### ISSUE TITLE
599 in Literatur bitte nicht liefern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#107]
Hallo Stephan, könntest du bitte das Feld 599 in der Literatur an die BSB nicht mitliefern? Wir wollen nicht, dass diese Infos zur Verfügung stehen, auch wenn sie nur im MARC-Datensatz enthalten sind und nicht publiziert werden. 
Beispiel: https://opac.rism.info/search?id=lit30027115&View=rism
In [MARC ](https://opac.rism.info/id/rismauthorities/lit30027115?format=marc)ist sichtbar: 599 RISM-HB

**Comment by bjoernkessler** [comment]
Dieser Issue wurde in das task-Repository verschoben. Dort issue no. 312
