### ISSUE TITLE
Vollständige Literaturangaben anzeigen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#108]
In der Literatur, egal ob in der Vollanzeige oder über einen Titel, werden viele Felder geliefert aber leider nicht angezeigt.

Bitte alle gelieferten Daten publizieren. Es wirkt unprofessionell, wenn ein bibliographisches Projekt unvollständige bibliographischen Daten anbietet.

Beispiele: 

- [Frescobaldi Thematic Catalogue Online](https://opac.rism.info/search?id=lit30026105&View=rism)
- [Pauline Viardot. Systematisch-bibliographisches Werkverzeichnis (VWV)](https://opac.rism.info/search?id=lit30026835&View=rism)
URL wird nicht angezeigt.

Annotated Catalogue of Chopin's first Editions
https://opac.rism.info/search?id=lit30025545&View=rism
Verlag wird nicht angezeigt.

**Comment by jenniferward** [comment]
Noch ein Beispiel:
https://opac.rism.info/search?id=lit30028750&View=rism
Es fehlt die Angabe "Den Haag, Koninklijk Conservatorium Den Haag, Master's thesis" (Feld Fußnoten). Dass hier um eine Masterarbeit geht kann man ohne diese Angaben nicht erkennen.

**Comment by MFalletta** [comment]
siehe auch Anzeige Literatur ohne Kürzel #11  und  Popup-Fenster Literatur #12

**Comment by BernLutz** [comment]
Wäre folgende Anzeige in Ihrem Sinne @MFalletta @jenniferward ?
1. Autor [als Link]: (100$a, d)
2. Sonstige Person [als Link] und ihre Funktion: (700$a, 4)
3. Titel: (240$a)
4. Art/Inhalt: (240$b)
5. Ausgabeform: (240$h)
6. Zusätzlicher Titel: (730$a)
7. Verlagsort: (260$a)
8. Verlag: (260$b)
9. Jahr: (260$c)
10. Umfang: (300$a)
11. Medientyp: (337$a)
12. Kürzel: (210$a)
13. ISBN: (20$a)
14. ISSN: (22$a)
15. ISMN: (24$a)
16. Sprache: (41$a)
17. Land: (44$a)
18. Körperschaftsname [als Link]: (710$a)
20. In [als Link]: (760$t)
21. Schlagwort: (650$a)
22. Ort: (651$a)
23. Ausgabe: (250$a)
24. Früherer Eintrag [als Link]: (780$t)
25. Folgeeintrag [als Link]: (785$t)
26. Bemerkungen: (500$a)
27. Hinweis zur Dissertation: (502$a)
28. Link: (856$u, z)
29. Bestandsangabe: (520$a)

**Comment by MFalletta** [comment]
Ich sitze gerade dran eine Aufstellung zusammenzustellen. Das Ergebinis kommt am Montag.

**Comment by MFalletta** [comment]
Folgende Reihenfolge erscheint uns sinnvoll:

Bezeichnung		zugehörige Felder

RISM-Kurztitel:	Kurztitel (210$a)
Titel:		        Titel (240 $a) 
		                Zusätzlicher Titel (730$a) 
Personen(en):		Autor (100$a)
		                Sonstige Person (700 $a und $4)
Körperschaft(en):	Körperschaft (710 $a und $4)
Verlag:		        Verlagsangaben (260 $a und $b und $c)
Ausgabe:		         Ausgabe (250$a)
Umfang:		        Material (300$a)
Serie/Reihe/Periodikum:	    In: (760 $t und $g)
ISBN/ISSN/ISMN:	ISBN (020$a)
		               ISSN (022$a)
		               ISMN (024$a)
URL:		       URL (856 $u und $z)
Anmerkung:	       Bemerkungen (500$a)
		               Hinweis zur Dissertation (502$a)
Früher <--		Früherer Eintrag (780$t)
Fortsetzung -🡪	Folgeeintrag (785$t)
Erschienen:		Bestandsangabe (520$a)
Sprache:		       Sprache (041$a)
		               Land (044$a)

**Comment by BernLutz** [comment]
Kann das Ticket geschlossen werden @MFalletta ?
