### ISSUE TITLE
Vollständige Institutionsangaben anzeigen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#109]
In der Institutionsanzeige, egal ob in der Vollanzeige oder über einen Titel, werden viele Felder geliefert aber leider nicht angezeigt.

Bitte alle gelieferten Daten publizieren. 

Wenn wir z.B. nur die Postadresse einer Institution veröffentlichen und die URL nicht, haben die Nutzer den Eindruck, dass sie einen Brief schreiben müssen. (Tatsächlich.)

#108

**Comment by jenniferward** [comment]
Die Anzeige der Link zum GND verwirrt einige Nutzer: Sie glauben, die Quelle läge an der DNB. Kann man eine klare optische Trennung zwischen unseren beschreibenden Angaben und die Normdaten machen?

Siehe z.B. Wikipedia, wo die Normdaten ein eigenes Kästchen haben (unten auf der Seite)
https://de.wikipedia.org/wiki/Ludwig_van_Beethoven

**Comment by BernLutz** [comment]
Die Anzeige der Institutionsangaben wurde vollständig überarbeitet.
