### ISSUE TITLE
Anzeige Literatur ohne Kürzel

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#11]
Die Literatur wird ohne Kürzel angezeigt. Ist auch nicht im MARC21 record.

**Comment by HirschSt** [comment]
Bitte Beispiel nennen.

**Comment by bjoernkessler** [comment]
Dieser Eintrag sollte das Kürzel ZimH enthalten:
https://opac.rism.info/search?id=lit272&View=rism

Das Kürzel ist in der XML Datei enthalten (210$a) wird aber nicht angezeigt.

Wo das Kürzel angezeigt wird bleibt zu diskutieren.

**Comment by bjoernkessler** [comment]
Hat zu tun mit #12

**Comment by jenniferward** [comment]
Auf Englisch: Short title

N.B.: "Short title" ist schon vergeben aber wird falsch verwendet! #35

**Comment by jenniferward** [comment]
Siehe  #311

**Comment by BernLutz** [comment]
Das Kürzel wird nun in der Literatur angezeigt.
