### ISSUE TITLE
667 in Institutionen nicht liefern

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#110]
Hallo Stephan, mir ist heute aufgefallen, dass auch die internen Bemerkungen der Institutionen an die BSB geliefert werden. Die werden zwar nicht angezeigt, aber in der MARC-Datei sind sie sichtbar.

Beispiel: In einer Privatsammlung wird die Veröffentlichung der privaten E-Mail-Adresse ausdrücklich nicht gewünscht. Sie ist aber in der MARC-Datei zu finden:
https://opac.rism.info/search?id=ks51001754&View=rism
https://opac.rism.info/id/rismauthorities/ks51001754?format=marc

#107

**Comment by bjoernkessler** [comment]
Dieser Issue wurde in das task-Repository verschoben. Dort issue no. 312
