### ISSUE TITLE
Arbeit in mehreren Reitern soll möglich sein

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#111]
Ich muss sehr oft mehrere Suchanfragen durchführen. Ich habe mehrere Reiter gleichzeitig offen. Das Herumspringen war im alten OPAC möglich aber jetzt nicht mehr. Die Suche wird stillschweigend zurückgesetzt:
![image](https://user-images.githubusercontent.com/18663291/45754626-6a1a1300-bc1c-11e8-8865-f5464ee14e72.png)

Bitte mehrere gleichzeitige Sessions erlauben!

**Comment by BernLutz** [comment]
Gleichzeitige Sessions sind möglich.
