### ISSUE TITLE
Einige Institutionen haben nichts mit RISM zu tun

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#117]
Einige Institutionen, die nichts mit RISM zu tun haben, werden im OPAC angezeigt. Das ist verwirrend für die Nutzer. Alles, was im OPAC angezeigt wird, soll RISM-relevant sein.

Beispiele:
Eine Suche nach "D-B", Filter Institutionen. Unter den Ergebnissen sind:
[DB Station & Service AG [Berlin] / Marketingkommunikation](https://opac.rism.info/search?id=ks47803&View=rism)
[Dresdner Bank](https://opac.rism.info/search?id=ks8530&View=rism)

**Comment by BernLutz** [comment]
@HirschSt Die KS-Sätze werden in den Daten geliefert. Bei Bedarf müssten diese in Muscat gelöscht werden, z.B.:
  DB  Station & Service AG [Berlin] / Marketingkommunikation = https://muscat.rism.info/admin/institutions/47803
