### ISSUE TITLE
Kein Ton bei der Incipiteingabe

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#124]
iPhone und iPad: Bei der Erweiterten Suche: Wenn ich eine Taste der Klaviatur drücke, soll die Note ertönen.

Ich höre nichts.

**Comment by bjoernkessler** [comment]
Funktioniert in chrome auf ubuntu 18.04 mit pulseaudio und auch auf meinem android-telefon.

Wenn es bekannte Einschränkungen gibt, könnte man einen Hinweis auf die Systemvorraussetzungen mit in die Seite einbinden.

**Comment by jenniferward** [comment]
Ja, das können wir machen. Ich hoffe aber, dass die BSB solche Probleme mit älteren Geräten behebt. Ich hatte extra bei der BSB nachgefragt, weil meine Geräte älter sind. Die Antwort war: "Grundsätzlich unterstützen wir die gängigen und in allgemeiner Verwendung befindlichen Geräte, das schließt auch etwas ältere Versionen mit ein. iOS-Geräte waren im Sommer auch schon Bestandteil der Tests, der Rückmeldungen an uns, und der darauf folgenden Fehlerbehebungen."

**Comment by jenniferward** [comment]
Es ist nicht möglich, mit neueren Geräten zu testen.
