### ISSUE TITLE
Töne muss man 2x drücken

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#126]
iPod, iPad, Erweiterte Suche: Die Erwartung ist: Noten können über die virtuelle Klaviatur eingegeben werden und die Suchanfrage wird auf dem Notensystem angezeigt.

Auf meinen Geräten muss ich zunächst 2 Mal auf eine Taste drücken, bevor der Ton auf dem Notensystem und im Suchfeld angezeigt wird (z.B. F). Wenn ich das F wiederhole, wird er angezeigt. Wenn ich dann das E eingeben will, muss ich 2 Mal auf die Taste E drucken, bevor es angezeigt wird.

**Comment by BernLutz** [comment]
Auf dem iPhone X taucht dieses Problem nicht mehr auf.
