### ISSUE TITLE
Anzeige "Externe Bemerkungen" in Personen-Datensätzen

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#13]
Das Feld "Externe Bemerkungen" (680$a) wird in der Vollanzeige der Personen nicht angezeigt.
Beispiel: https://opac.rism.info/search?id=pe174719&View=rism
Bitte das Feld einfügen (z.B. vor den Lexika).

**Comment by alexandermarxen** [comment]
Dringend, da teilweise Angaben über die Quelle von Informationen nur im Feld 680 stehen. Außerdem gehen zahlreiche weitere wichtige Informationen für die Nutzer verloren.

**Comment by alexandermarxen** [comment]
Aus aktuellem Anlass nochmal ein push für dieses Ticket:
Wir haben die Mail eines Nutzers erhalten, der nach "Bainville" gesucht hat und nur diesen Datensatz angezeigt bekam:
https://opac.rism.info/search?id=pe30013821&View=rism
In diesem Datensatz steht Bainville nur im nicht veröffentlichten Bemerkungsfeld. Das ist für Nutzer SEHR verwirrend!

**Comment by BaMikusi** [comment]
Bin ganz einverstanden, da ich als Nutzer früher mehrmals ähnliche Erfahrungen gemacht habe. Die Ursache habe ich damals als Außenseiter nicht erraten können, hatte aber gerade deshalb den unangenehmen Eindruck, dass die Suche im OPAC irgendwie unzuverlässig sei.

**Comment by alexandermarxen** [comment]
Die Feldbezeichnung entspricht Feld 500 im Bestand Quellen:

Deutsch: Bemerkungen
Englisch: Notes
Französisch: Notes
Italienisch: Note generali
Spanisch: Observaciones

**Comment by BernLutz** [comment]
Feld 500 wird im OPAC angezeigt.
