### ISSUE TITLE
Bild für Person überschneidet sich mit dem Text

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#135]
Mit dem iPhone, in der Vollanzeige:
Beispiel: https://opac.rism.info/search?id=1001026840&View=rism

Wenn man auf den Namen klickt, um die Normdatei anzusehen, überschneidet sich das Bild der Person mit dem Text. Kann sich der Text nicht anpassen?
![image](https://user-images.githubusercontent.com/18663291/46130734-4406fb00-c23a-11e8-84ec-e735be42ab5b.png)

**Comment by BernLutz** [comment]
Auf dem iPhone X taucht dieses Problem nicht mehr auf.
