### ISSUE TITLE
Suche nach Namens-Varianten

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#14]
Die Suche nach Namens-Varianten funktioniert nicht so, wie erwartet.
"Melante" ist eine Namensvariante zu "Telemann, Georg Philipp".
Die Suche nach "Melante" in "Alle Felder" ergibt 550 Treffer
Die Suche nach "Melante" in "Komponist" ergibt 265 Treffer
Das zu erwartende Ergebnis müsste in allen Fällen bei 5845 Treffern liegen.

**Comment by BernLutz** [comment]
Die Verweisformen werden für die Suche nun berücksichtigt.
