### ISSUE TITLE
Zuschreibung "Zweifelhaft" wird komisch angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#141]
In diesem Titel
https://opac.rism.info/search?id=1001037551&View=rism
wird statt die Zuschreibung "Zweifelhaft" [???de.rism.personattribute.z???] angezeigt.

![image](https://user-images.githubusercontent.com/18663291/46656028-5de6fd00-cbad-11e8-978e-28410fc6b8f1.png)

**Comment by bjoernkessler** [comment]
Auch andere Titel, die mit zweifelhafter Zuschreibung markiert wurden, werden auf diese fehlerhafte Weise dargestellt:

https://opac.rism.info/search?id=603000393&View=rism

**Comment by BernLutz** [comment]
Erledigt
