### ISSUE TITLE
Einbände werden nicht richtig verlinkt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#144]
In Muscat, Feld 563, Einband, Subfeld $u, Related record, werden zusammengebundenen Titel verlinkt. 
Diese Verlinkung wird im OPAC nicht angezeigt. 

Beispiel aus Muscat (Ausschnitt):
https://muscat.rism.info/admin/sources/1001028358/

![image](https://user-images.githubusercontent.com/18663291/46674580-c4cfda80-cbdc-11e8-9a16-5eb8d98595b2.png)

Anzeige im OPAC:
https://opac.rism.info/search?id=1001028358&View=rism
Einband: bound together with bound together with bound together with bound together with bound together with bound together with

Siehe auch: #53

**Comment by BernLutz** [comment]
In Muscat ist 563$u mit "UNUSED - WILL BE REMOVED" gekennzeichnet. Ist diese Anforderung noch aktuell @jenniferward ? 
Falls ja,  nehmen wir die Verlinkungen zu den IDs gerne mit in die Anzeige auf.

**Comment by jenniferward** [comment]
Nein, ist nicht mehr aktuell. Das Thema "Darstellung der Konvoluteinträge" ist wohl ein größeres Thema und wird später ausführlicher diskutiert.
