### ISSUE TITLE
Fingerprint wird nicht angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#145]
Fingerprints werden in MARC 026 eingegeben und geliefert aber nicht angezeigt.

Beispiel:
990064189
Fingerprint: n?n, n;t, v.at BeDr C 1695R

Im OPAC:
https://opac.rism.info/search?id=00000990064189&View=rism

Siehe auch #53

**Comment by HirschSt** [comment]
gilt ebenso für das Testrelease 08/19

**Comment by BernLutz** [comment]
Da 026$a-$e im Material angezeigt werden soll, benötigen wir in den Daten noch einen Marker in $8 (analog zu den anderen Feldern der Materialschichten).

**Comment by HirschSt** [comment]
Woher stammt die Anforderung, den Fingerprint im Material anzuzeigen? Wenn nötig, muss hier die Muscat-Konfiguration geändert werden, dazu wäre dann dort ein entsprechendes Ticket zu erstellen.

**Comment by MFalletta** [comment]
Fingerprint ist in der Liste genannt, siehe #168

**Comment by BernLutz** [comment]
Vorgaben klären (RISM ZR / SLUB)

**Comment by jenniferward** [comment]
Fingerprint wird nicht in Material eingegeben. Die Angaben sollen wie in Muscat angezeigt werden:
EN
Fingerprint identifier
Unparsed fingerprint (026 $e)
First/second group (026 $a)
Third/fourth group (026 $b)
Date (026 $c)
Number of volume/part (026 $d)



ES:  Identificador tipográfico
Identificador tipográfico no disgregado (026 $e)
Primero/segundo grupo (026 $a)
Tercero/cuarto grupo (026 $b)
Fecha (026 $c)
Número de volumen/parte (026 $d)

026$e kommt am häufigsten vor.
Für mich ist eine Plazierung in "Weitere Angaben und Bemerkungen" ausreichend.

**Comment by BernLutz** [comment]
Hätten Sie noch Beispiele für 026$a-d @jenniferward ?
In Muscat wird offenbar das übergeordnete Label "Fingerprint identifier" für alle Subfields verwendet. Soll dies im OPAC ebenfalls so gehandhabt werden?

**Comment by jenniferward** [comment]
Das Feld an sich heißt in Muscat "Fingerprint identifier" auf EN, aber die Subfields werden so bezeichnet wie oben geschrieben.  Die RISM-Mitarbeiter haben dann die Wahl zwischen Fingerprintangabe in einer Zeile ($e) oder verteilt auf 4 Zeilen, je nach Fingerprintstandard. Ich finde eine Feldbelegung 148 Mal in den Daten (Stand August 2021), 146x  in nur $e, 1x ohne $e (990007087), und 1x mit a-e (1001121857).
Ich glaube, wir sollen beides erlauben, auch wenn $a-d äußerst selten vorkommen.

**Comment by BernLutz** [comment]
Vielen Dank für die Informationen @jenniferward 
Dies wäre dann z. B. die Lösung für die ID 1001121857:
![Fingerprint_RISM_OPAC](https://user-images.githubusercontent.com/44613113/142220614-a071b3fb-9b88-4c89-a95b-1a1c113d5f0c.jpg)
Wäre dies in Ihrem Sinne?

**Comment by jenniferward** [comment]
Ja, ich finde das völlig in Ordnung, vielen Dank! 

Notiz für mich: Hilfetext ergänzen damit die Nutzer den Fingerprint verstehen.
