### ISSUE TITLE
Doppelte Besetzungshinweise werden in einer Zeile angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#148]
Das Feld Besetzungshinweis (240 $m) ist in Muscat verdoppelbar, d.h. mehrere Angaben sind möglich. 

Beispiel:
![image](https://user-images.githubusercontent.com/18663291/47708233-ed705080-dc2d-11e8-91f8-3131b83bb669.png)

Im OPAC werden sie leider in einer Zeile angezeigt:
https://opac.rism.info/search?id=1001049539&View=rism
![image](https://user-images.githubusercontent.com/18663291/47708323-1abcfe80-dc2e-11e8-8d67-e882a1b5a6b8.png)

Bei mehreren Angaben bitte untereinander anzeigen.

**Comment by BernLutz** [comment]
Die Besetzungshinweise werden jetzt in getrennten Zeilen angezeigt.
