### ISSUE TITLE
Filter "Datierung" bietet falsche Anzahl an

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#153]
Ich finde den Filter "Datierung" unlogisch.

1. Suche nach "Liszt": 167 Ergebnisse.
2. Filter Datierung: klicken auf: >=1912  (33) 
für alle Quellen nach 1912
3. 33 Ergebnisse werden angezeigt aber im Filter "Dateriung" sehe ich weit über 33 Ergebnisse:
![image](https://user-images.githubusercontent.com/18663291/47906228-150f2500-de89-11e8-81f2-19e12cc0431b.png)
4. Wenn ich hier klicke: <= 1876 (156)
erwarte ich 156 Ergebnisse. Ich bekomme aber nur 4.

Diese 4 Quellen haben mehrere Materialarten, mal nach 1912 und mal vor 1876. Das ist in Ordnung, aber die Zahl "156" ist irreführend.

**Comment by BernLutz** [comment]
Die Angabe in den Datierungsfiltern entspricht nun der Treffermenge.
