### ISSUE TITLE
Links im RISM SPARQL-Endpoint sind tot

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#154]
Wenn ich von der Seite "RISM SPARQL-Endpoint" ausgehe
https://opac.rism.info/index.php?id=16&L=1
dann klicke ich auf "Submit", bekomme ich eine Seite "SPARQL Query Results to XHTML (XSLT)"
Auf dieser Seite gibt es 3 Spalten: s, p und o.
Stichprobenartig scheinen die Links in Spalte s (Beispiel:
http://data.rism.info/id/rismauthorities/10626#lit )
und Spalte p (Beispiel: http://bsb-muenchen.de/ont/bsbMusicOntology#lexicon =
tot zu sein.
Fehlermeldung: 404 Not Found bzw. 404 Seite nicht gefunden

**Comment by BernLutz** [comment]
Generell sollten die URIs jetzt wieder korrekt funktionieren. 
Hier ein Beispiel: Pasten Sie einfach folgende SPARQL-Query um die URI v. Beethoven, Ludwig van zu bekommen:

SELECT * WHERE {
      ?s ?p 'Beethoven, Ludwig van'
}
LIMIT 2

[Link auf das Ergebnis ](https://opac.rism.info/sparql?query=PREFIX+rdf%3A%3Chttp%3A%2F%2Fwww.w3.org%2F1999%2F02%2F22-rdf-syntax-ns%23%3E%0D%0APREFIX+bsbmo%3A%3Chttp%3A%2F%2Fbsb-muenchen.de%2Font%2FbsbMusicOntology%23%3E%0D%0APREFIX+gnd%3A%3Chttp%3A%2F%2Fd-nb.info%2Fstandards%2Felementset%2Fgnd%23%3E%0D%0APREFIX+isbd%3A%3Chttp%3A%2F%2Fiflastandards.info%2Fns%2Fisbd%2Felements%2F%3E%0D%0APREFIX+rdagr2%3A%3Chttp%3A%2F%2Fmetadataregistry.org%2Furi%2Fschema%2FRDARelationshipsGR2%2F%3E%0D%0APREFIX+dc%3A%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Felements%2F1.1%2F%3E%0D%0APREFIX+dcterms%3A%3Chttp%3A%2F%2Fpurl.org%2Fdc%2Fterms%2F%3E%0D%0APREFIX+bibo%3A%3Chttp%3A%2F%2Fpurl.org%2Fontology%2Fbibo%2F%3E%0D%0APREFIX+mo%3A%3Chttp%3A%2F%2Fpurl.org%2Fontology%2Fmo%2F%3E%0D%0APREFIX+frbr%3A%3Chttp%3A%2F%2Fpurl.org%2Fvocab%2Ffrbr%2Fcore%23%3E%0D%0APREFIX+rel%3A%3Chttp%3A%2F%2Fpurl.org%2Fvocab%2Frelationship%2F%3E%0D%0APREFIX+rdagr1%3A%3Chttp%3A%2F%2Frdvocab.info%2FElements%2F%3E%0D%0APREFIX+umbel%3A%3Chttp%3A%2F%2Fumbel.org%2Fumbel%23%3E%0D%0APREFIX+daia%3A%3Chttp%3A%2F%2Furi.gbv.de%2Fontology%2Fdaia%2F%3E%0D%0APREFIX+geonames%3A%3Chttp%3A%2F%2Fwww.geonames.org%2Fontology%23%3E%0D%0APREFIX+rdfs%3A%3Chttp%3A%2F%2Fwww.w3.org%2F2000%2F01%2Frdf-schema%23%3E%0D%0APREFIX+owl%3A%3Chttp%3A%2F%2Fwww.w3.org%2F2002%2F07%2Fowl%23%3E%0D%0APREFIX+vcard%3A%3Chttp%3A%2F%2Fwww.w3.org%2F2006%2Fvcard%2Fns%23%3E%0D%0APREFIX+org%3A%3Chttp%3A%2F%2Fwww.w3.org%2Fns%2Forg%23%3E%0D%0APREFIX+foaf%3A%3Chttp%3A%2F%2Fxmlns.com%2Ffoaf%2F0.1%2F%3E%0D%0APREFIX+cc%3A%3Chttps%3A%2F%2Fcreativecommons.org%2Fns%23%3E%0D%0A%0D%0ASELECT+*+WHERE+%7B%0D%0A++++++%3Fs+%3Fp+%27Beethoven%2C+Ludwig+van%27%0D%0A%7D%0D%0ALIMIT+2%0D%0A++++&xhtml=true)

Funktionierende URI: http://data.rism.info/id/rismauthorities/pe11035 

Zwei Einschränkungen gibt es jedoch noch:

1) Aktuell liefern die Literaturlinks im RISM-OPAC keine Treffer, deshalb erscheint jetzt "korrekt" der RISM-OPAC mit der 0-Treffer-Seite statt des Http-Fehlers. Die Literaturlinks werden wir in einem nächsten Schritt zur Anzeige bringen. Dann sollte auch dieses Problem gelöst sein, vgl. #287 

2) Generell müssen nicht alle URIs im SPARQL-Endpoint zwingend auflösbar sein. http://bsb-muenchen.de/ont/bsbMusicOntology#lexicon  ist nur ein Identifier für einen Namespace. Im saubersten und optimalen Fall läge dahinter zwar eine aufrufbare Ontologiedefinition. Diese Anpassung müsste in einem größeren Schritt für alle BSB-Projekte angepasst werden. Der Dienst funktioniert einwandfrei ohne eine solche abrufbare Ontologie.

**Comment by BernLutz** [comment]
Bitte prüfen und ggf. schließen.

**Comment by jenniferward** [comment]
Danke, funktioniert für mich wie oben beschrieben.
