### ISSUE TITLE
Suche nach Incipits über die virtuelle Tastatur im RISM OPAC funktioniert nicht

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#156]
Die Suche nach Incipits über die virtuelle Tastatur im RISM OPAC funktioniert nicht!
Ein Beispiel: Simple Suche per Tonbuchstaben BAGBGFBEEF findet richtig dieses Stück (Incipit 1.4.1): https://opac.rism.info/search?id=1001002143&View=rism
Die entsprechende Eingabe der genauen Tonhöhen über die virtuelle Tastatur ergibt: A#G#GA#GFA#D#D#F und findet nichts.
Das lässt sich mit vielen Beispielen wiederholen und wurde schon lange beobachtet.
Interessanterweise funktioniert es auch nicht, wenn man das Incipit ohne Vorzeichen eingibt, obwohl dann der gleiche Suchcode wie oben ausgegeben wird.
Ich hatte hier verschiedentlich Beschwerden, dass im Zusammenhang mit den Recherchen für das neue Köchel-Verzeichnis Werke nicht gefunden werden, obwohl sie bei RISM verzeichnet sind.
Da das Ganze so unzuverlässig ist, würde ich dringend raten, die Suche "Notenanfang per Klaviatur" abzuschalten, bis eine funktionierende Lösung existiert.

**Comment by BernLutz** [comment]
Das Problem wurde durch die BSB-IT behoben.

**Comment by KlausKeil** [comment]
Das klappt jetzt. Man muss aber darauf achten, dass bei der Suche im Feld music incipit die Vorzeichen keine Rolle spielen. Ins keyboard muss man exact eingeben: bBbAGbBGFbBbEbEF.
