### ISSUE TITLE
Vorschlagsnoten werden nicht korrekt angezeigt

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#157]
Jeweils im Incipit 1.2.1 stimmt die Anzeige der ersten 16tel-Vorschläge nicht:

https://opac.rism.info/search?id=1001043147&View=rism

https://opac.rism.info/search?id=1001046718&View=rism

In Muscat ist die Anzeige korrekt.

**Comment by BernLutz** [comment]
Die Anzeige ist nun durch ein Verovio-Update im RISM-OPAC korrekt. Die Balkung von Kleinstichnoten #18 müsste dagegen in Verovio angepasst werden.
