### ISSUE TITLE
Normdatei Personen: Link zu Literatur

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#16]
Die Kürzel in der Normdatei wie DEUMM/b, MGG, Grove6, etc. bei Lexika sind nicht verständlich und müssen entschlüsselt werden. Ihnen entspricht ein Eintrag in der Literatur-Datei. 
Das Kürzel sollte also ein Link auf den entsprechenden Eintrag in der Literatur-Datei enthalten, so wie es auch bei den Titeln ist. 
Beispiel Personeneintrag: https://opac.rism.info/search?id=pe2347&View=rism
Beispiel Titel: Titel mit Literatur: https://opac.rism.info/search?id=500053294&View=rism
Beispiel Literatureintrag: Literatureintrag 1263 (hat kein Link) für MGG

**Comment by jenniferward** [comment]
Evtl. die Kürzel mit Mausover entschlüsseln.

**Comment by BernLutz** [comment]
Die Literatur wird in den PE- und KS-Sätzen nun verlinkt.
