### ISSUE TITLE
Anzeige von 240$o im Titel

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#162]
Bisher wird nur subfield $k ausgewertet, der  Eintrag unter subfield $o (z.B. 'Arr') wird nicht in den Titel übernommen.

Beispiel: https://opac.rism.info/search?id=1001050187&View=rism bzw. https://opac.rism.info/id/rismid/1001050187?format=marc

Die Titelanzeige soll statt **Die Rückfahrt des Kaisers (Excerpts)** folgendermaßen lauten:

**Die Rückfahrt des Kaisers (Excerpts. Arr)**

**Comment by BernLutz** [comment]
Erledigt!
