### ISSUE TITLE
Folgeeinträge werden doppelt angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#163]
Beispiel:
https://opac.rism.info/search?id=00000991006184&View=rism

Folgeeinträge: | 00000991006186, 00000991006186, 00000991006187, 00000991006187, 00000991006188, 00000991006188

Es gibt nicht 6 Folgeeinträge sondern 3.

**Comment by BernLutz** [comment]
Gibt es hier noch Änderungsbedarf? Aktuell werden die Informationen nicht angezeigt. Die Beispiel-ID (https://opac.rism.info/search?id=991006184&View=rism) enthält 3 Folgeeinträge in Marc 785. Das Feld ist jedoch weder in den Anforderungen an die Drucke noch im Muscat-Marcschema enthalten.

Falls 785 angezeigt werden soll, benötigen wir noch Angaben zur gewünschten Position in der Anzeige und die Übersetzungen der Label.

**Comment by jenniferward** [comment]
Nicht mehr relevant
