### ISSUE TITLE
Verlinkungen falsch

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#167]
In diesem Titel https://opac.rism.info/search?id=212001131&View=rism 
sind drei Interpreten angegeben: 
Interpret: | Rybitzky, Adam ; Lotti, Johann Friedrich <1653-> [ermittelt] ; Houlondel, Robert du <1669-> [ermittelt]
Rybitzka ist nicht blau unterlegt. 
Bei Lotti bekommt man den Eintrag von Rybitzka angezeigt; bei Houlondel den von Lotti. Houlondel kann man gar nicht aufrufen.

**Comment by BernLutz** [comment]
Die Personen werden nun korrekt verlinkt.

**Comment by BernLutz** [comment]
Im Titel https://opac.rism.info/metaopac/search?View=rism&id=1001122735&View=rism
führt der Klick auf "Riederer, Maria" zur Anzeige von "Zihl, Theresia" und der Klick auf "Gschwenter, Regalat" zur Anzeige von "Riederer, Maria".
