### ISSUE TITLE
Nicht alle Incipits werden angezeigt

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#169]
Im Titel 456009267 werden nicht alle Incipits angezeigt, sondern nur die Sätze 1-18. 
https://opac.rism.info/search?id=456009267&View=rism
In MARC-XML geht die Nummerierung bis 1.32.1

**Comment by jenniferward** [comment]
Siehe https://opac.rism.info/search?id=000106827&View=rism 

In Chrome:  Beide Incipits jetzt OK (vor 5 Minuten stand "Error loading SVG")
In Firefox:
Man sieht 1.1.2 aber nicht 1.1.1:
![image](https://user-images.githubusercontent.com/18663291/52698091-174a4a80-2f73-11e9-874f-35ecbfa56844.png)

Druckt man auf F5, sieht man 1.1.1 aber nicht 1.1.2:
![image](https://user-images.githubusercontent.com/18663291/52698144-2a5d1a80-2f73-11e9-9213-842c954866b8.png)

**Comment by BernLutz** [comment]
Die beiden Probleme wurden durch die BSB-IT behoben.

**Comment by jenniferward** [comment]
@BernLutz : Wird es erst nach dem Update sichtbar? In Firefox sehe ich folgendes:
https://opac.rism.info/search?id=000106827&View=rism
![image](https://user-images.githubusercontent.com/18663291/55638125-c57dae00-57c6-11e9-9a23-d288815b611b.png)

**Comment by jenniferward** [comment]
Entschuldigung, das hat wohl mit #3 zu tun.
