### ISSUE TITLE
Normdaten sind leer (Institutionen, Personen)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#170]
Ich habe im OPAC nach "kiev" gesucht (Chrome). Es gibt 9 Ergebnisse. Nr. 7 und 9 sind komplett leer, kein Text wird angezeigt.
In der Trefferliste:
![image](https://user-images.githubusercontent.com/18663291/52620456-e865a300-2ea4-11e9-81b3-e78b0fd6fb45.png)

In der Vollanzeige:
Nr. 7: 
![image](https://user-images.githubusercontent.com/18663291/52620589-3e3a4b00-2ea5-11e9-9d4a-489671684c6f.png)

Nr. 9: 
![image](https://user-images.githubusercontent.com/18663291/52620606-48f4e000-2ea5-11e9-91b4-b5b509396635.png)

Text wird allerdings in der MARCXML-Datei geliefert.

**Comment by KlausKeil** [comment]
Es gibt nur noch 5 Treffer. Ist das Ticket erledigt?

**Comment by jenniferward** [comment]
Aus meiner Sicht, ja.
