### ISSUE TITLE
Führende Nullen in RISM-IDs werden nicht ignoriert

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#173]
Heute habe ich im OPAC in der Erweiterten Suche, Feld RISM ID. nach diesem RISM-ID gesucht:
990065011

Ergebnis: Keine Treffer.

Erst wenn ich 00000990065011 eingebe, wird der Titel gefunden.
https://opac.rism.info/search?id=00000990065011&View=rism

Die führenden Nullen sollen bitte nicht berücksichtigt werden, ich dachte, es war früher so.

**Comment by BernLutz** [comment]
Um die in #173 #174 #175 beschriebenen Phänomene zu vermeiden,  müssen die IDs eindeutig sein. 
RISM müsste eine eindeutige Ansetzungsform der IDs definieren. Idealerweise würde die Anpassung dann direkt in den Daten erfolgen. Vor einer Einspielung der Daten sollte die BSB-IT über die Form der IDs (mit oder ohne Nullen) informiert werden, um den OPAC entsprechend anzupassen.

**Comment by HirschSt** [comment]
@BernLutz vielen Dank, ich prüfe das und melde mich.

**Comment by HirschSt** [comment]
@BernLutz In den aus Muscat 2 importierten Drucktiteln wurde die ID mit den Vornullen ergänzt und so auch importiert. Beispiel https://beta.rism.info/admin/sources/993100007.xml
```xml
<marc:controlfield tag="001">00000993100007</marc:controlfield>
```
Allerdings sind nur die IDs entsprechend verarbeitet worden, nicht aber die internen IDs:
```xml
<marc:datafield tag="773" ind1="1" ind2=" ">
   <marc:subfield code="w">993104250</marc:subfield>
</marc:datafield>
```
Daher ergänze ich für den Export die internen Links mit den Vornullen, damit sie korrekt aufgelöst werden. In Muscat selbst führt das zu keinen Problemen. Korrekterweise müsste im jeweiligen Marc-Dokument in Muscat die Vornullen gestrichen werden - was kurzfristig nicht zu machen ist -, in der Mysql-Tabelle selbst sind sie bereits nicht vorhanden. Daher führen die URIs https://beta.rism.info/admin/sources/993100007.xml und https://beta.rism.info/admin/sources/00000993100007.xml zum selben Datensatz.

Es gibt hier weitere Lösungsoptionen, z.B. die Vornullen beim to_external herauszunehmen - das ist kurzfristig machbar, muss aber wegen möglicher Seiteneffekte getestet werden. Dies würde z.B. dazu führen, dass Permalinks wie z.B. https://opac.rism.info/search?id=00000993100007&View=rism nicht mehr funktionieren. Oder man ergänzt die internen Links direkt beim to_external, was auch nicht ganz sauber ist. Die BSB kann hier zunächst wenig tun. Ich erstelle hierzu demnächst ein followup

**Comment by jenniferward** [comment]
Bleiben die Vornullen für die Nutzer angezeigt? Es ist schwierig, zwischen z.B. 00000990065011, 000000990065011  und 0000990065011 zu unterscheiden, falls man die RISM-ID in der Literatur zitieren will.

**Comment by MFalletta** [comment]
@BernLutz Im OPAC bitte die Vornullen ignorieren und die Verlinkung ermöglichen. Die Verlinkung ist wichtiger als die erstmal nicht funktionierenden Permalinks.
Wir werden uns um eine zügige Bereinigung der Nullen im jeweiligen Marc-Dokument in Muscat kümmern.

**Comment by BernLutz** [comment]
Die Vornullen der IDs sind weggeparsed, werden aber nun unter dem ID-Sucheinstieg berücksichtigt. Dadurch werden beide Varianten – mit und ohne Nullen - gefunden. Durch diese Anpassung funktionieren auch die alten Permalinks wieder.
