### ISSUE TITLE
Link "Suchergebnisse für diese ID" funktioniert nicht

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#176]
In dieser Normdatei für eine Person:
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe40207837%22&Language=en
 
steht der Link "Suchergebnisse für diese ID". Wenn ich darauf klicke, bleibe ich auf derselben Seite. 
Angezeigt werden sollen mindestens 15 Titel, siehe z.B.
https://opac.rism.info/search?View=rism&q=Francesco+Maria+Benedetti&Language=en

**Comment by alexandermarxen** [comment]
Das ist ein Fehler in den Daten: Es handelt sich beim ersten Link um eine Dublette aus dem ICCU-Bestand. Beim "richtigen" Datensatz funktioniert der Link:
https://opac.rism.info/search?id=pe30004916&View=rism
bzw.
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe30004916%22

**Comment by MFalletta** [comment]
Unabhängig von dem ICCU-Beispiel wird scheinbar nicht das Feld Komponist durchsucht.

Beispiel Beethoven:
https://opac.rism.info/metaopac/search?View=rism&View=rism&q=pe11035 
297 Treffer, aber Beethoven nur 22 Mal als Komponist

https://opac.rism.info/metaopac/search?View=rism&View=rism&q=beethoven+ludwig
3861 Treffer
