### ISSUE TITLE
Eckige Klammern in 031$n

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#177]
same as https://github.com/rism-international/tasks/issues/496

Eckige Klammern bei den Vorzeichen führen zur falschen Darstellung von Incipits.

Beispiel: https://opac.rism.info/search?View=rism&id=452008590
die Schreibweise mit eckigen Klammern in 031$n kommt ca.1.500x in den Daten vor. 

Im OPAC werden die eckigen Klammern maskiert (in Verovio möglicherweise einfach weggeparst), siehe
https://opac.rism.info/verovio_incipits?f=pae&i=%40data%3a%25G-2%40c%24x%5bF%5d+%3d1%2f2-%27%27%5b8DDEG%5d%2f%5bFD%5d2G4F%2f im Vergleich mit
https://opac.rism.info/verovio_incipits?f=pae&i=%40data%3a%25G-2%40c%24xF+%3d1%2f2-%27%27%5b8DDEG%5d%2f%5bFD%5d2G4F%2f

Wenn das Maskieren entfällt, wird das Incipit korrekt angezeigt.

**Comment by KlausKeil** [comment]
Noch ein Beispiel, aus einem feedback von heute:
https://opac.rism.info/search?View=rism&id=452019994

**Comment by HirschSt** [comment]
Im Gegensatz zu vorher werden die Incipits jetzt dargestellt, oder?

**Comment by KlausKeil** [comment]
In Muscat wird das geklammerte Vorzeichen (in meinem Beispiel E) weggelassen. Im OPAC wird statt dessen das geklammerte Vorzeichen als Viertelnote angezeigt  (in meinem Beispiel wird es zu 4E), was natürlich verwirrend ist.

**Comment by HirschSt** [comment]
Ah, das habe ich übersehen, so ist es natürlich auch falsch: wie bei Muscat müsste das gesamte Element Vorzeichen in eckigen Klammer weggeparst werden, also aus:
```html
<img class="incipit" title="Incipit Nr. 1.1.1" alt="Incipit Nr. 1.1.1" 
src="/verovio_incipits?f=pae&amp;
i=%40data%3a%25C-3%40c%24bB%5bE%5d+1%2cG2G'D%2f%2cA'C%2cBA%2f1G2-G%2f'DCFE%2fDxC1D%2f">
```
![image](https://user-images.githubusercontent.com/6461776/61941886-a2a31f80-af98-11e9-8cd1-1cdf92dc39bc.png)

würde dann korrekterweise

```html
<img class="incipit" title="Incipit Nr. 1.1.1" alt="Incipit Nr. 1.1.1" 
src="/verovio_incipits?f=pae&amp;
i=%40data%3a%25C-3%40c%24bB+1%2cG2G'D%2f%2cA'C%2cBA%2f1G2-G%2f'DCFE%2fDxC1D%2f">
```
![image](https://user-images.githubusercontent.com/6461776/61941825-84d5ba80-af98-11e9-8fe6-428f563f048e.png)

**Comment by KlausKeil** [comment]
Ja, dann ist die falsche Note weg. 
Fehlt aber noch das globale Vorzeichen Es, das wenigstens ohne Klammern angezeigt werden sollte. 
Solange Verovio es nicht anzeigen kann, müssen also nur die [ ]  weggeparst werden. Ist es denn vorgesehen, Verovio so zu ändern, dass Vorzeichen in Klammern angezeigt werden können?

**Comment by jenniferward** [comment]
Habe es auch hier angesprochen https://github.com/rism-ch/muscat/issues/808 , ohne dieses Ticket zu kennen

**Comment by BernLutz** [comment]
Bitte an RISM CH weiterleiten @KlausKeil
