### ISSUE TITLE
Musikincipit nicht richtig dargestellt

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#18]
Kombination von Kleinstichnoten (qq..r) müssen gebalkt sein: 
280001096 Incipit 5.1.1. erste drei Noten

**Comment by BernLutz** [comment]
Die Balkung von Kleinstichnoten müsste in Verovio angepasst werden.

**Comment by KlausKeil** [comment]
Ja, das wissen wir. Es ist schon seit längerem eine Forderung an die Verovio Entwickler.

**Comment by BernLutz** [comment]
In diesem Fall würde ich das Ticket hier schließen. Sobald eine Anpassung in Verovio erfolgt ist, sollte die Anzeige auch im RISM-OPAC korrekt sein.
