### ISSUE TITLE
Links zu IDs finden auch Exemplare

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#181]
Das Sigel ROK-HAlim hat in Muscat die Institutions-ID 51002658. Nur eine Quelle ist mit diesem Sigel verknüpft. 

Im OPAC-Eintrag für dieses Sigel
https://opac.rism.info/search?id=ks51002658&View=rism
findet man den Link "Suchergebnisse für diese ID":
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22ks51002658%22
Klickt man darauf, sieht man nicht 2 Einträge (für das Sigel + Quelle), sondern auch einen dritten Eintrag, und zwar für diesen Druck von Handel aus D-MZp:
https://opac.rism.info/search?id=1001055215&View=rism

In Muscat und in der MARCXML-Datei sieht man, dass dieses Exemplar auch die ID 51002658 hat.

Ich glaube, das kommt vor, immer wenn die IDs von Institutionen und Exemplareinträgen identisch sind.
Beispiele:
-Findet auch einen Druck nicht aus D-KWER (51002801) sondern aus US-CAe (51002801): https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22ks51002801%22

-Findet nicht nur die Provenienz "Gymnasium zu Quedlinburg" (51002830) sondern auch einen Druck aus GB-Lbl (51002830):
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22ks51002830%22

Ich weiß nicht, ob z.B. Personen oder Literatur auch davon betroffen sind.

**Comment by jenniferward** [comment]
Personen: Ja, sind sie!
Britten-Pears Library (ks30003719) findet auch die Person Carl Friedrich Günther (pe30003719):
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22ks30003719%22

**Comment by BernLutz** [comment]
Erledigt
