### ISSUE TITLE
Permalinks funktionieren nicht

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#182]
Die Permalinks sehen heute anders aus und führen ins Leere!

Beispiel:
https://bsb-touch01.bsb-muenchen.int:8443/search?id=1001034106&View=rism

![Permalink 2019-05-02](https://user-images.githubusercontent.com/18736235/57061789-8441c680-6cbe-11e9-8040-ba73a9921831.png)

**Comment by BernLutz** [comment]
Danke für Ihren Hinweis auf die falsch generierten RISM-Permalinks. Der Fehler ging auf eine fehlerhafte Webserver-Konfiguration zurück und ist jetzt behoben.
