### ISSUE TITLE
Autocomplete soll auch Namen  mit Sonderzeichen anzeigen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#185]
Erweiterte Suche: Namen wie Fétis und Félix werden im Autocomplete nur angezeigt, wenn das Sonderzeichen eingegeben wird, d.h., bei Fetis wird nur 1 Namen angezeigt:

![image](https://user-images.githubusercontent.com/18663291/59335746-78a1e080-8cfd-11e9-88ee-bb8ee2269f1d.png)

Meiner Meinung nach wäre es benutzerfreundlicher, wenn das Autocomplete die Sonderzeichen ignorieren würde aber die betroffenen Namen trotzdem anzeigen würde. Was meinen die anderen, würde das zu vielen Ergebnisse führen? Bei slavischen Namen wäre das sehr schwierig für mich, wie sehe ich z.B. Žába?

**Comment by alexandermarxen** [comment]
Ich fände es auch viel komfortabler, wenn die Sonderzeichen ignoriert würden. Möglicherweise muss man mitunter ein paar Buchstaben mehr eingeben, aber das erscheint mir das kleinere Übel.

**Comment by BernLutz** [comment]
Beim Autocomplete können wir aktuell leider keine isolierten Anpassungen vornehmen, da die Funktion mit vielen weiteren BSB-Anwendungen gekoppelt ist. Hier sind aber bereits konkrete Schritte hin zu einer verbesserten Funktionalität geplant, vgl. auch #273

**Comment by jenniferward** [comment]
Heute finde ich Fétis auch mit Fetis, Žába leider nicht.
@MFalletta : Als Zwischenlösung schlage ich vor, einen Hinweis im OPAC-Hilfstext zu ergänzen.

**Comment by BernLutz** [comment]
Dieses Ticket können wir denke ich schließen @alexandermarxen  @jenniferward , oder sehen Sie hier noch Korrekturbedarf?

**Comment by alexandermarxen** [comment]
Soweit ich sehe funktioniert es jetzt einwandfrei. Vielen Dank!
