### ISSUE TITLE
Kirchentonarten ergänzen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#187]
In Muscat werden transponierte Kirchentonarten ergänzt. Diese sollen auch im OPAC suchbar sein. Aktuell sind die Kirchentonarten mit 1t bis 12t codiert. Entsprechend sollen die neuen transponierten Kirchentonarten mit 1tt bis 12tt codiert werden. 

Hier eine Liste mit den transponierten Kirchentonarten. "1tt" ist die Codierung. "1st tone (Dorian), transposed" ist die Anzeige im OPAC (Beispiel für 1t: https://opac.rism.info/search?id=403000066&View=rism )

1tt = 1st tone (Dorian), transposed
2tt = 2nd tone (Hypodorian), transposed 
3tt = 3rd tone (Phrygian), transposed
4tt = 4th tone (Hypophrygian), transposed 
5tt = 5th tone (Lydian), transposed
6tt = 6th tone (Hypolydian), transposed
7tt = 7th tone (Mixolydian), transposed 
8tt = 8th tone (Hypomixolydian), transposed 
9tt = 9th tone (Aeolian), transposed 
10tt = 10th tone (Hypoaeolian), transposed 
11tt = 11th tone (Ionian), transposed 
12tt = 12th tone (Hypoionian), transposed

**Comment by MFalletta** [comment]
Für die deutsche Version bitte folgende Bezeichnungen übernehmen:

1tt = 1. Ton (Dorisch), transponiert
2tt = 2. Ton (Hypodorisch), transponiert
3tt = 3. Ton (Phrygisch), transponiert
4tt = 4. Ton (Hypophrygisch), transponiert
5tt = 5. Ton (Lydisch), transponiert
6tt = 6. Ton (Hypolydisch), transponiert
7tt = 7. Ton (Mixolydisch), transponiert
8tt = 8. Ton (Hypomixolydisch), transponiert
9tt = 9. Ton (Aeolisch), transponiert
10tt = 10. Ton (Hypoaeolisch), transponiert
11tt = 11. Ton (Ionisch), transponiert
12tt = 12. Ton (Hypoionisch), transponiert
