### ISSUE TITLE
Links in rismAuthoritiesRDF.ttl sind tot

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#188]
Eine Meldung von einem Nutzer: Er schreibt "I am currently parsing your rismAuthoritiesRDF.ttl file" 
(vermutlich von https://opac.rism.info/index.php?id=10&L=0 ) und der Link, den er wiedergibt als https://t.co/Gmisg29eRi  (vermutlich http://data.rism.info/id/rismauthorities/pe30106403 ) führt ins Leere. Er wollte pe30106403 ( Szymanowski, Karol) . 

Siehe auch #154

**Comment by HirschSt** [comment]
Kurze Info zum Hintergund: die "_Links_" in den ttl-Daten sind in der Regel keine **URL**s, sondern **URI**s, daher werden sie u.U. nicht aufgelöst (auch wenn dies möglich wäre). Es handelt sich dabei um eine verbreitete Konvention bei RDF-Daten.

**Comment by jenniferward** [comment]
Auf der Edirom-Summer School hieß es von den Nutzern der RISM-Open-Data, dass die URIs, die ins Leere führen, für Verwirrung sorgen.
Beispiele:
data.rism.info/id/rismauthorities/30004689
data.rism.info/id/rismid/000100021

**Comment by BernLutz** [comment]
Vermutlich erledigt. Könnten Sie den Punkt noch einmal prüfen @jenniferward ? Danke!

**Comment by jenniferward** [comment]
Für mich ok, danke! Ich melde mich, wenn ich wieder etwas von unsern Nutzern höre.
