### ISSUE TITLE
Stand von Daten angeben

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#189]
Könnte die BSB den Stand bitte angeben, wann die Dateien auf der Seite https://opac.rism.info/index.php?id=10&L=0 zuletzt aktualisiert wurden? Englisch wäre z.B. Last update: June 2019

Der Satz "Gesamter Datenbestand, über 800.000 Datensätze" müsste wohl auch aktualisiert werden.

**Comment by BernLutz** [comment]
Wir gehen den Punkt zusammen mit der Erstellung von Testdatensätzen und der Versionierung an #236

**Comment by jenniferward** [comment]
Vielleicht jetzt machbar angesichts #290?

**Comment by BernLutz** [comment]
Ist eingetragen! Bis wir eine automatisierte Angabe ermöglichen können, werde ich den Stand der Daten nach den Einspielungen zusammen mit den "aktuellen Zahlen" manuell eingeben.
