### ISSUE TITLE
Personen: Suchergebnisse für diese ID benutzt Session-IDs

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#191]
Der Klick auf den Link "Suchergebnisse für diese ID" benutzt seit Kurzem Session-IDs. Diese Links sind daher nicht "wiederverwendbar".
Beispiel
https://opac.rism.info/search?id=pe27690&View=rism
Erzeugter Link:
https://opac.rism.info/metaopac/perma.do;jsessionid=21024B76FFF2A242AACA21BF2827D522.touch02?v=rism&q=-1%3d%22pe27690%22
Früher sahen diese Links so aus:
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe27690
Könnte bitte der alte Zustand wieder hergestellt werden?

**Comment by BernLutz** [comment]
Die Links sind nun nicht mehr an eine Session gebunden. Im konkreten Fall unterscheidet sich der generierte Link zu ihrem Beispiel allerdings durch ein ASCII-Zeichen (%22 bzw. ") am Ende: https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe27690%22
Könnten Sie dies noch einmal prüfen @alexandermarxen ? Vielen Dank!

**Comment by alexandermarxen** [comment]
Herzlichen Dank! Ja, das war mein Fehler, die Anführungszeichen am Ende sind wohl beim Copy&Paste verloren gegangen. Jetzt ist es perfekt!
