### ISSUE TITLE
Anzeige der Holding-ID soll grundsätzlich entfallen

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#196]
Es handelt sich bei den Holding-IDs immer um interne Nummern.

Beispiel https://rismtest.bsb-muenchen.de/search?id=00000991013433&View=rism

![image](https://user-images.githubusercontent.com/6461776/62465252-bddb0f80-b78e-11e9-95d6-3959de61990c.png)

soll werden zu:
![image](https://user-images.githubusercontent.com/6461776/62465438-2b873b80-b78f-11e9-96d2-57b65ec140be.png)

**Comment by BernLutz** [comment]
Die Siegel wurden entsprechend aufgelöst und die Holding-IDs entfernt
