### ISSUE TITLE
Anzeige der Lebensdaten mit c

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#197]
Bei den Personen, wo ein "c" (circa) in den Lebensdaten steht, z.B.
https://opac.rism.info/search?id=00000990033214&View=rism
 
![image](https://user-images.githubusercontent.com/18663291/62519737-7b681000-b82c-11e9-95a8-51028e356609.png)

fällt das "c" weg in der Vollanzeige der Normdatei:
![image](https://user-images.githubusercontent.com/18663291/62519794-963a8480-b82c-11e9-820a-98c825100316.png)

Aus meiner Sicht soll es einheitlich sein, also 1600c in beiden Anzeigen. 
@alexandermarxen : Was meinst du?

Siehe auch #6

**Comment by alexandermarxen** [comment]
Ja, bitte unbedingt die Angaben aus 100$d immer unverändert übernehmen!
