### ISSUE TITLE
Term "Werk" in den Facets

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#198]
In den Facets steht prominent der Filter "Collection/Werk":

![image](https://user-images.githubusercontent.com/6461776/62521867-c97f1280-b830-11e9-8b7f-becbb6e3f6f3.png)

 Hier sind wohl die gruppierten Templates "Sammlung" bzw. "Individualeintrag" gemeint
"Werk" ist hier der falsche Begriff, bitte zu "Individualeintrag" ändern.

**Comment by jenniferward** [comment]
Auf EN wäre das:
Collection main entries/Individual entries


Aber ehrlich gesagt frage ich mich, ob diese Unterscheidung überhaupt etwas bringt für die Nutzer?  Was meinen die anderen?

Das Wort "Collection" hat auf EN mehrere Bedeutungen (Sammlung, Sammelband, Sammeldruck, Sammelhandschrift, Bestand, Archiv, Konvolut, Nachlass), und die Benutzung von Collections in RISM-Sprache ist auch manchmal gegen allgemeine Erwartungen. Ich würde es lieber vermeiden.

Wenn es sein muss, schlage ich "Collection main entries" vor, um Missverständnisse zu vermeiden. Außerdem würde ich diesen Filter ganz unten stellen, nach Series, weil es eher strukturell ist und dient nicht zum Stöbern.

**Comment by jenniferward** [comment]
Sag niemals nie...
Ich habe einen Fall entdeckt, wo es tatsächlich hilfreich wäre, nur die "Collections" zu sehen. 

Beispiel: Suche nach PL-Kj und Signatur Mus.ant.pract. S 912, um die aneinandergebundenen Drucke zu finden. 65 Ergebnisse, eine Mischung aus Collectioneinträge und Einzeleinträge. Mit Knopfdruck auf "Collections" sieht man die 10 Drucke und kann die 55 Einzeleinträge ignorieren. Eigentlich ganz praktisch. 

Ein Problem ist, dass "Collection" hier nicht ganz richtig ist, weil ein Druck ja auch aus nur einem Werk bestehen kann. Aber ein besserer Begriff fällt mir nicht ein.

**Comment by BernLutz** [comment]
Wir ändern den Filter gerne in:
**Sammlung/Individualeintrag
Collection main entries/Individual entries**
Es wäre nur wichtig, hierfür auch die korrekte Ansetzung in den Sprachen (IT, FR, ES) zu erhalten.

Der Begriff „Collection“ ist allerdings in anderen Zusammenhängen explizit gefordert, z.B.: https://github.com/rism-international/opac-report/issues/210

**Comment by jenniferward** [comment]
Jetzt sehe ich, dass die Drucke vom Filter "Collection/Einzeleintrag" ausgeschlossen werden, wenn sie keine Einzeleinträge haben. (Beispiel: Suche nach: chopin funeral). Dann bin ich mit "**Collection main entry/Individual entry**" zufrieden.

Ich kümmere mich um ES.

(Habe es gerade in Einzahl geändert.)

**Comment by jenniferward** [comment]
Vielleicht als Überschrift
Collection/Individual entry
![image](https://user-images.githubusercontent.com/18663291/62861291-431c7200-bd03-11e9-88bd-90d0910fd188.png)

Dann
Individual entry
Collection main entry

**Comment by jenniferward** [comment]
ES: 
Registro primario
Registro secundario

**Comment by BernLutz** [comment]
Danke!

**Comment by BernLutz** [comment]
Die Überschrift für ES ist dann "Registro primario/Registro secundario" oder nur "Registro"? Wir bräuchten auch noch die entsprechenden Titel für IT und FR. Danke!

**Comment by MFalletta** [comment]
FR:
Recueil
Entrée individuelle

IT: 
Collezione
Singolo elemento

**Comment by jenniferward** [comment]
ES: "Registro primario/secundario"

**Comment by MFalletta** [comment]
Welche Idee steht eigentlich dahinter? Geht es darum, Einzeleinträge auszuschliessen? Dann würde sich doch eine einzige Zeile "Einzeleinträge verbergen" anbieten.
Außerdem steht dieser Filter zu weit oben in der Liste (s. Anmerkung oben von Jennifer)

**Comment by jenniferward** [comment]
EN: Hide individual entries

Dann könnte man den problematischen Begriff "Collections" vermeiden (z.B. 1001040048 ist keine Collection, wird aber beibehalten, wenn man im Filter auf "Collection" klickt.)

**Comment by BernLutz** [comment]
Die Idee ist meines Wissens mit der Einführung der neuen Kategorie "Konvolute" entstanden - mit einem Filter "Konvolute - Collection - Werk". Darum auch der Einstieg in dieser Form. Die Konvolute sind in den Daten noch nicht als solche ausgezeichnet, darum kann die Kategorie in den Facetten auch noch nicht angeboten werden. 
Wir können den Filter gerne nach unten (z.B. vor die Normdaten) verschieben. Wenn das Konstrukt  generell nicht gewünscht wird, entfernen wir den Filter.

**Comment by MFalletta** [comment]
Ich finde den Filter problematisch, auch weil die Konvolute noch nicht aufgereift sind. Zum jetzigen Zeitpunkt sollten wir auf den Filter verzichten.
Eine Anregung noch für die zukünftige Einführung des Filters: m. E. passt er sehr gut in die Erweiterte Suche.

**Comment by BernLutz** [comment]
Der Filter wurde entfernt.
