### ISSUE TITLE
Unterschiedlicher Stand der Anzeige von Holdings im Testreleases

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#199]
Kann es sein, dass die Anzeige der Holdings bei verschiedenen Drucken unterschiedlich ausfällt?

so etwa bei 00000990047070, Stand 2019-08-06:

![image](https://user-images.githubusercontent.com/6461776/62523529-3fd14400-b834-11e9-926e-6151a429e9ef.png)

im Gegensatz zu 
![image](https://user-images.githubusercontent.com/6461776/62524232-896e5e80-b835-11e9-9e0d-497f938b88f7.png)

**Comment by jenniferward** [comment]
Da stimmt etwas nicht; bei 00000990047070 wird "RISM A/I " ganz rechts angezeigt: 
![image](https://user-images.githubusercontent.com/18663291/62636932-bf493b00-b93a-11e9-86b1-fdd2266080a5.png)

**Comment by jenniferward** [comment]
Ein weiteres Beispiel:
https://rismtest.bsb-muenchen.de/search?id=1001034803&View=rism
![image](https://user-images.githubusercontent.com/18663291/62638645-2c120480-b93e-11e9-8d78-5d444cb50cc1.png)

Vgl. mit der Abbildung von GB-Lbl in #214 (in Rahmen)

**Comment by BernLutz** [comment]
In der Produktion ist die Anzeige der Holdings einheitlich.
