### ISSUE TITLE
Schlagworte - andere Strategie notwendig

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#20]
Es sollten nicht Schlagworte erscheinen, die nicht sprachbezogen umgesetzt sind. Siehe #4 
Die BSB nimmt gelieferte Schlagworte, setzt sie zu einem Ausdruck um, der die Linkfunktion auslöst, und lässt diese Begriffe über eine Übersetzungsliste laufen, in der neue Schlagworte erst mal nicht vorkommen. Diese müssen von der BSB zuerst in die Übersetzungsliste exportiert werden, und die Liste wird dann von Hand ergänzt. Frühestens beim nächsten Datenupdate sind die Schlagworte dann korrekt. 
Vorschlag: die Schlagworte sollten in Muscat 5 (oder mehr-)sprachig gepflegt werden und mit alle Übersetzungen an die BSB geliefert werden. Der OPAC würde dann gleich auf die von uns gelieferten Schlagworte in der jeweiligen Sprache zurückgreifen können.

**Comment by jenniferward** [comment]
Schlagworte werden im Moment nicht von unseren Übersetzern übersetzt. Wir bleiben bei EN/DE.
