### ISSUE TITLE
Personen (700) fehlen in Werkinformation

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#200]
Personen (700) wie Widmungsträger stehen unter "Weitere Angaben und Bemerkungen". Lt. Testliste sind sie in "Werkinformation" vorgesehen.
Beispiel:  990055558
![990055558 Widmungsträger vom 2019-08-06 11-13-14](https://user-images.githubusercontent.com/18736235/62527880-406dd880-b83c-11e9-8219-87caa4fa8d08.png)

**Comment by MFalletta** [comment]
Weiteres Beispiel: 1001034803 (Teileintrag)
Textverfasser fehlt!
![1001034803 aktuell vom 2019-08-07 11-52-33](https://user-images.githubusercontent.com/18736235/62613601-11be3380-b90a-11e9-8b02-4bb547d48039.png)
vergleiche mit 
![1001034803 Teileintrag vom 2019-08-07 11-45-30](https://user-images.githubusercontent.com/18736235/62613621-197dd800-b90a-11e9-8601-9b2a6643fcb2.png)

**Comment by MFalletta** [comment]
Die Komponistenquerverweise sind ebenfalls in die "Weiteren Angaben und Bemerkungen" verrutscht.  Gehören aber in die "Werkinformation".
Beispiel 993121419
https://rismtest.bsb-muenchen.de/search?id=993121419&View=rism

**Comment by BernLutz** [comment]
Die genannten Personen aus 700 sind nun an der richtigen Stelle in den Werkinformationen.
