### ISSUE TITLE
Stimmenmaterial 590$a, $b fehlt bei Material in Quellenbeschreibung

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#201]
Beispiel: 990055558
4 parts - vl 1, vl 2, vla, vlc
![990055558 Stimmenmaterial vom 2019-08-06 11-28-07](https://user-images.githubusercontent.com/18736235/62528651-7bbcd700-b83d-11e9-9d10-167e438a0d54.png)

**Comment by jenniferward** [comment]
Sieht heute anders aus
![image](https://user-images.githubusercontent.com/18663291/62641231-7ba6ff00-b943-11e9-91f2-3a3ce8bec2ba.png)

**Comment by BernLutz** [comment]
Das Stimmenmaterialist ist nun im Material nachgewiesen.
