### ISSUE TITLE
Plattennummer steht bei den Verlagsangaben

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#202]
gehört eigentlich zum Material, s. Beispiel 1001040384

Muscat:
![image](https://user-images.githubusercontent.com/6461776/62529270-9f345180-b83e-11e9-962c-423696f7ecc3.png)

Testrelease:
![image](https://user-images.githubusercontent.com/6461776/62529323-ba06c600-b83e-11e9-86fc-d089d4ca784f.png)

**Comment by jenniferward** [comment]
Ist jetzt ok?
![image](https://user-images.githubusercontent.com/18663291/62641129-384c9080-b943-11e9-9f1c-3405a62eb812.png)

**Comment by BernLutz** [comment]
Die Plattennummer ist in den Anforderungen an die Drucke  dem Bereich "Verlagsangaben" zugeordnet.
Wollen Sie den Punkt noch einmal klären?

**Comment by MFalletta** [comment]
Ich glaube hier liegt ein Missverständnis vor. 
Die Angaben aus dem Block "Materialbeschreibung" in Muscat werden ja bei den Drucken zu den "Verlagsangaben" im OPAC.
Die Anforderungen bleiben wir gehabt.
