### ISSUE TITLE
Bemerkungen 500 $a doppelt

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#203]
Die Bemerkungen 500$a stehen sowohl bei den "Verlagsangaben" als auch bei "Weitere Angaben und Bemerkungen"
Gehören nur zu "Weitere Angaben und Bemerkungen"
Beispiel: 990055558
![990055558 Bemerkungen vom 2019-08-06 11-41-23](https://user-images.githubusercontent.com/18736235/62529810-a6a82a80-b83f-11e9-95d1-5cbbb1892446.png)

**Comment by jenniferward** [comment]
Scheint jetzt OK zu sein??
https://rismtest.bsb-muenchen.de/search?id=00000990055558&View=rism
![image](https://user-images.githubusercontent.com/18663291/62640757-9331b800-b942-11e9-9413-916f23f03b2a.png)

Aber eigentlich gehören 2 Bemerkungen zum Exemplar. Siehe #220

**Comment by jenniferward** [comment]
@MFalletta Scheint ok zu sein? https://opac.rism.info/search?id=990055558&View=rism

**Comment by BernLutz** [comment]
Erledigt!
