### ISSUE TITLE
Bemerkung 500$a aus Exemplar 

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#204]
Bemerkungen 500 $a werden sowohl zum Exemplar gehörig gezeigt als auch in "weitere Angaben" bzw. "Verlagsangaben"
Beispiel 990055558
![990055558 Bemerkungen vom 2019-08-06 11-41-23](https://user-images.githubusercontent.com/18736235/62530912-b0cb2880-b841-11e9-8c48-2334428bc726.png)
und 
![990055558 Bemerkung Exemplar 328945 vom 2019-08-06 11-52-00](https://user-images.githubusercontent.com/18736235/62530929-bcb6ea80-b841-11e9-9754-c41b01ff7f07.png)

**Comment by MFalletta** [comment]
siehe auch #203

**Comment by BernLutz** [comment]
Die exemplarspezifischen Bemerkungen werden nun nur noch im Exemplar angezeigt.
