### ISSUE TITLE
597 Kolophon

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#206]
Angaben vorhanden, aber bitte Beschriftung "Impressum:" in "Kolophon:" ändern.
Beispiel: 990008027
![990008027 Kolophon vom 2019-08-06 12-24-12](https://user-images.githubusercontent.com/18736235/62535496-d9f0b680-b84b-11e9-8f3d-7ed32dbe427e.png)

**Comment by jenniferward** [comment]
Auf EN auch: Colophon
