### ISSUE TITLE
Umsetzung von sprachbezogenen Begriffen funktioniert nicht

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#21]
Manche Begriffe sollen je nach Spracheinstellung übersetzt angegeben werden. Die Übersetzungsliste ist von der ZR und Ländergruppen vollständig bearbeitet worden. Trotzdem finden sich noch Platzhalter wie:  
???de.rism.manuskriptstatement.Print with autograph annotations???: 
in: https://opac.rism.info/search?id=1001036994&View=rism
statt dessen müsste stehen: Deutsch "Druck mit autographen Anmerkungen" oder Englisch: "Print with autograph annotations"
Siehe auch #4

**Comment by BernLutz** [comment]
Soll über Thesaurus gelöst werden.

**Comment by BernLutz** [comment]
Könnten Sie die Daten entsprechend anpassen @HirschSt  ?
