### ISSUE TITLE
Anzeige der Komponistenansetzung bei Collection

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#210]
Bei collections wird nun kein Komponist mehr angezeigt, sondern lediglich der Titel - wahrscheinlich weil 100 bei diesen Titeln leer ist.

Beispiel https://rismtest.bsb-muenchen.de/search?id=220039923&View=rism
![image](https://user-images.githubusercontent.com/6461776/62602827-eb41cd80-b8f4-11e9-8935-b8507c417320.png)

Bitte zur Ansetzung in der Anzeige wie bisher "Collection" anzeigen:

![image](https://user-images.githubusercontent.com/6461776/62603011-4c69a100-b8f5-11e9-8b2b-a0206ce08288.png)

**Comment by MFalletta** [comment]
Außerdem rutscht dadurch der Besetzungshinweis 240$m nach oben.
Sieht bei 993121263 verwirrend aus.

![993121263 Kein Autor vom 2019-08-07 14-40-19](https://user-images.githubusercontent.com/18736235/62623795-fa8b4000-b921-11e9-9ab6-9dc0837b129e.png)

**Comment by jenniferward** [comment]
Ist jetzt ok?!
![image](https://user-images.githubusercontent.com/18663291/62639591-1f8eab80-b940-11e9-859a-caecd03b5c19.png)

![image](https://user-images.githubusercontent.com/18663291/62639615-2e755e00-b940-11e9-8899-e10f633e2087.png)

**Comment by HirschSt** [comment]
@jenniferward hast du wirklich im aktuellen Testrelease geprüft? Bei mir ist es nach wie vor falsch.

**Comment by BernLutz** [comment]
Erledigt!
