### ISSUE TITLE
Fehlende Verbalisierung im Facet "Materialtyp"

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#212]
Nach Suche von Bach, Lokalisierung deutsch

Im Testrelease:
![image](https://user-images.githubusercontent.com/6461776/62604320-1974dc80-b8f8-11e9-9425-b51036ab8a1a.png)

Im Produktionssystem
![image](https://user-images.githubusercontent.com/6461776/62604356-30b3ca00-b8f8-11e9-954e-1e0c18d3148b.png)

**Comment by jenniferward** [comment]
Selbe Suche in EN ist auch problematisch

Im Testrelease: 
![image](https://user-images.githubusercontent.com/18663291/62718034-567ac500-ba05-11e9-9133-7bf180cc8b6f.png)

Im Produktionssystem (auch nicht schön)
![image](https://user-images.githubusercontent.com/18663291/62718069-714d3980-ba05-11e9-9257-bd1b6e5af9e7.png)

**Comment by BernLutz** [comment]
Ich habe für die Übersetzungen des Materialtyps ein zweites Tabellenblatt angelegt:
https://docs.google.com/spreadsheets/d/1fOFV5R57fJU8IDMfNA5EQkSowuIQc5CkwL73tDKxofk/edit#gid=1415147376
Um die Kategorien korrekt anzeigen zu können, benötigen wir noch die Bezeichnungen in den fünf relevanten Sprachen. Soweit die Übersetzungen vorliegen, sind diese bereits im Dokument erfasst.

**Comment by BernLutz** [comment]
Hat sich erledigt, wir haben die Bezeichnungen.

**Comment by KlausKeil** [comment]
@BernLutz  Lieber Herr Lutz, wie ich sehe ist dieses Problem noch nicht gelöst. Die von Ihnen angezeigte Tabelle ist nach MARC Feldern ausgerichtet. Wir müssen aber verschiedene Begriffe in einem Marcfeld umsetzen. Im Feld 593 sind das: 

    • manuscript_copy 
    • autograph_manuscript
    • possible_autograph_m…
    • partial_autograph
    • print_with_nonautogr…
    • manuscript_copy_with…
    • print_with_autograph… 
    • libretto,_handwritten 
    • treatise,_handwritten
    • treatise,_printed 
,
Erstaunlicherweise sind einige Begriffe richtig umgesetzt: 
    • Print 
    • Autograph 
    • other
    • Fragliches Autograph
In der von Ihnen verlinkten Liste ist das Feld 593 gar nicht vorhanden. Es muss also noch eine andere Liste geben, mit der die Umsetzungen der 4 Begriffe gemacht werden. 
Bei den Schlagworten (650) ist es ähnlich. Das Feld kommt in Ihrer Liste nicht vor.

**Comment by BernLutz** [comment]
Lieber @KlausKeil 
die Liste befindet sich im zweiten Tabellenblatt. 
![grafik](https://user-images.githubusercontent.com/44613113/83498950-df934900-a4bc-11ea-9c27-f99eb6f17b7f.png)
Sobald uns die fehlenden Übersetzungen vorliegen, können wir die Verbalisierungen in den OPAC übernehmen.

Die bereits richtig umgesetzten Begriffe stammen aus den CH-Daten. Diese Ansetzungen führen übrigens dazu, dass derzeit einige Materialtypen in zwei Filtervarianten erscheinen, z.B. "autograph_manuscript"  und "Autograph".
![grafik](https://user-images.githubusercontent.com/44613113/83499722-10c04900-a4be-11ea-9cc6-52ca4a8ea84b.png)

Es wäre gut, wenn dies in den Daten vereinheitlicht werden könnte. Wäre das möglich @HirschSt ?

**Comment by MFalletta** [comment]
Die Liste im zweiten Tabellenblatt ist vollständig.

**Comment by BernLutz** [comment]
Die Materialtypen sind angepasst.
