### ISSUE TITLE
Filter "Besetzung" wird mit weiteren Feldern gefüllt

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#213]
wie #26 
Es scheint, dass der Besetzungsfilter wieder Angaben aus anderen Marcfeldern enthält, und nicht nur aus 240

Beispiel Suche nach "Bach":

Testrelease:
![image](https://user-images.githubusercontent.com/6461776/62604734-f565cb00-b8f8-11e9-80cd-46b37d720db9.png)

Produktionssystem:
![image](https://user-images.githubusercontent.com/6461776/62604769-06aed780-b8f9-11e9-9549-28b4ac8f1bd9.png)

**Comment by alexandermarxen** [comment]
Scheinbar stehen in der aktuellen Version nun nur Angaben aus dem Feld "Incipits - Besetzung (031)", das Feld 240 wird offensichtlich nicht berücksichtigt.

**Comment by BernLutz** [comment]
Der Filter wurde entsprechend den Anforderungen aus der E-Mail vom 5.9.2019 von @KlausKeil umgesetzt:
"Er [der Filter] sollte sich speisen aus dem Besetzungshinweis (240 $m) und der Besetzung (594): aber gerade*nicht *aus dem Musikincipit (031 $m)"
