### ISSUE TITLE
Übergeordeter Eintrag 773 hat unterschiedliche Bezeichnungen

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#214]

**Comment by MFalletta** [comment]
Bei Handschriften steht "In Sammelwerk"
![Übergeordneter Eintrag Ms  vom 2019-08-07 12-47-19](https://user-images.githubusercontent.com/18736235/62617532-5ea60800-b912-11e9-832f-83af1ff6c4bf.png)


bei Teileinträgen zu Musikdrucken "Übergeordnete Reihe"
![1001034803 Teileintrag vom 2019-08-07 11-45-30](https://user-images.githubusercontent.com/18736235/62617559-7087ab00-b912-11e9-9676-fac15dee2332.png)

Soll einheitlich wieder "In Collection" lauten. Oder?

**Comment by jenniferward** [comment]
Auf EN wäre eine einheitliche Lösung ok. "In collection"

Bei den Drucken ist "In collection print" auf jeden Fall unidiomatisch
![image](https://user-images.githubusercontent.com/18663291/62718388-0819f600-ba06-11e9-98c7-cd0bb8d5326c.png)
Besser ist: In printed collection

**Comment by BernLutz** [comment]
Die Vorgabe aus dem Drucke-Template für 773$w war: >Achtung die Ausschrift ist bis jetzt nur in Englisch " In Collection". Müsste bei Handschriften "In Sammelwerk" heißen und bei Drucken "Übergeordnete Reihe"<
Falls es hier Änderungen im Konzept gegeben hat, bräuchten wir die aktualisierten Begriffe - idealerweise gleich in DE, EN, FR, IT, ES. Vielen Dank!

**Comment by jenniferward** [comment]
ES ist schon in Ordnung!

**Comment by MFalletta** [comment]
FR und IT sind auch in Ordnung!
Für DE bitte einheitlich "In Sammelwerk" verwenden

**Comment by BernLutz** [comment]
Erledigt
