### ISSUE TITLE
Schreiber in den Bemerkungen statt Material

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#215]
Schreiber sind Materialbezogen und sollten entsprechend beim Material auftauchen.

Beispiel https://rismtest.bsb-muenchen.de/search?id=989003585&View=rism

**Testrelease:**
![image](https://user-images.githubusercontent.com/6461776/62622124-e9403480-b91d-11e9-83dc-982108d470f6.png)

**Produktionssystem:**

![image](https://user-images.githubusercontent.com/6461776/62622204-1260c500-b91e-11e9-8c5e-9cad374ec59f.png)

**Comment by jenniferward** [comment]
Scheint heute OK zu sein?
![image](https://user-images.githubusercontent.com/18663291/62638107-09cbb700-b93d-11e9-9972-bb9d1593b639.png)

**Comment by BernLutz** [comment]
Die Schreiber sind nun wieder im Material nachgewiesen.
