### ISSUE TITLE
Auflistung der Serien

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#216]
Wenn man nach * sucht, sind die RISM-Serien (Filter) anders aufgeteilt als im Produktivsystem:

Test:
![image](https://user-images.githubusercontent.com/18663291/62636424-d3406d00-b939-11e9-9ad1-779f43c5c15a.png)

RISM A/I (97319)
RISM B/I (14998)
B/I (737)
A/I (673)
B/VI (13)
A/II (5)
510a:RISM Series_Series (2)
B/II (2)
Authority dataAuthority data

Im Gegesantz zum Produktivsystem:
![image](https://user-images.githubusercontent.com/18663291/62636409-cae83200-b939-11e9-9473-0f4c1172ed7e.png)

**Comment by BernLutz** [comment]
Der Filter wird auf Wunsch von @KlausKeil entfernt.
