### ISSUE TITLE
Vorsatz Digitalisate

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#22]
Digitalisate erhalten einen neuen Vorsatz in 856$z (“[digitized version] statt “Digitalisat”).
Beispiel: https://opac.rism.info/search?id=1001045228&View=rism
Der geforderte Vorsatz ist nicht vorhanden. Statt dessen "Externe Links" oder englisch "External Links". 
Zu Diskutieren: Was wollen wir? 
Der Text unter code="z" ist entfallen. 

<datafield tag="856" ind1=" " ind2=" ">
<subfield code="u">
https://findingaids.library.dal.ca/music-score-library
</subfield>
<subfield code="z">
Digital copy available via Dalhousie University Archives catalogue.
</subfield>
<subfield code="8">1\c</subfield>

**Comment by jenniferward** [comment]
Der Text unter $z soll auf jeden Fall angezeigt werden; die Mitarbeiter gehen davon aus, dass das der Fall ist.

**Comment by HirschSt** [comment]
Digitalisate werden in Muscat 5 unter 856$x in der Auswahlliste als "Digitized music" ausgezeichnet. 856$z ist ein Freitextfeld, ein entprechender Vorsatz muss eigentlich dann nicht mehr eingetragen werden. Ziel wäre, dass der Bemerkungstext 856$z auf 856$u verlinkt, also etwa bei 856$x "digitalisat":

- Digitalisat: [Digital copy available via Dalhousie University Archives catalogue](https://findingaids.library.dal.ca/music-score-library)

bei 856$x "other"

- Externe Links: [Wasserzeichen XYZ](https://upload.wikimedia.org/wikipedia/commons/f/fb/Pro-Patria-Wasserzeichen.jpg)

**Comment by BernLutz** [comment]
Eine Anpassung der Anzeige der Digitalisate über den Online lesen-Button ist für die kommende FID-Phase 2020 als eigener Punkt beantragt.
