### ISSUE TITLE
 Online Lesen aber kein Link

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#23]
Viele Titel haben ein Online Lesen aber kein Link. 
Z.B. https://opac.rism.info/search?id=553013057&View=rism

**Comment by jenniferward** [comment]
Wenn nur 1x das Feld 856 ausgefühlt ist (d.h. wenn es nur einen Link gibt) wird grundsätzlich der Link an sich nicht angezeigt sondern er rutscht nach oben unter "Online lesen". 

Meiner Meinung nach ist das keine schöne Lösung. Das ist vor allen Dingen bei den Drucken verwirrend. Man kann den Link nicht einordnen, z.B.
https://opac.rism.info/search?id=00000990029860&View=rism
Von welcher Bibliothek ist der Link?!

**Comment by jenniferward** [comment]
Siehe #53
