### ISSUE TITLE
Binding note 563 gehört zum Material

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#231]
Beispiel https://rismtest.bsb-muenchen.de/search?id=290002896&View=rism

Testrelease:
![image](https://user-images.githubusercontent.com/6461776/62697932-2a971980-b9dc-11e9-9c59-49d3b5b15905.png)

Muscat:
![image](https://user-images.githubusercontent.com/6461776/62698000-57e3c780-b9dc-11e9-8dc8-0b9043155e11.png)

**Comment by BernLutz** [comment]
563 wird nun im Material angezeigt.
