### ISSUE TITLE
Anzeige von Exemplaren bei Titeln ohne Holdings

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#234]
Beispiel: https://rismtest.bsb-muenchen.de/search?id=702011950&View=rism

![image](https://user-images.githubusercontent.com/6461776/62706379-b1092680-b9ef-11e9-9432-ee2c29d2fcd1.png)

Es ist unklar, woher dieser Exemplareintrag stammt. Exemplare sollten nur angezeigt werden, wenn eine Holding-Id in 852$3 vorliegt, z.B.

```xml
<marc:datafield tag="852" ind1="1" ind2="0">
  <marc:subfield code="a">N-Onm</marc:subfield>
  <marc:subfield code="e">Nasjonalbiblioteket, Seksjon for Musikk</marc:subfield>
  <marc:subfield code="x">rauthors@@@ks30076022</marc:subfield>
  <marc:subfield code="3">287440</marc:subfield>
</marc:datafield>
```

**Comment by MFalletta** [comment]
Im Falle von RISM ID no. 603001643 mit handschriftlichem und gedrucktem Material werden alle Materialangaben im "Exemplar" zusammengefasst. Eine Unterscheidung der Angaben zu den Materialien ist nicht erkennbar.
![gemischtes Material vom 2019-08-09 13-16-46](https://user-images.githubusercontent.com/18736235/62775512-27695f80-baa8-11e9-89aa-68cc7d033639.png)

**Comment by jenniferward** [comment]
In 603001643 werden folgenden Angaben getrennt angezeigt:
Institution: Tranquillo Mollo
Attribution qualifier: Verified
Funktionsbezeichnung: pbl

Vorschlag:
Publisher: Tranquillo Mollo (Verified)

Ansicht im Produktivsystem:
![image](https://user-images.githubusercontent.com/18663291/62777474-f4c26580-baad-11e9-81b6-43b9845eb155.png)

**Comment by jenniferward** [comment]
Jetzt bei https://opac.rism.info/search?id=603001643&View=rism ist der Fundort (Sigel, Signatur) komplett weg.

![image](https://user-images.githubusercontent.com/18663291/64531430-ca173700-d30f-11e9-9154-5382af097ba2.png)

852 wurde nicht veröffentlicht.

**Comment by BernLutz** [comment]
Die Punkte sollten im Produktionssystem nun korrekt dargestellt werden.
