### ISSUE TITLE
Icons für Musikdrucke sind verschwunden

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#235]
Zur Unterscheidung waren Drucke bisher mit einem Buchsymbol und Handschriften mit einer Schriftrolle versehen. 
Das Buchsymbol ist verschwunden, in allen Einträgen ist jetzt die Schriftrolle zu finden.
Alte Version 
![Icon alt](https://user-images.githubusercontent.com/18736235/62709161-1dd2ef80-b9f5-11e9-9c63-8794751fc22e.JPG)

neu
![Icon vom 2019-08-06 10-53-20](https://user-images.githubusercontent.com/18736235/62709190-2b887500-b9f5-11e9-921d-0b236d3bac23.png)

**Comment by BernLutz** [comment]
Soll für die Anzeige der Icons - analog zur Steuerung des Templates vgl. #263  - auch der Leader ausgewertet werden @MFalletta @HirschSt ?

- Handschrift: ndc, ndd, ndm, ntm, npm
- Druck: ncc, ncd, nam

Die Frage hat sich ergeben, da z.B. bei faksimilierten Manuskripten, Repros etc. das Handschriften-Template bei gleichzeitiger Verwendung des Materialtyps „Druck“ genutzt werden kann:
Beispiel: 
https://opac.rism.info/search?View=rism&id=1001080818

**Comment by BernLutz** [comment]
Die Zuordnung der Icons für Drucke und Handschriften wird nun über den Leader gesteuert, vgl. #263.
