### ISSUE TITLE
Anzeige Bibliotheken und Signaturen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#241]
Im aktuellen OPAC heißt es ja
![image](https://user-images.githubusercontent.com/18663291/62776023-b460e880-baa9-11e9-874a-ad3886aeed2c.png)

Im Testsystem steht nur:
Exemplare

Ist es allen Nutzern klar, was die Nummern bedeuten?
Bsp: 00000990045842
![image](https://user-images.githubusercontent.com/18663291/62776067-d0648a00-baa9-11e9-850f-4bf4796fedf0.png)

Wäre es vielleicht deutlicher, nur den vollen Namen (mit Sigel) anzugeben, und die Signatur (EN Shelfmark) im Kästchen anzubieten?

**Comment by MFalletta** [comment]
Die vollständigen Institutionsnamen mit Signatur und SIgel (im aufgeklappten Kästchen) sind da, aber der Ort fehlt noch. Eine "Universitäts- und Landesbibliothek" gibt es in vielen Städten.

![990045842 vom 2019-09-04 14-33-07](https://user-images.githubusercontent.com/18736235/64255351-7b3d5c00-cf21-11e9-849c-44c1f11154a2.png)

**Comment by jenniferward** [comment]
...und Länder! :-) Die Liste ist alphabetisch nach Land, aber ich weiß nicht, ob das für alle Nutzer selbstverständlich ist. Bei einem Druck mit 60 Exemplaren, wie kann ich z.B. Italien schnell finden?

**Comment by jenniferward** [comment]
Die kompletten Sigelbezeichnungen (z.B. D-Dl oder D-B) müssen nach dem Institutionsnamen angehängt werden, wie im alten OPAC.

Beispiel:
![image](https://user-images.githubusercontent.com/18663291/64528604-32aee580-d309-11e9-8af8-6b56feccf9a6.png)

Coburg, Landesbibliothek (D-Cl)

**Comment by BernLutz** [comment]
Wurde umgesetzt.
