### ISSUE TITLE
"Angaben über Unvollständigkeiten" auf EN

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#242]
"Angaben über Unvollständigkeiten" ist noch auf DE.
Beispiel 00000990045842, Bibliothek CZ-Pk
 Auf EN bitte ändern in:
Material held

**Comment by BernLutz** [comment]
Die "Angaben über Unvollständigkeiten" werden offenbar in 852$q geliefert. Da das subfield nicht im Muscat-Marc-Schema gelistet ist, haben wir es auch nicht für das Mapping berücksichtigt.
 Ich bin auch bei der DE-Version nicht sicher, ob das Label "Angaben über Unvollständigkeiten" unbedingt so treffend ist. Vielleicht könnten Sie sich das noch einmal ansehen @MFalletta @jenniferward @HirschSt ? Wichtig wäre in jedem Fall die Information, wie die Bezeichnung auf FR,IT und ES lauten soll. Vielen Dank!

**Comment by MFalletta** [comment]
852 $q 
heißt in DE einheitlich "Erhaltenes Material". Bitte so übernehmen.

IT:  Materiale conservato
FR: Matériaux préservées

**Comment by BernLutz** [comment]
Das hört sich besser an, vielen Dank!

**Comment by jenniferward** [comment]
ES: Material existente

**Comment by jenniferward** [comment]
EN ist in Ordnung.

Für ES sehe ich die IT-Bezeichnung (?) statt "Material existente"?
