### ISSUE TITLE
657$a Liturgische Feste gehört zur Werkinformation																						

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/opac-report#243]
Siehe den laufenden RISM OPAC: 

![image](https://user-images.githubusercontent.com/26874482/62776639-75cc2d80-baab-11e9-81bd-5698b0292af4.png)

**Comment by BernLutz** [comment]
Gerne, in dem Drucke-Template ist das Feld allerdings explizit für die Rubrik "Weitere Angaben und Bemerkungen" vorgesehen. Ich würde allerdings auch für eine Zuordnung zu den "Werkinformationen" plädieren.

**Comment by MFalletta** [comment]
Prima, dann bitte "Werkinformation"!
