### ISSUE TITLE
Angaben zu Exemplaren noch auf DE und verwirrend

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#244]
Siehe 00000990045842
![image](https://user-images.githubusercontent.com/18663291/62776605-546b4180-baab-11e9-884c-7fbf5d95abfd.png)

Die Begriffe sind noch auf DE. EN wäre:
Person
Life dates
Function
Attribution

Aber warum nicht alles in einer Zeile anzeigen? Diese Granularität braucht man für eine einzige Person nicht. Zum Beispiel: 
Previous owner: Brem, Aurel, 1826-1890 (Conjectural)

**Comment by jenniferward** [comment]
Verlinkung mit Personennormdatei fehlt wohl. #269

**Comment by BernLutz** [comment]
Erledigt!
