### ISSUE TITLE
"Personen Rolle" bitte auflösen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#246]
Die Funktionen der Personen müssen aufgelöst werden
Beispiel 00000990045842
![image](https://user-images.githubusercontent.com/18663291/62777045-9a74d500-baac-11e9-945e-244619d76a26.png)

Siehe Vorschlag in #244 
Previous owner: Grimm, Julius Otto, 1827-1903 (Ascertained)

**Comment by jenniferward** [comment]
(hat vielleicht mit LD-Browser zu tun)

**Comment by jenniferward** [comment]
Bei den Institutionen auch:

1001042604
![image](https://user-images.githubusercontent.com/18663291/62782589-df076d00-baba-11e9-9825-b5d4ecce99e7.png)
Depositor: Fürsten- und Landesschule

**Comment by jenniferward** [comment]
Und manchmal unformatiert:
00000990046456
![image](https://user-images.githubusercontent.com/18663291/62787286-ad939f00-bac4-11e9-8ebe-bda4ec7a5b28.png)

![image](https://user-images.githubusercontent.com/18663291/62787351-d156e500-bac4-11e9-94de-bf34662b2520.png)

**Comment by BernLutz** [comment]
Die Anzeige der Personen und Institutionen in den Exemplaren ist nun angepasst. Durch die Zusammensetzung der Einzelfelder entsteht nun in einigen Fällen eine Leerzeile unter der Person, die leider nicht ohne Weiteres entfernt werden kann. Wir versuchen aber auch dafür eine Lösung zu finden.
![grafik](https://user-images.githubusercontent.com/44613113/65307335-d90bae00-db87-11e9-80a8-817b577f1d23.png)
