### ISSUE TITLE
Abschnitt "Copy or imprint"

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#247]
Ich verstehe nicht, warum es den neuen Abschnitt "Copy or imprint" gibt:
Beispiel 570010087
![image](https://user-images.githubusercontent.com/18663291/62777188-06573d80-baad-11e9-8101-a75ffad4de95.png)

Gibt es im Produktivsystem nicht:
![image](https://user-images.githubusercontent.com/18663291/62777236-2edf3780-baad-11e9-8f2c-c9f0f0b444fa.png)

Außerdem wird das Datum 2x angezeigt.
Der Begriff "Copy" ist hier sehr problematisch. Ich würde einen neuen vorschlagen, aber erst muss ich wissen, wozu dieser Abschnitt dient.

**Comment by jenniferward** [comment]
Taucht das nur bei den Handschriften auf?
Weitere Beispiele:
452010781
230018506
650008648
450028838

**Comment by jenniferward** [comment]
siehe auch #257

**Comment by BernLutz** [comment]
Der Bereich "Abschrift oder Impressum" ist bislang das Pendent der "Handschriften" zu den "Verlagsangaben" der "Drucke". Wir haben uns hier an Muscat orientiert. Angezeigt wird der Ort (260$a, Schreiber (260$b) und Jahr (260$c). Soll dies so bleiben?

Wenn ja und Sie uns neue Bezeichnungen (DE/EN/IT/FR/ES) für den Abschnitt geben, benennen wir den Block gerne um.

**Comment by jenniferward** [comment]
Ich glaube, es kommt nur selten vor, dass bei einer Handschrift alle 3 Angaben Ort, Schreiber und Jahr (260 $a, b, c) angegeben wird. Meistens - glaube ich - hat man nur das Jahr, und das Jahr ist wie gesagt jetzt doppelt vorhanden. Einen eigenen Bereich ist, finde ich, zu viel.
Kann es nicht vielleicht Teil der Materialbeschreibung sein?
![image](https://user-images.githubusercontent.com/18663291/63109220-f6e26380-bf88-11e9-8292-e3c231198e56.png)
z.B. Manuscript: 1751-1800 (18.2d); Place: XYZ; Copyist: ABC; 27,8 x 22,5 cm  ??

Wenn wir den Bereich beibehalten, dann besser auf EN einfach "Production information."

**Comment by MFalletta** [comment]
Der Abschnitt ist nicht notwendig. 
Bitte den Vorschlag von Jennifer umsetzen und die Angaben in die Materialbeschreibung einfliessen lassen. 
Beispiel: wie oben: 1751-1800 (18.2d); Place: XYZ; Copyist: ABC; 27,8 x 22,5 cm
