### ISSUE TITLE
"Leere" Felder nicht anzeigen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#248]
Beispiel: Normdatei H-Gk
530011783
![image](https://user-images.githubusercontent.com/18663291/62777771-bf6a4780-baae-11e9-97f9-409379a91e40.png)
Wenn es keinen Alternativen Name gibt, soll das Feld nicht angezeigt werden.

**Comment by jenniferward** [comment]
Weiteres Beispiel
1001071746
"Name of printer" ist leer
![image](https://user-images.githubusercontent.com/18663291/62779729-51288380-bab4-11e9-98ab-9ac079c49f86.png)

**Comment by jenniferward** [comment]
1001065921
![image](https://user-images.githubusercontent.com/18663291/62787595-52ae7780-bac5-11e9-9bf6-d4f533d78c8a.png)

**Comment by BernLutz** [comment]
Die Felder werden angezeigt, da Leerzeichen mitgeliefert werden. Diese sollten in den Daten gelöscht werden, vgl. meine Mail @KlausKeil [3.90.2019, Linebreaks und isolierte Leerzeichen in den Daten]

**Comment by KlausKeil** [comment]
@HirschSt
