### ISSUE TITLE
260 in den Daten verdoppelt, im OPAC zusammen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#251]
Verlagsangaben werden manchmal verdoppelt, z.B.
![image](https://user-images.githubusercontent.com/18663291/62780239-897c9180-bab5-11e9-9ff1-db6057e25616.png)

Im Testsystem kommen die Angaben teilweise durcheinander. Siehe 00000990000888

![image](https://user-images.githubusercontent.com/18663291/62780199-6eaa1d00-bab5-11e9-9fca-bdc2fa2bffa2.png)

Wäre es möglich, zwei verschiedene Blöcke daraus zu machen? Oder sie irgendwie zu trennen?
In der Muscat-Anzeige sind die Felderbezeichnungen nicht vorhanden:
![image](https://user-images.githubusercontent.com/18663291/62780350-cea0c380-bab5-11e9-814c-509a965a9095.png)

**Comment by jenniferward** [comment]
Jetzt scheint das zweite 260 komplett weg zu sein, obwohl im MARC mitgeliefert.

https://opac.rism.info/search?id=990000888&View=rism

**Comment by BernLutz** [comment]
Das Datum aus 260$c wird jetzt (einmal) im Material angezeigt.
![grafik](https://user-images.githubusercontent.com/44613113/66567100-cf61de80-eb66-11e9-86f2-bc86011730d3.png)
Diese Anzeige entspricht auch der Feldbelegung von 260$c in Muscat:
![grafik](https://user-images.githubusercontent.com/44613113/66567276-210a6900-eb67-11e9-9d67-fae2a9dddaf2.png)
