### ISSUE TITLE
Exemplare "offen" oder "zu"

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#252]
Kann mir jemand bitte erklären, wie/warum bestimmte Exemplare "offen" oder "zu" sind, wenn ein Titel aufgerufen wird? 
Bespiel:
00000990049426
![image](https://user-images.githubusercontent.com/18663291/62781224-cb0e3c00-bab7-11e9-8bad-bbb6c4453b96.png)
Warum F-Pc zu aber US-R offen? Wird das im Produktivsystem so bleiben?

**Comment by BernLutz** [comment]
Die Default-Einstellung wird in der Produktion "geschlossen" sein.

**Comment by jenniferward** [comment]
Alles klar, danke!
