### ISSUE TITLE
Filter "Publisher" wird mit weiteren Feldern gefüllt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#255]
wie #213: Der Filter "Publisher" wird mit anderen MARC-Feldern gefüllt.
![image](https://user-images.githubusercontent.com/18663291/62786155-5391da00-bac2-11e9-8c76-067896427adf.png)

Das ist aus 260 $b und ist ein Freitextfeld (unkontrolliert) und gehört nicht in den Filtern! 
In Muscat:
![image](https://user-images.githubusercontent.com/18663291/62786749-88eaf780-bac3-11e9-8afb-6a97892b5eae.png)

Weitere Beispiele aus dem Testsystem: (Erweiterte Suche, Feld Publisher, Suche nach "chez")
Chez le Sieur FOUCAU… (136)
Simrock, Nicolaus (20)
B. Schott's Söhne (17)
chez N. Simrock (14)
Marco Berra (9)
Breitkopf & Härtel (7)
Johann André (7)
Rameau, Jean-Philippe (7)
chez les fils de B.… (7)
Boivin (5)
La Chevardière (5)
Leclair (5)
Boivin, Vve (4)
Chez les fils de B.… (4)
Friedrich Hofmeister (4)

Im Produktivsystem: 

    Chez le Sieur FOUCAU… (273)
    B. Schott's Söhne (18)
    Breitkopf & Härtel (8)
    A. Schott (7)
    Marco Berra (7)
    chez A. Schott (7)
    chez Breitkopf & Härtel (7)
    Chez B.Schott fils (6)
    Etienne Adolphe Cate… (6)
    Johann André (6)
    chez Ad.e Catelin &… (6)
    chez J. André (6)
    ex taberna musices B… (6)
    Le Sr Sieber Musicie… (4)

**Comment by BernLutz** [comment]
#213

**Comment by BernLutz** [comment]
Für den Filter "Verlag" werden nur noch Körperschaften aus 710$a berücksichtigt, deren subfield $4 mit "pbl" belegt ist.
