### ISSUE TITLE
Jahr in Konvolut-Einträgen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#257]
Beispiel
1001068757
![image](https://user-images.githubusercontent.com/18663291/62787687-82f61600-bac5-11e9-987a-9c6cb1439b61.png)

Der Abschnitt "Copy or imprint" ergibt hier wirklich keinen Sinn. Besser wäre, bei Konvoluten das Jahr nach Source Description zu verschieben.

**Comment by jenniferward** [comment]
https://opac.rism.info/search?id=1001068757&View=rism

Jetzt fehlt das Jahr komplett. Das Jahr soll auf jeden Fall angezeigt werden. Mein Vorschlag wäre im Abschnitt Source Description--> Material:

![image](https://user-images.githubusercontent.com/18663291/64530331-288ee600-d30d-11e9-8624-8208525572fd.png)

**Comment by BernLutz** [comment]
Das Jahr ist im Abschnitt Material eingetragen.
