### ISSUE TITLE
Suchfilter Besetzung

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#26]
Für den Suchfilter (Suche verfeinern) "Besetzung" werden offensichtlich sowohl das Feld Besetzungshinweis (240) als auch das Feld Besetzung insgesamt (594) ausgewertet. Das ist so nicht gewünscht; bitte nur das Feld Besetzungshinweis (240) verwenden!
Beispiel:
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe41007394%22
Zum einen erscheinen dadurch viele Titel zwei Mal im Suchfilter, zum anderen ist ein aufgeblähter Suchfilter für den Nutzer äußerst unpraktisch.

**Comment by jenniferward** [comment]
Hmmm, ich bin gerade darüber gestolpert, dass wir das tatsächlich gewünscht haben! So war das im Lastenheft (siehe Entwurf_Lastenheft_RISM_OPAC_Weiterentwicklung sortiert , Nr 49) und auch aus der Nutzerstudie: "Besetzung insgesamt soll berücksichtigt werden." :-o

**Comment by alexandermarxen** [comment]
Wenn ich das richtig sehe, bezieht sich der Eintrag im Lastenheft auf die Suche, nicht auf den Suchfilter.
Bei der Suche muss natürlich unbedingt auch das Feld Besetzung insgesamt (594) berücksichtigt werden.
Bei den Suchfiltern ist das eher kontraproduktiv.

**Comment by BernLutz** [comment]
Der Filter wurde entsprechend den Anforderungen aus der E-Mail vom 5.9.2019 von @KlausKeil umgesetzt:
 "Er [der Filter] sollte sich speisen aus dem Besetzungshinweis (240 $m) und der Besetzung (594): aber gerade*nicht *aus dem Musikincipit (031 $m)"
