### ISSUE TITLE
"Suchergebnisse für diese ID" findet falsche Ergebnisse 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#260]
(Siehe #221: auch im Test-OPAC)

"Suchergebnisse für diese ID" bei Person pe30097534 https://opac.rism.info/search?id=pe30097534&View=rism findet https://opac.rism.info/search?id=000138474&View=rism und nicht die 2 Titel, die mit diesem Namen verknüpft sind:
https://opac.rism.info/search?id=212001507&View=rism 
https://opac.rism.info/search?id=212001309&View=rism
 
Siehe auch #181

**Comment by BernLutz** [comment]
Danke für die Meldung. Ist erledigt.
