### ISSUE TITLE
Exemplareintrag bei Konvolutbestandteilen ohne Darstellung von Feld "Eingesprungen (973)" 

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/opac-report#261]
Anders formuliert: Es fehlt in den Exemplareinträgen bei Konvolutbestandteilen der Link zum Haupteintrag des Konvolutes. 

Bsp.: 990035744 und 990035748: Es geht um die Exemplareinträge von D-LEm (Leipziger Stadtbibliothek). Dort fehlt der Link zur RISM ID 1001065921 des Konvoluthaupteintrages.

**Comment by BernLutz** [comment]
Danke für den Hinweis @Docudoctor 
Wir bräuchten hier bitte noch die Information, wie das Label von 973 in den 5 Sprachen (DE/EN/FR/IT/ES) benannt werden soll.

**Comment by MFalletta** [comment]
DE: Zusammengebunden mit

**Comment by MFalletta** [comment]
EN: Bound with 
FR: Relié en 
IT: Rilegato con

**Comment by jenniferward** [comment]
ES: Encuadernado con

**Comment by BernLutz** [comment]
Wird konzeptionell (Konvoluthaupteintrag?) zwischen RISM ZR und SLUB geklärt und in den FID Antrag 2021-23 aufgenommen

**Comment by jenniferward** [comment]
Zum Thema Darstellung der Konvolute: Aus unserer Sicht sind lediglich die Rückverweise vom Holdings eines Items zum Konvoluteintrag notwendig. Das Feld 973 wird mitgeliefert. 
https://opac.rism.info/search?id=990035744&View=rism

**Comment by BernLutz** [comment]
Vielen Dank für die Information @jenniferward 
Aktuell wird das Feld 774 im OPAC mit dem Label "Sammelwerk" angezeigt. Gibt es hier von Ihrer Seite Änderungswünsche? Grundsätzlich kann über das Feld ja sowohl auf eine Collection als auch auf ein Konvolut verlinkt werden. Wäre "Sammelwerk oder Konvolut" oder vielleicht noch einfacher „Übergeordneter Eintrag“ eine Alternative?

**Comment by jenniferward** [comment]
Vielen Dank, das stimmt, 774 gib es auch noch. OK, vielleicht ist das Thema nicht so unkompliziert wie auf dem ersten Blick. Wegen 774: das muss ich mir noch überlegen. 
Wenn man auf dem Konvoluteintrag ist (Beispiel: https://opac.rism.info/search?id=1001174640&View=rism ) sieht man den Überschrift "Collection." Kann man diese Überschrift nur für Konvolute ändern? Zum Beispiel, auf English "Composite volume"?

**Comment by BernLutz** [comment]
Leider ist aus Feld 774 ja nicht ersichtlich, in welcher Beziehung die Datensätze zueinander stehen.
Wenn ich richtig sehe, dann müsste daher der angezeigte Feldtitel beide Optionen (Collection und/oder Konvolut) einschließen. Denn die einzige spezifische Konvolut-Kennzeichnung ist bislang nur in den Exemplaren der Drucke (Feld 973) eingetragen.
Wäre es denn generell möglich, das Abhängigkeitsverhältnis in den Daten selbst differenzierter darzustellen? Also den Teil eines Konvolutes für alle Quellentemplates einheitlich zu belegen? Andernfalls bleibt denke ich nur die Option, den Feldtitel so zu wählen, dass er für alle möglichen Fälle zutreffend ist.

**Comment by jenniferward** [comment]
Ja, ich habe es mir auch überlegt, ob wir das nicht differenzierter darstellen können. Ich werde das Thema mit den Entwicklern aufnehmen.
Ich meine, die Konvolute haben den Parameter "npc" im Leader.
Für 774: Ich habe mich für "Part of:" entschieden.
ES: Ítem integrante de

**Comment by BernLutz** [comment]
Super, vielen Dank @jenniferward !

**Comment by jenniferward** [comment]
Hallo @BernLutz  - leider scheint es nicht möglich zu sein, unser Feld 774 weiter zu differenzieren wie bei den Drucken. Doch eine Berücksichtigung von "npc" im Leader würde für unsere Zwecke ausreichen, oder?

**Comment by BernLutz** [comment]
Ich nehme den Punkt gerne einmal mit in die Anforderungsbeschreibung mit auf und kläre, ob dies technisch möglich ist.
Das System müsste dann aus dem untergeordneten Eintrag über die ID aus Feld 773 ermitteln, ob der dort verlinkte Datensatz im Leader "npc" enthält.
Falls dies möglich sein sollte, wäre ein spezifisches Label ja möglich und sinnvoll, z. B.: 
DE: Konvolut
EN: Composite volume
ES: Volumen compuesto
FR: Volume composite
IT: Volume composito

**Comment by BernLutz** [comment]
Leider ist es nicht möglich, die Information zur Art der hierarchischen Verknüpfung aus einem anderen Datensatz zu ermitteln.
Da auch in den Daten keine Differenzierung möglich ist, würde ich als Lösung nun noch einmal die Umbenennung des Labels vorschlagen. Wie oben beschrieben, könnten wir statt "Sammelwerk" oder "Konvolut" einen Begriff wie „Übergeordneter Eintrag“ o.ä. für den Link zu 773 verwenden. Wären Sie damit einverstanden @jenniferward ?

**Comment by jenniferward** [comment]
Trotzdem danke! Ja, fassen wir dann zusammen. Ich bleibe bei:
EN: Part of
ES: Ítem integrante de

Ich erkläre dann im Hilfetext, was gemeint ist.
