### ISSUE TITLE
Bibliothekssigel, Signatur und alte Signatur aus MARC Subfeldern von (852) fehlen bei im Handschriftentemplate katalogisierten Drucken

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/opac-report#263]
Beispiele RISM IDs 702010182 und 702012716.
Im Produktivsystem ist alles vorhanden.

**Comment by HirschSt** [comment]
same as #262

**Comment by HirschSt** [comment]
Wir vermuten, dass für die Auswahl des Drucketemplates im OPAC nicht der Leader verwendet wird, sondern ein enstprechendes Datafield (z.B. 593). Bei Titeln im HS-Template fehlt aber jeglicher Holding-Eintrag, d.h. Angaben über den Fundort führen ins Leere.

@BernLutz Bitte für die Auswahl des Anzeigetemplates im OPAC den Leader auswerten, bei Ms. z.B. "ndm", bei Prints z.B. "ncc", s. https://github.com/rism-ch/muscat/blob/004f0d5fe946639de6f54897f4ad93b6a14c0499/lib/marc_source.rb#L373

Bei den genannten Beispieltiteln enthält der Leader entsprechend "ndm".

**Comment by KlausKeil** [comment]
@BernLutz Wir haben aus der Vergangenheit mindestens 50.000 Titel, in denen Drucke im Hs-Template eingegeben sind. Das wird also sicher auffallen. Deshalb muss ich Sie bitten, diese Änderung noch möglichst bald machen zu lassen.

**Comment by BernLutz** [comment]
Gibt es außer den beiden Parametern "**ndm**" für Handschriften und  "**ncc**" für Drucke noch weitere Parameter, die bei der Auswertung des Leaders berücksichtigt werden müssen?

**Comment by HirschSt** [comment]
Alle Parameter stehen im oben referenzierten Quelltext: 

etwa "ntm" wäre für handschriftliche Libretti (z.B. https://muscat.rism.info/sru?maximumRecords=100&operation=searchRetrieve&query=id=1001082039&startRecord=1&version=1.1), 

"nam" für gedruckte Libretti (z.B. https://muscat.rism.info/sru?maximumRecords=100&operation=searchRetrieve&query=id=1001082595&startRecord=1&version=1.1)

**Comment by BernLutz** [comment]
Wenn ich richtig sehe, wäre die Zuordnung dann folgende:
Drucke: nam, ncc, ncd, ncm, ndc
Handschriften: ndd, ndm, npm, ntm

"npm" als Parameter für handschriftliche und gedruckte Theoretica integriert dann allerdings auch die entsprechenden Drucke in das Handschriftentemplate (im Script: "we cannot make the distinction between ms and print").

Sollte der Leader dann auch gleich die Zuordnung der Icons (Druck oder Handschrift) steuern, #235 ?

**Comment by BernLutz** [comment]
Können Sie die Zuordnung der Parameter zu den Templates (s. oben) bestätigen @HirschSt ?
Im Skript steht z.B.: "type = "dc" if source.record_type != RECORD_TYPES[:edition_content]", ich nehme hier an, dass "ndc" als Druck gewertet werden soll.
Die ID 1001072169 - mit dem Parameter "ndc" - ist aber beispielsweise eine Handschrift: 
https://opac.rism.info/search?id=1001072169&View=rism

**Comment by HirschSt** [comment]
@BernLutz nicht ganz: https://github.com/rism-ch/muscat/blob/004f0d5fe946639de6f54897f4ad93b6a14c0499/lib/marc_source.rb#L380 modifiziert, aber der Code-Snippet hier ist leider nicht ganz sauber und verwirrt, wir sollten lieber eine switch-case Schleife nutzen. 
Sie können alle leader auch noch in Muscat direkt prüfen, wenn Sie sich anmelden und nach den Templates suchen, vielleicht ist das einfacher.
Es gibt auch noch einen Bug dazu, der mit 6.0 gefixt wird: https://github.com/rism-ch/muscat/issues/813

**Comment by BernLutz** [comment]
Leider komme ich mit den Templates in Muscat auch zu keinem Ergebnis.
"ndd" finde ich z.B. einmal als Druck:
https://muscat.rism.info/admin/sources/469415508.xml

... und einmal als Handschrift:
https://muscat.rism.info/admin/sources/1001078219.xml

Wir können die Parameter der Leader gerne für die Zuweisung der Templates nutzen, aber wir brauchen dann konkrete Angaben über die zu verwendeten Marker in Form einer Liste o.ä.

**Comment by HirschSt** [comment]
In Muscat sind beide im Template "Musikhandschrift" erfasst, und so kann das auch genutzt werden:  469415508 z.B. ist ein im **Handschriften-Template** erfasster Druck, und keine Druck im **Drucke-Template**

**Comment by BernLutz** [comment]
Es müsste dennoch redaktionell festgelegt werden, welche Parameter nun für die Drucke und welche Parameter für die Handschriften gelten sollen.

Was sich in Muscat findet:
Handschrift: = ndc, ndm, ntm, npm
Druck: = ncc, ncd, nam
 
Ebenso gibt es in Muscat auch Aufnahmen ohne Leader (z.B. gedr. Theoretica: https://muscat.rism.info/admin/sources/1001037009).

Wenn Sie uns die Aufstellung der sieben Parameter bestätigen, korrigieren oder erweitern,  dann setzen wir die Anforderung gerne um.

**Comment by HirschSt** [comment]
Hier die ergänzte Liste:
- Handschrift: ndc, ndd, ndm, ntm, npm
- Druck: ncc, ncd, nam

**Comment by jenniferward** [comment]
@HirschSt : Ich habe die Datensätze mit "ncc" in LDR heruntergeladen und sehe, dass ca. 1500 Titel mit anderen Templates erfasst wurden. Die sind also keine Drucke, wie ich erwartete. Ist das problematisch?
Beispiele:

https://opac.rism.info/search?id=450032277&View=rism Collection, Handschrift, Abschrift
https://opac.rism.info/search?id=450302983&View=rism Collection, Handschrift, Autograph
https://opac.rism.info/search?id=1001100933&View=rism Collection, Handschrift, Abschrift
Ist es Zufall, dass diese Beispiele "Collections" sind aber ohne Einzeleinträge?

**Comment by HirschSt** [comment]
@jenniferward Gut gesehen! Der Fehler liegt bei der dynamischen to_external Methode https://github.com/rism-ch/muscat/blob/c1a715d45c9d9eec8ac048d2944f0cd2af5c3e57/lib/marc_source.rb#L374:

Hier wird bei Collections zunächst "cc" festgelegt; in der anschliessenden Verzweigung wird dieses zu "dc", **wenn** bei den Untereinträgen kein Druck vorliegt. Da die von Dir genannten Titel aber keine Untereinträge haben, bleibt das "cc" einfach stehen. Übrigens: das Template (der record_type) wird nicht durch den leader definiert, sondern durch ein Datenbankfeld (der leader ist nicht Bestandteil der Marc-Daten).

Das kann nur durch eine Änderung in Muscat verbessert werden, ich kümmere mich darum.

**Comment by jenniferward** [comment]
Alles klar, danke für die Infos!

**Comment by HirschSt** [comment]
see https://github.com/rism-ch/muscat/issues/902

**Comment by BernLutz** [comment]
Die Icons für Handschriften und Drucke werden nun entsprechend des Leaders angezeigt, vgl. #263
