### ISSUE TITLE
Weitere Angaben und Bemerkungen: Feldbezeichnung zu (596) ist falsch

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/opac-report#265]
Beispiel RISM ID 1001074921. Dort lautet die Feldbezeichnung fälschlich RISM B/I.

ES MUSS HEISSEN: Querverweise zu RISM A/I und RISM B !!!

**Comment by jenniferward** [comment]
Heute heißt das Feld "Dramatic roles named, standardized" ??
Beispiel:
https://opac.rism.info/search?id=900010978&View=rism
![image](https://user-images.githubusercontent.com/18663291/65972063-90969f00-e469-11e9-8bdc-2465809691d7.png)

**Comment by BernLutz** [comment]
Die Umbenennung von 596 ist in der BSB in Arbeit, siehe auch #266. Allerdings scheint hier auch etwas in den Daten nicht ganz zu stimmen. Das Subfield $a ist hier sowohl mit der RISM-Serie als auch mit der RISM-Nummer belegt. Die Nummer sollte eigentlich in $b stehen. Ich habe in Muscat keinen Zugriff auf den Datensatz. Könnten Sie den Datensatz korrigieren @jenniferward ? Dann können wir uns ansehen, ob das Phänomen danach immer noch besteht.
![grafik](https://user-images.githubusercontent.com/44613113/66044284-7b7d4700-e521-11e9-8f56-1a5a2aaa18e9.png)

**Comment by jenniferward** [comment]
@BernLutz : Der Eintrag 900010978 ist recht komisch, da liegt wohl ein Konvertierungsfehler aus Kallisto(!) vor. Habe ich korrigiert. Nach dem Update überprüfe ich den Datensatz und melde ich mich hier wieder.
(Ob andere Datensätze auch betroffen sind?? Das kann ich überprüfen.)

Ticket #266 doppelt

**Comment by jenniferward** [comment]
@BernLutz : Ich habe gerade ein Beispiel gefunden, in dem 596 richtig ist, wird aber als "Dramatic roles named, standardized:" angezeigt:
![grafik](https://user-images.githubusercontent.com/18663291/74717802-4dc73f00-5231-11ea-8b2e-33ec9ec9f43f.png)
![grafik](https://user-images.githubusercontent.com/18663291/74717837-60da0f00-5231-11ea-939a-e7598ffe1d70.png)


https://opac.rism.info/search?id=1001036258&View=rism

**Comment by jenniferward** [comment]
Hallo @BernLutz , der OPAC ist nun aktuell aber das Problem wie bei 900010978 beschrieben besteht immer noch.

900010978 hatte ich korrigiert:
https://opac.rism.info/search?id=900010978&View=rism
![image](https://user-images.githubusercontent.com/18663291/75334935-f6584d00-5888-11ea-8c7f-719c61d9afba.png)

![image](https://user-images.githubusercontent.com/18663291/75334976-0708c300-5889-11ea-9971-9e8110fa57f9.png)
