### ISSUE TITLE
Weitere Angaben und Bemerkungen: Das Subfeld (596 $a) fehlt in der Anzeige

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/opac-report#266]
Beispiel RISM ID 1001074921. Hier steht nur die A/I-Nummer.
Es fehlt der RISM-Serienname A/I

**Comment by BernLutz** [comment]
@Docudoctor die Angaben aus 260 sind im Bereich "Material" erfasst. In den Verlagsangaben sind die Normadtenverweise aus Marc 700/710 verlinkt. Soweit ich sehe, ist dieses Prinzip auch in Muscat so angelegt
![grafik](https://user-images.githubusercontent.com/44613113/66046560-517a5380-e526-11e9-9e79-54c47cae5a58.png)
Gibt es hier noch Änderungsbedarf? Dies betrifft auch das #267

**Comment by BernLutz** [comment]
Der RISM-Serienname wird nun angezeigt.
