### ISSUE TITLE
Verleger aus MARC-Feld (260 $b) fehlen im Abschnitt Verlagsangaben

### ISSUE THREAD

**Issue by Docudoctor** [rism-international/opac-report#267]
Beispiel RISM ID 1001068562. 
Es handelt sich um drei Verlage.

**Comment by BernLutz** [comment]
@Docudoctor könnten Sie dies noch einmal überprüfen? Ich kann den Fehler nicht reproduzieren. Danke!

**Comment by BernLutz** [comment]
@Docudoctor die Angaben aus 260 sind im Bereich "Material" erfasst. In den Verlagsangaben sind die Normadtenverweise aus Marc 700/710 verlinkt. Soweit ich sehe, ist dieses Prinzip auch in Muscat so angelegt
![grafik](https://user-images.githubusercontent.com/44613113/66046560-517a5380-e526-11e9-9e79-54c47cae5a58.png)
Gibt es hier noch Änderungsbedarf? Dies betrifft auch das Issue #264

**Comment by KlausKeil** [comment]
Im Opac ist unter Material nur SCHLESINGER angegeben. Die beiden anderen fehlen. Stattdessen eine Leerzeile: 
1 part - pf - 16 p.
Druck: early 1842 ; Paris; MAURICE SCHLESINGER

Notes on material: Page [i] : TP, p. [ii, 1]: blank.
Musical text: p. 2-16.
Heading, p. 2: FANTAISIE | PAR | F. CHOPIN, OP. 49.
Footline p. 2: F. CHOPIN, op 49. [space] M. S. 3489. [space] Maurice Schlesinger, rue de Richelieu, 97.; p. 3-15: M. S. 3489.; p. 16: F. Chopin, op. 49. [space] Maurice Schlesinger, rue de Richelieu, 97. | M. S. 3489.

**Comment by BernLutz** [comment]
Mehrfachbelegung von Marc 260 berücksichtigen

**Comment by BernLutz** [comment]
Lieber Herr @KlausKeil, könnten Sie diesen Punkt noch einmal prüfen? Laut unserer Konfiguration ist das Feld 260 mehrfach belegbar. In dem Beispiel (https://opac.rism.info/search?id=1001068562&View=rism) ist dem Material in Feld 260 auch nur ein Verlag - Schlesinger - zugeordnet. Die beiden anderen Verlage (Breitkopf & Härtel und Wessel & Stapleton) werden zusätzlich unter den Verlagsangaben angezeigt (Feld 710).

**Comment by BernLutz** [comment]
Kann das Ticket geschlossen werden @Docudoctor ?
