### ISSUE TITLE
Permalinks mit führenden Nullen in RISM-IDs müssen weitergeleitet werden

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#268]
Die Permalinks, die früher mit führenden Nullen gefüllt waren, sollen weitergeleitet werden. Beispiele:

ALT https://opac.rism.info/search?id=00000990026684&View=rism
NEU https://opac.rism.info/search?id=990026684&View=rism

ALT https://opac.rism.info/search?id=00000990065011&View=rism
NEU https://opac.rism.info/search?id=990065011&View=rism

ALT https://opac.rism.info/search?id=00000993100007&View=rism 
NEU https://opac.rism.info/search?id=993100007&View=rism

**Comment by BernLutz** [comment]
Die Nullen wurden - wie mit @MFalletta besprochen - durch die BSB-IT weggeparsed, um eine Verlinkung der Datensätze zu ermöglichen. Die funktionslosen Permalinks sind dabei eine Begleiterscheinung, die vorab bekannt war. Vielleicht könnte die Zentralredaktion hier eine Mitteilung an die Benutzer schicken?

**Comment by KlausKeil** [comment]
Herr Hirsch hat mir nochmals mitgeteilt, dass hier vom Servermanagement ein Redirect eingerichtet werden muss. Dabei werden Links mit führenden Nullen zu solchen ohne führende Nullen umgeleitet. 
Funktionslose Permalinks sind hölzerne Eisen. Wenn sie als Permalinks veröffentlicht wurden, dann dürfen sie nicht funktionslos sein.

**Comment by BernLutz** [comment]
Die Vornullen der IDs sind weggeparsed, werden aber nun unter dem ID-Sucheinstieg berücksichtigt. Dadurch werden beide Varianten – mit und ohne Nullen - gefunden. Durch diese Anpassung funktionieren auch die alten Permalinks wieder.
