### ISSUE TITLE
Normdateien  Literatur und Sigel nicht verlinkt in der Vollanzeige

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#269]
Die Normdateien/Indizes "Literatur" und "Institutionen" werden noch nicht verlinkt. 

Beispiel: 
https://opac.rism.info/search?id=1001074921&View=rism

![image](https://user-images.githubusercontent.com/18663291/64527054-3ccee500-d305-11e9-8522-50bb8f8d4f4c.png)

![image](https://user-images.githubusercontent.com/18663291/64527076-4bb59780-d305-11e9-9106-c71dc47d5d31.png)

**Comment by BernLutz** [comment]
Die entsprechenden Felder werden nun verlinkt
