### ISSUE TITLE
856 Externe Links in Materialbeschreibung

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#27]
Externe Links, die einer bestimmten Materialart zugeordnet sind, werden derzeit beim Hauptmaterial angezeigt (856 $u/z mit $8 = 1\c etc.). Die Links müssen im Block „Materialbeschreibung“ bei der jeweiligen Materialart angezeigt werden.
Beispiel:
https://muscat.rism.info/admin/sources/464130078
https://opac.rism.info/search?id=464130078&View=rism

**Comment by BernLutz** [comment]
Die Links werden jetzt im Material angezeigt.
