### ISSUE TITLE
"Online lesen" findet auch Links zu Wasserzeichen, Stempel usw.

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#270]
In der Vollanzeige soll der Button "Online lesen" nur zu Quellendigitalisaten führen. Er scheint aber alle (?) URLs anzuzeigen.

Beispiel: 
https://opac.rism.info/search?id=990046739&View=rism

![image](https://user-images.githubusercontent.com/18663291/64527825-42c5c580-d307-11e9-8f2d-a5c416ffc174.png)

1 = Quellendigitalisat
2 = Besitzerstempel in einer externen Datenbank

Noch ein Beispiel:
https://opac.rism.info/search?id=990003355&View=rism
![image](https://user-images.githubusercontent.com/18663291/64527984-a51ec600-d307-11e9-90ff-d215f2f93a58.png)
1 = Besitzerstempel in einer externen Datenbank
2 = Quellendigitalisat

Auch wird das Digitalisat des Stempels mit "e" bei den Exemplaren gekennzeichnet:
![image](https://user-images.githubusercontent.com/18663291/64528079-e3b48080-d307-11e9-9661-9b5fc75a6643.png)

Die Bezeichnung "Online lesen" und "e" sollen nur die Quellendigitalisate auszeichnen. 

Siehe #22

**Comment by BernLutz** [comment]
Eine Anpassung der Anzeige der Digitalisate über den Online lesen-Button ist für die kommende FID-Phase 2020 als eigener Punkt beantragt.
