### ISSUE TITLE
Sigel steht zu weit unten in der Exemplaranzeige

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#271]
Als Nutzer würde ich erwarten, dass man sofort nach dem Öffnen des Sigel-Kästchens die besitzende Bibliothek mit Kontaktinfos (#269, #109) angezeigt bekommt. Das Bibliothekssigel kann aber an 3. Stelle vorkommen, was viel zu weit unten ist: 

https://opac.rism.info/search?id=990026684&View=rism
![image](https://user-images.githubusercontent.com/18663291/64529120-70f8d480-d30a-11e9-88c1-5f34be35f9ff.png)
Die Angabe D-Dl ist wichtiger als Material oder Olim und soll an erster Stelle angezeigt werden.

**Comment by BernLutz** [comment]
Das Bibliothekssigel steht nun an erster Stelle im Exemplareintrag.
