### ISSUE TITLE
Exemplare "alle anzeigen" lassen? 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#272]
Ich frage mich, ob es sinnvoll wäre, die Möglichkeit "alle anzeigen/öffnen" (show all ?/ open all?) bei den Exemplaren anzubieten? Z.B. bei https://opac.rism.info/search?id=990026684&View=rism ist es mühsam, alle 70+ Exemplare zu öffnen. Es kann sein, dass jemand alle Exemplare einfach durchstöbern möchte.

Was meinen die anderen?

**Comment by KlausKeil** [comment]
Das wäre sinnvoll, man sollte es aber auf die Exemplareinträge begrenzen, in denen Angaben sind, die über Bibliothekssigel und Signatur hinausgehen.

**Comment by BernLutz** [comment]
Die Einbindung eines Schalters zum Öffnen und Schließen der Exemplare ist nun auf der Testinstanz umgesetzt @jenniferward:
https://opactest.bsb-muenchen.de/metaopac2/search?id=990026684&View=rism

**Comment by jenniferward** [comment]
Sieht gut aus. So kommt man auch schnell an den richtigen Vorbesitzer, wenn man z.B. nach Personen sucht. Danke!
