### ISSUE TITLE
Personen - Namensvarianten sind nicht mehr suchbar

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#273]
In der aktuellen OPAC-Version sind Namensvarianten nicht mehr suchbar.
Dies ist beispielsweise bei Čajkovskij, Pëtr Il'ič äußerst ungünstig.
Bislang wurden die Namensvarianten in der erweiterten Suche als weitere Vorschläge (Autocomplete) angegeben. Das war teilweise sehr verwirrend, da nicht klar war, dass es sich um dieselbe Person handelte. (Siehe auch Ticket #186 ).
Grundsätzlich sollten Sonderzeichen beim Autocomplete ignoriert werden (Siehe Ticket #185 ).
Ideal wäre eine Lösung, bei der die Varianten durchsucht werden, aber nicht als eigener Eintrag bei den Vorschlägen erscheinen (Siehe Ticket #66 ).
Falls dies nicht geht, bitte die Varianten beim Autocomplete weglassen, aber dennoch bei der Suche berücksichtigen.

**Comment by BernLutz** [comment]
Die Verweisformen werden jetzt in der Suche berücksichtigt. 
Beim Autocomplete können wir aktuell leider keine isolierten Anpassungen vornehmen, da die Funktion mit vielen weiteren BSB-Anwendungen gekoppelt ist. Hier sind aber bereits konkrete Schritte hin zu einer verbesserten Funktionalität geplant.
