### ISSUE TITLE
Links "MARCXML / RDF/XML anzeigen" sind weg

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#274]
Wir hatten ja bisher immer die Links "MARCXML / RDF/XML anzeigen" in jedem Eintrag. Seit gestern (Nachmittag?) sind sie weg.

Sollten hier angezeigt werden:
![image](https://user-images.githubusercontent.com/18663291/64766573-7e020780-d546-11e9-922c-ebd6787de6bb.png)

Beispiele:
HS in Collection:
https://opac.rism.info/search?id=464000732&View=rism

Collectioneintrag:
https://opac.rism.info/search?id=1001041374&View=rism

Druck:
https://opac.rism.info/search?id=1001080818&View=rism

**Comment by BernLutz** [comment]
Die Anzeige ist wieder verfügbar.
