### ISSUE TITLE
041 $a $e $g differenzieren 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#276]
Für die Nutzer ist die Unterscheidung zwischen 041 $a, $e und $g wichtig, da sie verschiedene Bedeutungen haben (teilweise neu; #028).
Wir brauchen 3 Felder:
Language of text (041 $a)
Language of libretto (041 $e)
Language of original text (041 $h)

Aktuell im OPAC werden die Felder in einer Zeile angezeigt: 
https://opac.rism.info/search?id=300234487&View=rism
![image](https://user-images.githubusercontent.com/18663291/64792576-edddb580-d579-11e9-837c-6d67105703e9.png)
Der Nutzer weiß hier nicht, dass "Italienisch" sich eigentlich auf die Originalsprache bezieht.

**Comment by BernLutz** [comment]
Die Differenzierung ist im OPAC umgesetzt:
https://opac.rism.info/search?id=300234487&View=rism
