### ISSUE TITLE
Einige URLs weisen <br/> auf, führt zu Fehlermeldung

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#279]
In einigen Links zu Quellendigitalisaten (856 $u)  werden ein < br > ans Ende der URL angehängt [ohne Blank], was zu einer Fehlermeldung führt. In Muscat sind die Links in Ordnung.
Es kommt bei den Exemplaren vor, zum Beispiel:

https://opac.rism.info/search?id=993121834&View=rism
Oben, bei "Online lesen", ist die URL in Ordnung:
![image](https://user-images.githubusercontent.com/18663291/66038322-1b32d900-e512-11e9-8332-5e48d3a2ff0b.png)

Unten beim Exemplar sieht man ein < br/ > am Ende der URL und der Link funktioniert nicht:
![image](https://user-images.githubusercontent.com/18663291/66038399-51705880-e512-11e9-9bff-b34fb1323534.png)

Ich sehe denselben Fehler in diesem Titel:
https://opac.rism.info/search?id=993104441&View=rism
Exemplar A-Wn
![image](https://user-images.githubusercontent.com/18663291/66038481-8b415f00-e512-11e9-8f42-a47e01202c1f.png)
Exemplar BSB:
![image](https://user-images.githubusercontent.com/18663291/66038513-9d230200-e512-11e9-9a2b-27d567bca75c.png)

Komischerweise funktioniert der Link in diesem Titel (aus der BSB) trotz < br/ >:
https://opac.rism.info/search?id=990025939&View=rism

**Comment by BernLutz** [comment]
Das <br/> wurde aus den Links entfernt.
