### ISSUE TITLE
700 Felder ohne $4 Zuordnung

### ISSUE THREAD

**Issue by BernLutz** [rism-international/opac-report#280]
Es existieren Datensätze mit belegten 700 Feldern ohne $4 Zuordnung. In diesen Fällen kann im OPAC keine Zuordnung zu einem Label erfolgen, z.B. "Dürr, Johann" im Datensatz  990047070.

Vermutlich gilt dies auch für das Feld 710.

Wäre es denkbar, eine obligatorische Belegung von subfield $4 für die Felder 700/710 in Muscat festzulegen?

**Comment by alexandermarxen** [comment]
Herzlichen Dank für den Hinweis, ich habe ein entsprechendes Ticket erstellt, siehe: https://github.com/rism-international/tasks/issues/686

**Comment by KlausKeil** [comment]
Erscheint so im OPAC: 
???en.rism.personrole.???: Dürr, Johann <1600c-1663>More Information; ???en.rism.personrole.???: Jacobi, Johann Sebastian <17.sc>
Liste von Stephan scheinbar noch nicht abgearbeitet.

**Comment by HirschSt** [comment]
> Liste von Stephan scheinbar noch nicht abgearbeitet.

Doch, siehe https://github.com/rism-international/tasks/issues/711
