### ISSUE TITLE
541$a wird nicht angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#281]
541 $a, Source of acquisition note, wird geliefert aber nicht angezeigt.
Beispiel
https://opac.rism.info/search?id=464000485&View=rism

In der MARC-Anezige:
![image](https://user-images.githubusercontent.com/18663291/66555918-b0a41d80-eb4f-11e9-81ca-fb63f859ba96.png)

Bitte dieses Feld veröffentlichen.

**Comment by BernLutz** [comment]
Das Feld soll laut der Liste zur Darstellung der Musikdrucke auch nicht angezeigt werden:
![grafik](https://user-images.githubusercontent.com/44613113/66568181-31234800-eb69-11e9-919f-fb667272c9e4.png)
#168

**Comment by jenniferward** [comment]
Ach so, Entschuldigung! Danke! Ich kläre das intern, dann melde ich mich wieder bzw. schließe ich das Ticket.

**Comment by BernLutz** [comment]
Alles klar, dankeschön!

**Comment by jenniferward** [comment]
Wir haben dieses Ticket intern diskutiert und wollen das Feld tatsächlich veröffentlichen. 

EN:
541: Source of acquisition 
$c: Method of acquisition
$a: Source of acquisition note
$d: Date of acquisition
$e: Accession number

ES: 
541: Fuente de adquisición
$c: Método de adquisición
$a: Nota sobre la fuente de adquisición
$d: Fecha de adquisición
$e: Número de adquisición

**Comment by BernLutz** [comment]
Gerne nehmen wir die Felder mit auf. Im OPAC würde sich dazu ein Eintrag in der Rubrik "Provenienz und Fundort" anbieten - oder gibt es andere Vorschläge?

Die Label für FR und IT sind in Muscat folgend belegt:
 
FR:
541: Source d'acquisition
$c: Méthode d'acquisition
$a: Source d'acquisition
$d: Date d'acquisition
$e: Numéro d'acquisition

IT:
541: Fonte immediata d'acquisto
$c: Metodo d'acquisto
$a: Nota sulla fonte d'acquisto
$d: Data d'acquisto
$e: Numero di acquisizione

Sollen diese so auch im OPAC angezeigt werden @MFalletta ?

**Comment by jenniferward** [comment]
"Provenienz und Fundort" ist für mich auf dem ersten Blick in Ordnung!

**Comment by MFalletta** [comment]
FR und IT können gerne so übernommen werden.

**Comment by BernLutz** [comment]
541$a wird nun angezeigt.
