### ISSUE TITLE
Anzeige der hochgestellten Zeichen nach einem Pipesymbol

### ISSUE THREAD

**Issue by BernLutz** [rism-international/opac-report#282]
Sollen grundsätzlich alle Elemente nach einem Pipesymbol ohne Spatium hochgestellt werden?
Bei der Anzeige der RISM B/I-Nummern scheint mir dies z.B. ungünstig,  da in den Daten oft nur ein Element mit "|" versehen ist, z.B. https://opac.rism.info/search?id=570006095&View=rism
![grafik](https://user-images.githubusercontent.com/44613113/66628686-d426a100-ebff-11e9-917f-39d9c939f37d.png)
Korrekt wäre ja "1583|2|4" anstelle von "1583|24".
Wenn die Hochstellfunktion nicht für alle Bereiche, sondern nur für einzelne Blöcke im OPAC gelten soll, bräuchten wir eine entsprechende Aufstellung, an welchen Stellen die Funktion eingesetzt werden soll.

**Comment by BernLutz** [comment]
#15

**Comment by KlausKeil** [comment]
Grundsätzlich muss das auf | folgende Zeichen hochgestellt werden, sofern auf | kein Leerzeichen folgt.  Aber immer nur das nächste. Wenn wie in dem Beispiel mehrere Zeichen folgen, die eigentlich hochgestellt werden müssen, ist das ein Datenfehler, der von der ZR bereinigt werden muss.

**Comment by BernLutz** [comment]
@KlausKeil @HirschSt wir haben die Hochstellfunktion für den TouchPoint wie gewünscht angepasst. Für die  oben genannten Bereiche müssten die Daten dann entsprechend bereinigt werden.
![grafik](https://user-images.githubusercontent.com/44613113/78753682-830d2500-7976-11ea-8cf3-9a6bab3bf42a.png)
Aktuell sind wir dabei, die Anpassung auch für die Normdaten im LD-Browser umzusetzen.

Das Beispiel der ID 993104551 ist ein Screenshot aus unserem aktuellen Entwicklungsbranch.

**Comment by BernLutz** [comment]
Die Anpassung wurde mit dem Release vom 29.6.2020 in die Produktion übernommen.
