### ISSUE TITLE
Einfache Suche berücksichtigt nur Musikquellen

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#283]
Bislang wurden bei der einfachen Suche auch die Normdateien durchsucht. Das ermöglichte (wenn auch etwas umständlich) beispielsweise die Suche nach Komponistinnen (ein vielfach geäußerter Wunsch!).
Siehe:
http://www.rism.info/en/home/newsdetails/select/rism_online_catalog/article/2/searching-for-people-in-the-new-rism-catalog.html
und Nr. 3 in der OPAC-Hilfe
https://opac.rism.info/index.php?id=8&L=0#c49

Könnte das wieder hergestellt werden? Ansonsten müssten wir die Hilfetexte anpassen.

**Comment by BernLutz** [comment]
Vielen Dank für den Hinweis. Wir suchen aktuell noch nach einer Lösung. Das Phänomen hängt vermutlich auch mit #155 zusammen.
