### ISSUE TITLE
Aufzählung von Digitalisaten bei Drucken

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#284]
Bei der Aufzählung von Digitalisaten bei Drucken mit mehreren Fundorten wird die Signatur aufgeführt aber nicht das Bibliothekssigel. Siehe Bild. 
Es sollte sowohl das Sigel als auch die Signatur angegeben werden. Beispiel: A-Wn 73.S.3*
Beipieltitel: https://opac.rism.info/search?id=990059797&View=rism
![Bildschirmfoto von 2019-11-06 12-23-35](https://user-images.githubusercontent.com/42997126/68294396-5e8fe280-0090-11ea-8663-b3004169122a.png)

**Comment by BernLutz** [comment]
vgl. auch #22
