### ISSUE TITLE
Aktualisierung der Personen-Normdatei (Gelöschte Personen-Datensätze)

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#285]
Beim letzten Update des OPAC sind zwar die neuen Personen eingespielt worden, inzwischen gelöschte Personen-Datensätze werden jedoch immer noch angezeigt.
Beispiel:
https://opac.rism.info/search?id=pe40205562&View=rism
Bitte auch die Personen-Datei beim Einspielen des Updates vollständig überschreiben.

Wir haben aufgrund einer Dateneinspielung (ICCU) zur Zeit noch zahlreiche Dubletten, die gelöscht werden.

**Comment by BernLutz** [comment]
@alexandermarxen Die Daten sind nun aktuell.  Am Beispiel von Claude Paul Taffanel ist der veraltete Datensatz nicht mehr im OPAC nachgewiesen:
https://opac.rism.info/search?id=pe40221137&View=rism
Könnten Sie diesen Punkt noch einmal prüfen und das Ticket dann schließen? Schon einmal vielen Dank!

**Comment by alexandermarxen** [comment]
Schon mal herzlichen Dank!
Wird dies bei inzwischen bei jedem Update gemacht? Aktuell gibt es im OPAC 140.872 Personen, in Muscat sind es 139.421. Auch wenn ich in den letzten Wochen viel gelöscht habe, kommt es mir immer noch sehr viel vor. Wissen Sie oder @HirschSt wie viele Personen für das letzte Update geliefert wurden?

**Comment by BernLutz** [comment]
Vielen Dank für die schnelle Antwort. Eigentlich sollten bei jeder Einspielung die Normdaten gänzlich überschrieben werden. Ich hake hier auch noch einmal nach.

**Comment by BernLutz** [comment]
Mir ist aufgefallen, dass auch Personen mit dem Muscat-Status "in Arbeit (UNP)" im OPAC enthalten sind. Könnte es sein, dass in der Datenlieferung grundsätzlich alle Daten geliefert werden?
z.B: Franceschina Abatantuono (id 40206954)
https://opac.rism.info/search?id=pe40206954&View=rism

**Comment by alexandermarxen** [comment]
Ja, es werden alle Personen-Daten geliefert, der Status spielt dabei keine Rolle (er hat eher eine interne Funktion).

**Comment by jenniferward** [comment]
Das ist mir gestern aufgefallen, bei dieser Literatur:
https://opac.rism.info/search?id=lit30010515&View=rism

**Comment by alexandermarxen** [comment]
@jenniferward Ja, das müssen wir auf jeden Fall in der Zentralredaktion klären. Bei den Personen ist es etwas anders: Da grundsätzlich auch veröffentlichte Musikquellen mit Personen verknüpft sein können, die noch den Status "in Arbeit (UNP)" haben, müssen alle Personen an den BSB-OPAC geliefert werden.

**Comment by alexandermarxen** [comment]
Beim aktuellen Update sind auch die in Muscat gelöschten Personen-Datensätze im OPAC nicht mehr vorhanden. Herzlichen Dank!
