### ISSUE TITLE
Zahl der Ergebnisse instabil 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#286]
Im Frühling hat ein Bibliothekar nach der Zahl der Quellen in verschiedenen italienischen Bibliotheken zwecks Projektplanung gesucht, und sich die Zahlen notiert. Am 3. Oktober ist es ihm aufgefallen, dass die Zahlen deutsch gesunken sind. Beispiele:

I-Fr -- Frühling: 144, Oktober: 33
I-Fl -- Frühling: 30, Oktober: 2

Ich habe ihm den Unterschied so erklärt, dass der OPAC seit der Umstellung im September 2019 nicht mehr die Einzeleinträge in den Drucken auch mitzählt, sondern nur die Haupteinträge. 

Heute ist es mir aufgefallen, dass der OPAC wieder alles mitzählt:
I-Fr -- heute 182 
I-Fl -- heute 31

Bleibt der heutige Stand nun stabil? Oder kann es wieder weniger werden?  Was wird eigentlich mitgezählt?

Neben Projektplanung werden die Zahlen auch in Publikationen verwendet: ich sitze gerade über einen Artikelentwurf (Stand Juli), in dem die Zahlen auch zwischen Juli und heute schwanken. Ich möchte der Autorin helfen, möglichst genaue Zahlen erfassen (und veröffentlichen) zu können.

**Comment by BernLutz** [comment]
Der aktuelle Stand müsste nun in jedem Fall stabil bleiben. Leider können wir nicht mehr nachvollziehen, wie es zu den Schwankungen der Zahlen gekommen ist. 
Eine genaue Übersicht, welche Felder für die Suche berücksichtigt werden, finden sich in der Excel zum vergangenen Release (Testliste_RISM_OPAC_Release_2019: hier Tabellenblatt "Formatanpassung").

**Comment by jenniferward** [comment]
Danke!
