### ISSUE TITLE
Literatur im OPAC 

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#287]
Ich habe entdeckt, dass nun auch Literatur im OPAC angezeigt wird, z.B.: 
https://opac.rism.info/search?id=lit200090&View=rism
Der Eintrag macht aber nur Sinn, wenn auch die Titel angezeigt werden, in denen diese Literatur vorkommt. Könnte also eine Liste der Titel angezeigt werden. In Muscat ist das vorhanden: s. Bildschirmabb.
 ![Bildschirmfoto von 2019-11-21 10-40-11](https://user-images.githubusercontent.com/42997126/69326017-62546500-0c4b-11ea-8a3c-644e6a22c75e.png)

**Comment by jenniferward** [comment]
Über den Link "Suchergebnisse für diese ID" sollte das vermutlich gehen, aber der Link funktioniert nicht.
https://opac.rism.info/metaopac/perma.do;jsessionid=AC2E71F2CFB26D20EE57E23E62553A56.touch02?v=rism&q=-1%3d%22lit200090%22
