### ISSUE TITLE
Belegung des Felds "Materialtyp/Quellentyp" (593)

### ISSUE THREAD

**Issue by BernLutz** [rism-international/opac-report#289]
Im Feld „Materialtyp“ (593) sind seit der letzten Dateneinspielung (Januar 2020) neue Auszeichnungen enthalten, die sich mit den bisherigen Belegungen überschneiden: 
z.B.: "Autograph" (https://opac.rism.info/search?id=403004226&View=rism) und "Autograph manuscript" (https://opac.rism.info/search?id=1001093888&View=rism). In Muscat selbst ist das Auswahlfeld einheitlich mit "Autograph manuscript" belegt. 

Ebenso verhält es sich mit der Kategorie "Fragliches Autograph" / "Possible autograph manuscript".
![grafik](https://user-images.githubusercontent.com/44613113/72245880-cbc07680-35f1-11ea-928e-a20be490b82f.png)

Für die Auswertung durch den Filter im RISM-OPAC wäre eine Vereinheitlichung der Werte wünschenswert.

Vgl. zu dem Thema auch #212

**Comment by KlausKeil** [comment]
Das kommt von den Datenübertragungen und wird von uns bereinigt
