### ISSUE TITLE
Outdated marcxml data dump at /data

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#290]
The set at https://opac.rism.info/main-menu-/kachelmenu/data is from January 2019 and very outdated. 

Please update this set with the latest one from January 2020.

related https://github.com/rism-ch/muscat/pull/884#issuecomment-578809313

**Comment by BernLutz** [comment]
Die LOD-Pakete sind aktualisiert. Eine Routine synchronisiert zukünftig die Daten mit der monatlichen Einspielung.
