### ISSUE TITLE
Städtenamen im Fundort bei Drucken

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#291]
Bei Drucken fehlt in der Anzeige des Fundortes der Städtenamen. Erst wenn man aufklappt, erfährt man den Namen. 
Außerdem fehlt wenn man aufklappt, das "heute in:"
Siehe: https://opac.rism.info/search?id=991025222&View=rism
Fundort D-DO 
müsste haben: 
heute in: Badische Landesbibliothek, Musikabteilung D-KA

**Comment by BernLutz** [comment]
a) Ort aus 110$c in blauen Exemplabalken nach Library (siglum)
b) Verweis im Exemplarbereich aus 580 (aktueller Aufbewahrungsort) mit dem Label "in:" vgl. #237
