### ISSUE TITLE
Sprachkürzel bitte auflösen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#294]
https://opac.rism.info/search?id=300234487&View=rism
![image](https://user-images.githubusercontent.com/18663291/74668129-de0b7280-51a4-11ea-855d-ab55807ea287.png)

Kann statt "ita" bitte "Italian" stehen? (grundsätzlich für alle Sprachen)

Aus #276

**Comment by BernLutz** [comment]
Das Sprachkürzel wird nun aufgelöst.
