### ISSUE TITLE
Personen mit neuen Funktionen fehlen in der Vollanzeige

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#295]
Es ist mir zufällig aufgefallen, dass neue (11.2019) Funktionen in 700/710 $4 nicht angezeigt bzw. falsch angezeigt werden.

Beispiele:
https://opac.rism.info/search?id=300000239&View=rism
Falsche Anzeige bei lse
![image](https://user-images.githubusercontent.com/18663291/75430889-48ae7200-594c-11ea-82ef-3a51291b7d2a.png)

https://opac.rism.info/search?id=840016415&View=rism
ppm geliefert aber nicht angezeigt
![image](https://user-images.githubusercontent.com/18663291/75430975-75628980-594c-11ea-9f6a-792c31bb3985.png)

Neu sind:
1. **asg**
EN: assignee
DE: Lizenznehmer 
ES: asignee 

2. **cph** 
EN: Copyright holder 
DE: Rechteinhaber
ES: titular de los derechos de copia

3. **lse**
EN: licensee 
DE: Lizenzinhaber 
ES: licensee 

4. **ppm** 
EN: papermaker
DE: Papierhersteller 
ES: fabricante de papel

Siehe #5 

(Neue Funktionen: https://github.com/rism-international/tasks/issues/716 )

**Comment by BernLutz** [comment]
@jenniferward Für die Einbindung neuer Begriffe benötigen wir immer die Übersetzungen in alle angebotenen Sprachen. Ich habe hier schon einmal Vorschläge (IT und FR) ergänzt. Würden Sie die Begriffe noch überprüfen und bei Bedarf korrigieren? Dann können wir die neuen Kategorien im OPAC anzeigen. Schon einmal vielen Dank! 

asg
EN: assignee
DE: Lizenznehmer
ES: asignee
**FR: ayants droit
IT: assegnatario**

cph
EN: Copyright holder
DE: Rechteinhaber
ES: titular de los derechos de copia
**FR: titulaire des droits sur la copie
IT: titolare dei diritti di copia**

lse
EN: licensee
DE: Lizenzinhaber
ES: licensee
**FR: licencié
IT: licenziatario**


ppm
EN: papermaker
DE: Papierhersteller
ES: fabricante de papel
**FR: fabricant de papier
IT: fabbricante di carta**

**Comment by jenniferward** [comment]
FR und IT ist @MFalletta

**Comment by MFalletta** [comment]
asg
FR: Licencié
IT: Licenziatario

cph
FR: Détenteur des droits
IT: Titolare dei diritti

lse
FR: Titulaire de licence
IT: Titolare di licenza 

ppm
FR: Papetier
IT: Fabbricante di carta
