### ISSUE TITLE
510 wird nur 1x angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#297]
Wenn ein Druck sowohl eine A/I- als auch eine B/I-Nummer hat, wird das Feld 510 2x ausgefüllt. Beide Nummern sind also vorhanden (siehe SH 24 Jul 2019 #24). Es sieht aber so aus, als würde nur die erste Instanz angezeigt. 
Beispiel:
https://opac.rism.info/search?id=993104538&View=rism
Muscat: 
![image](https://user-images.githubusercontent.com/18663291/76322223-6a600f80-62e3-11ea-9c92-dc90d16af64b.png)

OPAC:
![image](https://user-images.githubusercontent.com/18663291/76322334-8e235580-62e3-11ea-9013-7594be1d71c6.png)

(Da stimmt sowieso etwas in der Darstellung nicht)
MARCXML: 
![image](https://user-images.githubusercontent.com/18663291/76322392-9f6c6200-62e3-11ea-9072-658658ec6846.png)
In diesem Fall ist die (unsichtbare) A/I-Nummer such- und auffindbar.

Können alle 510-Felder angezeigt werden?

**Comment by BernLutz** [comment]
Die Inhalte aus Feld 510 werden nun korrekt angezeigt: https://opac.rism.info/search?id=993104538&View=rism
