### ISSUE TITLE
Englische Begriffe/Überschriften/Termini

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#298]
Sammelticket

**Erweiterte Suche**
1. Feldbezeichnung  "Wasserzeichen" bitte ändern in:
Watermark
![image](https://user-images.githubusercontent.com/18663291/76437366-c1d0af00-63b9-11ea-9933-6d60158492d6.png)

**In der Trefferliste**
1. Da wir auch auf andere Quellen verlinken, z.B. Libretti, soll der Filter nicht "Digitized music" heißen sondern "Digitized source".
![image](https://user-images.githubusercontent.com/18663291/76425834-79f65b80-63aa-11ea-9b37-24385240040b.png)

2. In der Trefferliste hat man direkt unterhalb der Trefferzahl die Möglichkeit, alle angezeigten Titeln auszuwählen. Auf Englisch heißt es "Select titles". Bitte ändern in:
Select records
![image](https://user-images.githubusercontent.com/18663291/76425887-8a0e3b00-63aa-11ea-9496-82a6f409355a.png)

3.  Filter "Authority data":
![image](https://user-images.githubusercontent.com/18663291/76437181-774f3280-63b9-11ea-8c10-9865eb9052d8.png)
"Authority data"  Bitte ändern in: Indexes
Außerdem:
Persons --> Personal names
Organisations --> Institutions
Literature --> Secondary literature

**Vollanzeige**
1. Unten rechts in irgend einem Titel beim Feedback-Button: Mit Mouseover wird folgender Text angezeigt: Your message on the title
![image](https://user-images.githubusercontent.com/18663291/76426083-db1e2f00-63aa-11ea-8606-6f565b80912b.png)
Bitte ändern in:
Send a comment about this record

2. In der Vollanzeige, z.B. https://opac.rism.info/search?id=858000171&View=rism , unten, wird einen Link zu "Show MarcXML" angezeigt: 
![image](https://user-images.githubusercontent.com/18663291/76436431-808bcf80-63b8-11ea-933b-95ab6357ee4b.png)
Bitte ändern in: 
Show MARCXML

**Literatur**
1. In der Literaturanzeige sind einige englischen Begriffe falsch.
Beispiele: https://opac.rism.info/search?id=lit552&View=rism
https://opac.rism.info/search?id=lit761&View=rism (Serie)
https://opac.rism.info/search?id=lit41001273&View=rism (Zeitschrift)
Falsch-->Bitte ändern in
Place-->City
Pages-->Pages/volume
Short title--> Part of
Lexica --> Secondary literature

**Normdaten**
In den Normdaten auf Englisch steht der Hinweis:
Get titles containing this id
Bitte ändern in: 
All records linked to this index term
![image](https://user-images.githubusercontent.com/18663291/76435981-f9d6f280-63b7-11ea-9d35-97a2d8ed725d.png)

(Alte Tickets: #165 #142 #121 #120  #35 #116 #36)

**Comment by BernLutz** [comment]
Ein Teil der Änderungen wurde im Release vom 29.6.2020 umgesetzt; für die Bereiche "Literatur" und "Normdaten" wurden zwei separate Tickets erstellt.
https://github.com/rism-international/opac-report/issues/310
https://github.com/rism-international/opac-report/issues/311
