### ISSUE TITLE
Abschaltung der Bildanreicherung für Personen (Normdaten)

### ISSUE THREAD

**Issue by BernLutz** [rism-international/opac-report#299]
Die Bildanreicherung für Personen über Wikimedia Commons soll in den Normdaten abgeschaltet werden, da:
a) eine ausreichende Qualität durch eine automatisierte Einspielung nicht gewährleistet werden kann
b) eine redaktionelle Prüfung der Daten nicht geleistet werden kann

**Comment by KlausKeil** [comment]
Danke Herr Lutz.
Ich schicke das weiter an Herrn Pietschmann
Beste Grüße Klaus Keil

Am Mo., 30. März 2020 um 13:06 Uhr schrieb BernLutz <
notifications@github.com>:

**Comment by BernLutz** [comment]
Die Bildanreicherung für Personen über Wikimedia Commons wurde deaktiviert.
