### ISSUE TITLE
Incipit-Anzeige

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#3]
Incipits werden teilweise nicht direkt aufgebaut und erst nach einer Aktualisierung angezeigt.

**Comment by alexandermarxen** [comment]
Unter welchen Umständen der Fehler auftritt ist nicht erkennbar, er wurde aber auch schon von Nutzern gemeldet: https://twitter.com/MusikschaetzeDD/status/1034696782322847744

**Comment by jenniferward** [comment]
Aktuelles Beispiel:
https://opac.rism.info/search?id=464110015&View=rism

In Firefox:
![image](https://user-images.githubusercontent.com/18663291/47648115-534ed080-db79-11e8-9c5d-369f8a4161fd.png)

In Chrome und Opera sieht man folgendes:
![image](https://user-images.githubusercontent.com/18663291/47648201-9c9f2000-db79-11e8-8882-1191bbb4f4c2.png)

Vorgang: 
1. Ich habe Firefox geöffnet
2. opac.rism.info aufgerufen
3. 464110015 in der Einfachen Suche eingegeben
4. Auf Enter geklickt
5. Da es nur einen Treffer gab, wurde die Trefferliste übersprungen und Datensatz 464110015 direkt angezeigt. Die Incipits waren wie oben abgebildet.

Es fiel mir auf, dass ich dabei opac.rism.info zum ersten Mal in meiner Browser-Session offen hatte.

Meine Theorie: Die Incipits werden nicht angezeigt, wenn ein Datensatz "direkt" abgerufen wird (sei es über den Permalink oder über die Suche, wo es nur 1 Ergebnis gibt), wenn mann zum ersten Mal in der Browser-Session opac.rism.info abruft und keine "Zwischenseite" aufgebaut wurde.

Ich konnte dies bestätigen, in dem ich Schritte 1-5 wiederholt habe und nach  456000203 gesucht habe. Das Ergebnis war wie in Schritt 5.

Als Gegencheck habe ich Schritte 1 und 2 wiederholt und Caldara in der Einfachen Suche eingegeben. Dann sah ich eine Trefferliste und habe auf den 5. Titel geklickt (wo ich weiß, dass sich 456000203 dahinter steckt). Die Incipits waren sichtbar, vermutlich, weil es diese Trefferliste inzwischen gab.

**Comment by jenniferward** [comment]
Heute hat dieses Problem eine Nutzerin verwirrt.

**Comment by BernLutz** [comment]
Das Phänomen tritt nicht mehr auf.

**Comment by jenniferward** [comment]
Heute ist dieses Problem aufgetreten.
https://opac.rism.info/search?id=464110015&View=rism
Firefox:
![image](https://user-images.githubusercontent.com/18663291/74664539-33905100-519e-11ea-8fe6-14a9e5b6665c.png)

Erst beim F5-Drucken werden die Incipits angezeigt.

**Comment by jenniferward** [comment]
Auch heute in Chrome
https://opac.rism.info/search?id=467012500&View=rism

![image](https://user-images.githubusercontent.com/18663291/75012628-b1947680-5482-11ea-896c-edf620697874.png)

**Comment by BernLutz** [comment]
Unsere IT konnte das Problem nun beheben. Bei meinen Tests wurden die Incipits korrekt angezeigt. Möchten Sie die Anzeige vielleicht auch noch einmal kurz überprüfen und das Ticket dann ggf. schließen, @jenniferward @alexandermarxen ?

**Comment by jenniferward** [comment]
Bei mir sieht es korrekt aus.

**Comment by alexandermarxen** [comment]
Bei mir auch! Vielen Dank! Ich schließe das Ticket.
