### ISSUE TITLE
Vorsatz bei Performances

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#30]
Feld 518 enthält bei Aufführungsdaten den Vorsatz “Performance date: “
Die Anforderung ist anscheinend nicht umgesetzt; bzw. habe keinen Titel Beispiel mit diesem Vorsatz gefunden

**Comment by BernLutz** [comment]
Der Vorsatz "Performance date: " ist im OPAC sichtbar, z.B. https://opac.rism.info/search?id=530010166&View=rism
