### ISSUE TITLE
Darstellung von Umlauten im Feld 700

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#300]
Umlaute bei Personen werden teilweise nicht richtig dargestellt. Mein erster Eindruck ist, dass dies nur in Feld 700 der Fall ist, nicht aber in Feld 100:

Beispiele
https://opac.rism.info/search?id=454016894&View=rism
https://opac.rism.info/search?id=552002068&View=rism
https://opac.rism.info/search?id=456005331&View=rism

**Comment by BernLutz** [comment]
Die Umlaute werden wieder korrekt aufgelöst.
