### ISSUE TITLE
Falsche Darstellung von Umlauten im Feld 043 $c (Personen)

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#301]
Das Länderkürzel XA-AT wird im OPAC im Feld 043 $c (Personen) in "Ãsterreich" umgesetzt.
Beispiel: https://opac.rism.info/search?id=pe20001768&View=rism
@HirschSt Liefern wir eine Tabelle für die Umsetzung der Kürzel?

**Comment by BernLutz** [comment]
Vielen Dank für die Meldung @alexandermarxen, das Problem ist behoben.
