### ISSUE TITLE
Auswertung von Feld 594 und 240$m für die Erweiterte Suche (Besetzung)

### ISSUE THREAD

**Issue by BernLutz** [rism-international/opac-report#303]
Für die Erweiterte Suche (Besetzung) soll Feld 594 und 240$m ausgewertet werden:
Soll die Einbindung von 594 nur das Subfield $b betreffen @alexandermarxen ?

**Comment by alexandermarxen** [comment]
Ja, ich denke die Suche nach der Anzahl ist in diesem Feld nicht so sinnvoll.
