### ISSUE TITLE
Bezeichnung des Filters "Besetzung" in "Instrument/Stimmlage" ändern

### ISSUE THREAD

**Issue by BernLutz** [rism-international/opac-report#304]
Der Suchfilter "Besetzung" in der Erweiterten Suche soll zukünftig mit dem Ausdruck "Instrument/Stimmlage" bezeichnet werden.

Soll die Bezeichnung auch für den Facettenfilter am linken Menürand übernommen werden @alexandermarxen ?

Für IT/ES/FR und EN bräuchten wir dann noch die gewünschten Vorgaben @MFalletta @jenniferward 
Vielen Dank!

**Comment by alexandermarxen** [comment]
Die Änderung des Begriffes bezog sich nur auf die Erweiterte Suche, da hier nur nach Instrumenten gesucht wird, der Filter sollte weiterhin Besetzung (oder Besetzungshinweis?) heißen.

**Comment by alexandermarxen** [comment]
Nach Rücksprache mit den KollegInnen haben wir uns entschieden, den Begriff "Besetzung" auch für die Erweiterte Suche zu behalten. Durch das Fenster mit der Abkürzungsliste, das bei der Auswahl von "Besetzung" erscheint, ist dem Nutzer (hoffentlich) klar, was er an dieser Stelle eingeben kann.
