### ISSUE TITLE
Feld 852$b bei den Exemplaren (Drucken) umbenennen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#305]
Bei den Drucken-- Exemplaren:
852$b soll heißen:
DE: Abteilung
EN: Department
IT: Dipartimento
FR: Section
ES: Departamento

Momentan wird das Feld as  "Bibliothek (Sigel):" angezeigt. Kann das geändert werden? Das ist uns bisher entgangen.

Beispiel: Erster Eintrag unter 
https://opac.rism.info/search?id=990034717&View=rism

![image](https://user-images.githubusercontent.com/18663291/82889059-79ea0e80-9f4a-11ea-9f53-7c36daaf6324.png)

**Comment by BernLutz** [comment]
Danke für den Hinweis @jenniferward . Ich habe den Punkt in unser Ticket-System übertragen.

**Comment by jenniferward** [comment]
Super, danke!
