### ISSUE TITLE
Lange diplomatische Titel werden auf kleineren Bildschirmen mit - aufgespalten

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#306]
Beispiel: https://opac.rism.info/search?id=993104602&View=rism

hier sollte statt mit Bindestrich mit Whitespace umgebrochen werden

**Comment by BernLutz** [comment]
Der Trennung durch einen Bindestrich ist im diplomatischen Titel tatsächlich sehr irreführend. Ich nehme den Punkt in unser Ticket-System auf.
Vielen Dank für den Hinweis @HirschSt !
