### ISSUE TITLE
Materialbezeichnungen in 593 sind teilweise umbenannt:

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#31]
autograph => Autograph manuscript >>> in Titelanzeige umgesetzt
partly autograph => Partial autograph  >>> in Titelanzeige nicht umgesetzt
manuscript => Manuscript copy >>> in Titelanzeige nicht umgesetzt
probably autograph => Possible autograph manuscript >>> umgesetzt in Possible autograph

Das Autocomplete in der Suche gibt auch noch die alten Begriffe vor.

**Comment by KlausKeil** [comment]
Ist das Autocomplete sprachabhängig?

**Comment by jenniferward** [comment]
Nein, wenn ich auf Englisch suche und "aut" eingebe, wird auch "fraglisches autograph"angezeigt.
