### ISSUE TITLE
Suche nach Besetzung findet nicht alle Treffer

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#313]
In der Erweiterten Suche suche ich nach Besetzung = vlne.
Ich bekomme 1.043 Ergebnisse, aber Komponist Lechler ist nicht dabei. Er soll aber gefunden werden, z.B. 600176969. 
Wenn ich aber nach Besetzung = vlne, (also mit Komma!) suche, dann werden die gesuchten Titel von Lechler gefunden, und außerdem bekomme ich 2366 Ergebnisse.

Kann es sein, dass das Komma als Teil des Suchbegriffes gesehen wird?

**Comment by BernLutz** [comment]
Danke für die Meldung @jenniferward , das Problem ist nun behoben.
