### ISSUE TITLE
Blank zwischen Bemerkungen in den Exemplaren

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#315]
Beispiel https://opac.rism.info/search?id=990051014&View=rism, Exemplar US-IO
Es gibt mehrere 563$a und 500$a. Können sie durch ein Blank getrennt werden?

![image](https://user-images.githubusercontent.com/18663291/86806527-3f12e480-c079-11ea-82a2-387fb5ef9735.png)

![image](https://user-images.githubusercontent.com/18663291/86806581-4a661000-c079-11ea-87d8-185ee890af27.png)

**Comment by jenniferward** [comment]
Die Trennung bei 500$a funktioniert in den meisten Fällen bestimmt schon korrekt, aber irgendwie nicht bei diesem Titel. Der Titel hat 4x 500$a:
![image](https://user-images.githubusercontent.com/18663291/86915933-16472980-c123-11ea-9e94-11906eeb3849.png)

aber im OPAC werden die ersten zwei Bemerkungen ohne Trennung angezeigt: severely.Inscribed

Kann es sein, dass die ersten zwei Fälle von 500$a zusammengeschrieben werden, alles andere getrennt?
Weiteres Beispiel: 
https://opac.rism.info/search?id=990046739&View=rism Exemplar D-LEu
![image](https://user-images.githubusercontent.com/18663291/86916158-7342df80-c123-11ea-808f-dc1218e86c3a.png)

![image](https://user-images.githubusercontent.com/18663291/86916202-89e93680-c123-11ea-97ca-d9c09843b992.png)

**Comment by BernLutz** [comment]
Danke für den Hinweis @jenniferward
Die Inhalte werden nun getrennt angezeigt.
