### ISSUE TITLE
Literatur fehlt in den Exemplaren

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#317]
Beispiel: https://opac.rism.info/search?id=990051014&View=rism, Exemplar US-IO
Der Literaturhinweis KimberA 2020 wurde geliefert 
![image](https://user-images.githubusercontent.com/18663291/86807338-0f181100-c07a-11ea-932f-acbc0eae0305.png)

aber wird nicht angezeigt.

**Comment by BernLutz** [comment]
Vielen Dank für die Meldung @jenniferward. 
Die Literatur wird nun angezeigt. Wir prüfen auch noch die Verlinkung zum Normdatensatz.
