### ISSUE TITLE
Probleme bei der Datierung

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#321]
Ich habe gerade nach nach Datierung gesucht und im Filter wurden ca. 73 Treffer angezeigt (unmöglich für meine Suche), jetzt sehe ich es richtig (3). Kann es sein, dass der OPAC in dieser Zeit indexiert wurde? Falls ja, kann ein kurzer Hinweis in der Trefferliste angezeigt werden? Es verunsichert die Nutzer, glaube ich, wenn die Treffer keinen Sinn ergeben und der OPAC instabil wirkt.

**Comment by BernLutz** [comment]
Vielen Dank für die Meldung @jenniferward. Die letzte Indexierung ist schon einige Zeit abgeschlossen. Diese dürfte eigentlich auch keine Auswirkung für den Nutzer haben. Ich kann den Fehler leider nicht reproduzieren, beobachte diesen Punkt aber gerne in der nächsten Zeit. Könnten Sie mir schreiben, falls Ihnen das Problem erneut auffallen sollte? Schon einmal vielen Dank!

**Comment by jenniferward** [comment]
Alles klar, danke! Dann liegt es nicht an der Indexierung. Vielleicht habe ich nur ein Problem mit dem Filter Datierung.

Gerade tauchte das Problem wieder auf.
Suche nach * [nichts]
Filter Komponist: Haydn, Joseph
14.700 Ergebnisse.

Filter Datierung:
![image](https://user-images.githubusercontent.com/18663291/88284172-3ebb5000-cced-11ea-8207-48b81dc08cbc.png)
136.000 Quellen vor 1774, das ist schon extrem, oder? Auch wenn es mehrere Materialgruppen gibt?
Ich wollte eigentlich die modernere Quellen, also nach 1925. Man würde 27.000 Ergebnisse erwarten. Wenn mann darauf klickt, finde ich (erwartungsgemäß) nur 25:
![image](https://user-images.githubusercontent.com/18663291/88284388-9d80c980-cced-11ea-9dba-0586c1c10c6d.png)

Ich habe die Suche auch anders gemacht:
Einfache Suche nach: Haydn
Filter Komponist: Haydn, Joseph 
Jetzt "nur" 205 Quellen nach 1925:
![image](https://user-images.githubusercontent.com/18663291/88284729-31529580-ccee-11ea-8e61-1ef8d305a75d.png)
Ich kann den Unterschied nicht erklären, und außerdem ich verstehe auch nicht, wie der OPAC auf die Zahl 205 bei nur 25 Quellen kommt.

Auch auf der Trefferliste mit 25 Quellen sehe ich nicht, wie der OPAC weitere 4380 Quellen vor 1849 findet.
![image](https://user-images.githubusercontent.com/18663291/88285153-e84f1100-ccee-11ea-9622-7d51d6ab06cf.png)

Wie kann man am besten diesen Filter benutzen?

(Gerade gesehen, es gib schon ein Ticket zum Thema Datierung: #153)

**Comment by BernLutz** [comment]
Vielen Dank für das Beispiel @jenniferward.  Wir werden uns diesen Punkt noch einmal im Kontext von #153 ansehen.

**Comment by BernLutz** [comment]
Die Angabe in den Datierungsfiltern entspricht nun der Treffermenge.
