### ISSUE TITLE
Schlüssel abgeschnitten

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#322]
https://opac.rism.info/search?id=1001100318&View=rism 
Auf meinem Bildschirm (Firefox und Chrome) ist der Schlüssel in 1.2.1 abgeschnitten
![image](https://user-images.githubusercontent.com/18663291/89549344-7c010100-d808-11ea-9d09-1929f32b41c0.png)

**Comment by BernLutz** [comment]
Vielen Dank für den Hinweis @jenniferward
Ich habe ein entsprechendes Ticket aufgesetzt. Auch in Muscat wird der Schlüssel übrigens abgeschnitten:
![grafik](https://user-images.githubusercontent.com/44613113/89612909-477d5b80-d881-11ea-85c7-fd0f91f748c4.png)
In Verovio selbst ist die Anzeige korrekt:
![grafik](https://user-images.githubusercontent.com/44613113/89612932-5cf28580-d881-11ea-9d87-a33cb4d99ab7.png)
