### ISSUE TITLE
Literatur fehlt - Druck und Exemplar

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#323]
Die 2. und 3. Literatur und fehlen hier im Exemplareintrag
https://opac.rism.info/search?id=1001100274&View=rism

![image](https://user-images.githubusercontent.com/18663291/89550042-6b04bf80-d809-11ea-86e2-90d8024c28ec.png) 

und im Druckeintrag fehlen die 2 Literaturhinweise komplett. 
![image](https://user-images.githubusercontent.com/18663291/89550298-c040d100-d809-11ea-8347-3efec0870a58.png)

Die MARC-Datei scheint OK zu sein.
![image](https://user-images.githubusercontent.com/18663291/89550167-95ef1380-d809-11ea-9e20-029dbb36918f.png)

Siehe auch #317

**Comment by BernLutz** [comment]
Vielen Dank für die Meldung des Problems @jenniferward 
Wir aktualisieren die Anzeige aller Felder mit einer potentiell multiplen Anzeige. Wenn die Anpassung produktiv ist, sollten auch alle Literaturhinweise wieder komplett angezeigt werden.

Dies betrifft z.B. auch #320 #316 #297

**Comment by jenniferward** [comment]
Vielleicht relevant? 
In diesem Titel https://opac.rism.info/search?id=200021144&View=rism wird das Feld "Komponistenquerverweis" angezeigt aber ohne Namen:
![image](https://user-images.githubusercontent.com/18663291/98003476-144e5800-1def-11eb-9371-cb77e4bea895.png)

Angezeigt werden soll Johann Sebastian Bach:
![image](https://user-images.githubusercontent.com/18663291/98003694-524b7c00-1def-11eb-923b-5f8c07cb6fa4.png)

Bach als Vorbesitzer fehlt überigens auch komplett.

**Comment by BernLutz** [comment]
Die Literatur wird nun im Exemplar angezeigt, darum schließe ich das Ticket. Den zweiten Teil der Anforderung - die fehlende Anzeige von Personen aus Feld 700 - habe ich in ein neues Issue #336  kopiert. Ist dies in Ihrem Sinne @jenniferward ?

**Comment by jenniferward** [comment]
Ja, völlig richtig, vielen Dank!
