### ISSUE TITLE
Link "Suchergebnisse für diese ID" bei Nicht-Komponisten

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#324]
Beispiel: Ludwig II.
https://opac.rism.info/search?id=pe168096&View=rism

Mit dem Link https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe168096%22 würde ich erwarten, die ca. 60 Titel mit ihm als Vorbesitzer oder Widmungsträger zu finden. Stattdessen bleibe ich auf derselbe Seite.
Hängt es damit zusammen, dass er kein Komponist ist?
Es wäre schön, auch seine Titel zu finden.

Siehe auch #176

**Comment by BernLutz** [comment]
Aktuell wird nur Feld 100 durchsucht. Wir können die Suche über die ID in den Normdaten der Personen auch auf Feld 700 (Nebeneintragung Personen) und - analog dazu - für die KS-Sätze auf 710 (Nebeneintragung Körperschaften) ausweiten. Wäre diese Lösung in Ihrem Sinne @jenniferward ?

**Comment by jenniferward** [comment]
Ja, das wäre schön. Meiner Meinung nach soll man alle Titel für die Person finden.

Es ist den Nutzern nicht klar, dass "Suchergebnisse für diese ID" nur für Komponisten gilt.

**Comment by alexandermarxen** [comment]
Ich fände das auch sehr gut. Eine spätere Einschränkung der Suche über den Suchfilter Komponisten gäbe ja auch die Möglichkeit, nur die Quellen herauszufiltern, in denen die Person Komponist ist.

**Comment by BernLutz** [comment]
Besten Dank für die Rückmeldung @jenniferward und @alexandermarxen ! Dann setze ich den Punkt auf unsere To-do-Liste.

**Comment by alexandermarxen** [comment]
Wir haben zu diesem Thema noch einen Nutzerhinweis bekommen: Diese Links werden auch von externen Projekten genutzt. Daher wäre es wichtig, auch das Feld 700 zu berücksichtigen.

**Comment by alexandermarxen** [comment]
Inzwischen verlinkt auch Wikipedia über die Personen-IDs zu RISM. Auf der englischen Seite sind es schon über 10.000 Artikel! https://en.wikipedia.org/w/index.php?title=Category:Wikipedia_articles_with_RISM_identifiers Da Feld 700 nicht berücksichtigt wird führen diese Links (wenn es sich nicht um Komponisten handelt) leider nur zum Personen-Datensatz. Da "Suchergebnisse für diese ID" in diesem Fall nicht zu den Quellen führt, ist es leider eine Sackgasse.

**Comment by BernLutz** [comment]
Das Feld 700 wird nun für die Verlinkung aus den PE-Datensätzen berücksichtigt.
