### ISSUE TITLE
Suche nach Textsprache

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#326]
Ich habe vor einigen Wochen (im Juli??) nach "Textsprache" in der Erweiterten Suche gesucht. Damals konnte ich "Ger...." oder auch "Deu..." eingeben und die Optionen wurden angezeigt. Ich habe es auch so im Hilfetext beschrieben. Jetzt geht das nicht mehr. Kann das wieder eingeführt werden? Es ist wirklich nicht intuitiv, wonach man suchen kann.

Außerdem scheint die Suche nicht mehr ganz zu funktionieren. (Siehe #7). "German" und "English" funktionieren, "Occitan" etwa nicht, hier muss man "oci" eingeben. Die Nutzer müssen wissen, wenn sie die Codes eingeben sollen, und wir müssten dann die 75 Sprachcodes zur Verfügung stellen.

**Comment by BernLutz** [comment]
Die Autocomplete ist für die Textsprachen wieder verfügbar. Möchten Sie dies kurz überprüfen und das Ticket dann ggf. schließen @jenniferward  ?  Vielen Dank!
Die Auflösung der Sprachcodes ist bei uns in einem gesonderten Ticket bereits erfasst und wir werden das Problem im Zuge von  #7 lösen.

**Comment by jenniferward** [comment]
Leider sehe ich keine Autocomplete, ich muss das ganze Wort ausschreiben.
Außerdem bekomme ich unterschiedliche Ergebnisse:
German: 225707 Ergebnisse
Deutsch: 225698 Ergebnisse

**Comment by BernLutz** [comment]
Vielen Dank für die Rückmeldung @jenniferward 
Ich habe die Autocomplete heute noch einmal mit verschiedenen Browsern (Edge, Safari, Firefox) getestet und dabei wurden die Sprachen korrekt angezeigt.
![grafik](https://user-images.githubusercontent.com/44613113/97533333-51ae8200-19b8-11eb-82bf-9c9b33cd056d.png)

Die Abweichungen in den Suchergebnissen resultieren offenbar aus einer uneinheitlichen Belegung in Feld 041$a. In einigen Fällen wurde hier nicht der Sprachcode (ger) erfasst, sondern wie in https://muscat.rism.info/admin/catalogues/41000085 (deutsch) oder https://muscat.rism.info/admin/catalogues/41002074 (German) eingetragen.

**Comment by jenniferward** [comment]
Ah, ich hab's! Im ersten Feld der Erweiterten Suche geht es nicht, im 2. und 3. Feld aber schon!
![image](https://user-images.githubusercontent.com/18663291/97548837-ef617b80-19cf-11eb-8270-345272646170.png)

Vielen Dank auch für den Hinweis wegen Sprachcode. Ich sehe, das hängt mit der Literatur zusammen. Ich kümmere mich darum. Danke!

**Comment by BernLutz** [comment]
Prima - vielen Dank! Ich denke, dass im ersten Feld die AC bewusst nicht aktiviert ist, da hier die Suchanfragen aus dem Cache angeboten werden. Ist das in dieser Form ok?

**Comment by jenniferward** [comment]
Hmmm, ich weiß es nicht - das ist für die Nutzer (wie mich ;) ) auf dem ersten Blick nicht offensichtlich. Ich dachte tatsächlich, es funktioniert nicht. Und manchmal glauben wir, die AC geht grundsätzlich nicht mehr (z.B. bei den Komponisten) aber im Nachhinein hing das vielleicht mit dem Feldauswahl zusammen.

Ich weiß, was Sie mit "die Suchanfragen aus dem Cache" meinen. Ich habe gerade nach Mozart gesucht und in der Erweiterten Suche erscheint der Name im ersten Feld.
![image](https://user-images.githubusercontent.com/18663291/97550786-6435b500-19d2-11eb-9070-c6107b3fb1ff.png)
Was würde passieren, wenn hier AC aktiviert wäre?

Andere Meinungen, @MFalletta @alexandermarxen ?

**Comment by BernLutz** [comment]
Ich setze bei Bedarf gerne ein Ticket an unsere IT auf, dann können sich die EntwicklerInnen die Sache einmal ansehen.

**Comment by MFalletta** [comment]
Ich verwende auch immer die oberste Suchmöglichkeit (+ weitere) und wäre nie auf die Idee gekommen, dass hier gar kein AC zur Verfügung steht.

**Comment by BernLutz** [comment]
Vielen Dank für die Rückmeldung, ich habe ein neues Ticket erstellt.

**Comment by jenniferward** [comment]
Folgende Sprachen auf Englisch finde ich nicht, wenn ich die AC benutze. Wissen Sie @BernLutz woran das liegt?

Swiss German. Ein Beispiel wäre https://opac.rism.info/search?id=410007819&View=rism
Aragonese https://opac.rism.info/search?id=806292706&View=rism
Low German https://opac.rism.info/search?id=1001004694&View=rism
Neapolitan https://opac.rism.info/search?id=850600065&View=rism



"Croatian" ist falsch geschrieben:
![image](https://user-images.githubusercontent.com/18663291/98273057-1e5c8c00-1f92-11eb-9999-62304ed84df7.png)

**Comment by BernLutz** [comment]
Vielen Dank für die Meldung @jenniferward ! Ich werde dieses Phänomen mit in unser Ticket  zu   #7 aufnehmen und Ihnen Bescheid geben, sobald wir eine Lösung gefunden haben.

**Comment by BernLutz** [comment]
Die AC ist nun auch für den ersten Sucheinstieg verfügbar. Die fehlenden Sprachen sind ebenfalls erfasst. Sobald diese in der Produktion verfügbar sind, werde ich dies in #7 kommentieren.
