### ISSUE TITLE
Filter: "Teilautograph" auch auf EN

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#329]
In den Filtern "Source type" wird "Teilautograph" auch mit der EN-Oberfläche angezeigt. 

![image](https://user-images.githubusercontent.com/18663291/95584758-82953a00-0a3e-11eb-89d3-baaeebfc344b.png)

Bitte ändern in: Partial autograph

**Comment by BernLutz** [comment]
Die Inhalte des Filters "Source type" wurden aktualisiert.
