### ISSUE TITLE
Suchfilter Personen kombiniert identische Namen

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#330]
Der Suchfilter "Personen" kombiniert identische Namen, dadurch ist eine differenzierte Filterung nicht möglich.
Beispiel: Suche nach Puccini, Giacomo zeigt aktuell 281 Treffer an.
![image](https://user-images.githubusercontent.com/42838336/96418196-adc41a00-11f2-11eb-9de1-c49063b023ed.png)
Richtig wären zwei Einträge mit 117 bzw. 164 Treffern.

**Comment by BernLutz** [comment]
Hier müsste dann auch die Anzeige der Personen im Filter angepasst werden. Wenn 2 x "Puccini, Giacomo" erscheint, bleibt eine Zuordnung schwierig.
Eine Option wäre es, die Lebenszeiten an den Namen anzuhängen (100$a + 100$d): "Puccini, Giacomo <1858-1924>" oder "Puccini, Giacomo <1712-1781>"  (s. https://opac.rism.info/id/rismid/850815634?format=marc und https://opac.rism.info/id/rismid/850641449?format=marc )
Wäre eine Anpassung in dieser Form auch in Ihrem Sinne @alexandermarxen ?

**Comment by alexandermarxen** [comment]
Ja, das wäre optimal! Herzlichen Dank!
Ich wäre (nicht nur in diesem Fall, sondern auch allgemein) für runde statt spitze Klammern für die Lebensdaten.
Vielleicht müsste man beim Suchfilter dann noch ein Trennzeichen (z.B. - ) einfügen, damit keine Verwirrung entsteht, da die Anzahl ja auch in runden Klammern steht.

**Comment by BernLutz** [comment]
Vielen Dank für die schnelle Rückmeldung @alexandermarxen!
Ich gebe dies so an unsere EntwicklerInnen weiter.

**Comment by BernLutz** [comment]
Gleichnamige Personeneinträge werden nun im Filter berücksichtigt.
