### ISSUE TITLE
Löschung von 031$u

### ISSUE THREAD

**Issue by HirschSt** [rism-international/opac-report#331]
Zur Information:

Für die Verlinkung umfangreicher "extended" Musikincipits werden bisher vorhandene Werte in Feld 031$u gelöscht, in dieses Feld werden zukünftig Links zu Digitalen Objekten abgelegt. 

Vor einigen Jahren benötigte die BSB dieses Feld für die Verlinkung lokaler Incipitgrafiken mit einem Titel; allerdings sind diese Werte mit der Umstellung auf Verovio beim RISM-OPAC jetzt überflüssig.

Beispiel: https://muscat.rism.info/admin/sources/1001128394 bzw. https://opac.rism.info/search?id=1001128394&View=rism, in den Lieferungsdaten ist kein 031$u mehr vorhanden, das Incipit wird trotzdem gerendert.

@BernLutz könnten Sie bitte kurz bestätigen, dass wir das Subfield 031$u aus den vorhandenen Daten löschen können?

**Comment by BernLutz** [comment]
In diesem Fall werden die IDs in 031$u von uns nicht mehr benötigt. Wichtig wäre für uns aber die Information, unter welchem Label das Subfield in den verschiedenen RISM-Sprachen zukünftig angezeigt werden soll.
Könnten Sie uns hierzu auf dem Laufenden halten? Schon einmal vielen Dank!

**Comment by HirschSt** [comment]
Prima, danke! Die Einbindung von "extended incipits" über 031$u steht noch in den Anfängen, wir möchten zunächst das bereits bestehende Feld nutzen. Natürlich werde ich über den weiteren Verlauf berichten, wir werden als nächstes - nachdem die bestehenden 031$u gelöscht sind - in Muscat bei einigen Titeln das Feld neu mit einer URL belegen.
