### ISSUE TITLE
"Literatur" ohne Nachweis

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#332]
Im Moment sehe ich Exemplareinträge mit Platzhaltern für Literaturhinweise, aber in der Tat gibt es keine Literaturhinweise zu diesen Exemplaren.
https://opac.rism.info/search?id=990063265&View=rism
![image](https://user-images.githubusercontent.com/18663291/96577713-51392b80-12d4-11eb-8390-b9bced203cf1.png)

**Comment by BernLutz** [comment]
Das Label "Literatur" wurde für alle nicht-belegten Felder entfernt.
