### ISSUE TITLE
Incipits werden nicht angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#334]
Hat vielleicht mit #3 zu tun, ist aber etwas anders:

Jetzt werden die Musikincipits überhaupt nicht angezeigt.

Chrome
![image](https://user-images.githubusercontent.com/18663291/98776944-3304ae00-23f0-11eb-8a79-8a4935535466.png)
https://opac.rism.info/search?id=850816067&View=rism

Beim Klicken auf F5 werden die Incipits (anders als in #3) nicht angezeigt.

(Heute von einem Nutzer gemeldet.)

**Comment by BernLutz** [comment]
Haben Sie vielen Dank für die Meldung @jenniferward 
Ich habe unsere IT über das Problem informiert und hoffe auf eine schnelle Lösung.

**Comment by BernLutz** [comment]
Die Incipits werden nun wieder angezeigt. Nochmals besten Dank für den Hinweis @jenniferward
