### ISSUE TITLE
Literatursuche fehlerhaft, unvollständig

### ISSUE THREAD

**Issue by MFalletta** [rism-international/opac-report#338]
Die einfache Suche nach dem Literaturkürzel "GroßeBoymannR 2005" führt zu 2 Treffern (1x Quelle, 1x Normdatensatz).
Nur die konkrete Suche nach dem Datensatz "lit30027920" führt zu allen Ergebnissen.

**Comment by BernLutz** [comment]
Die einfache Suche berücksichtigt nun das Literaturkürzel.
