### ISSUE TITLE
Geänderte Struktur bei Collections

### ISSUE THREAD

**Issue by KlausKeil** [rism-international/opac-report#34]
Bei Sammelhandschriften ist der Tag 100 (als Komponist bisher “Collection”) nicht mehr vorhanden, sondern wird durch Tag 130 ersetzt, welches statt 240 den UniformTitle anzeig
Ist nicht erledigt: in MarcXML st noch 100 Collection. 
https://opac.rism.info/search?id=455030112&View=rism

**Comment by BernLutz** [comment]
Wurde beim Umstieg auf das Muscat-Marc berücksichtigt.
