### ISSUE TITLE
852$b veröffentlichen 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#340]
https://opac.rism.info/search?id=410001695&View=rism
852$b (Abteilung) wird geliefert aber nicht angezeigt - bei den Handschriften zumindest. Ich glaube, das ist ein nützlicher Hinweis für die Nutzer. Kann das Feld veröffentlicht werden?

**Comment by BernLutz** [comment]
852$b wird nun vor der Signatur angezeigt.  Möchten Sie die Anpassung kurz prüfen und das Ticket dann ggf. schließen @jenniferward ? Vielen Dank!

**Comment by jenniferward** [comment]
Danke! Ich überlasse es hiermit @Docudoctor - vielleicht hat er einen Kommentar oder evtl. hängt das mit anderen Institutions-Tickets zusammen.
