### ISSUE TITLE
856 wird auf bibliographischer Ebene nicht angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#344]
Links, die im Feld 856 auf bibliographischer Ebene (nicht Exemplarebene) eingegeben werden, werden geliefert aber nicht angezeigt. Bitte publizieren.
Beispiele:

https://opac.rism.info/search?id=990036116&View=rism
https://opac.rism.info/search?id=240019&View=rism

**Comment by BernLutz** [comment]
Die Links werden jetzt auf bibliographischer Ebene angezeigt @jenniferward
