### ISSUE TITLE
Umbenennung Feld "Plattennummer"

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#345]
Unser Feld Plattennummer (028) wurde erweitert und Verlagsnummern sind auch mit dabei. Eine  technische Anpassung ist nicht notwendig. Beide Nummern werden mitgesucht.

Können wir die Bezeichnung des Feldes ändern?

Beispiel:
https://opac.rism.info/search?id=990021811&View=rism

Feld:
EN: Publisher or plate number
ES: Número de la editorial o de la plancha

Auch hier, falls möglich?
![image](https://user-images.githubusercontent.com/18663291/136242867-2916397f-93a0-4669-b275-9f32675daee9.png)

Man könnte vielleicht verkürzen:
Publisher/plate number
Número de la editorial/plancha

(cc @MFalletta OPAC-Hilfetext anpassen)

**Comment by BaMikusi** [comment]
Eine ganz kleine Bemerkung: Insbesondere in der drop-down Liste von Suchoptionen könnten "Publisher" und "Publisher or plate number" nebeneinander stehend ggf. Verwirrung stiften. Die Alternative "Publisher/plate number" dürfte das Problem nicht lösen, "Plate/publisher number" aber vielleicht schon?
(NB: In diesem Sinne denke ich, dass die Variante "Plate or publisher number" vielleicht auch im allgemeinen eindeutiger wäre.)

**Comment by BernLutz** [comment]
Anhand dieses Musters könnte die Feld- und Filterbezeichnung folgend aussehen:

DE: Platten- oder Verlagsnummer
EN: Plate or publisher number
IT: Numero della lastra o dell'editore 
FR: Numéro de plaque ou d'éditeur 
ES: Número de la plancha o de la editorial

Wäre dies im Sinne der ZR @jenniferward @BaMikusi ?

**Comment by jenniferward** [comment]
Das sieht gut aus, danke.

**Comment by jenniferward** [comment]
Wurde die Umbenennung zurrückgesetzt? Heute sehe ich nur "Plattennummer" als Feld- und Filterbezeichnung:
https://opac.rism.info/search?id=1001098603&View=rism
![image](https://user-images.githubusercontent.com/18663291/165290502-11315de3-cad9-4036-ab33-dca4044a1592.png)

![image](https://user-images.githubusercontent.com/18663291/165290515-5ba84a96-c7ea-485e-adfb-04a5953660a9.png)
