### ISSUE TITLE
Feld 787 anpassen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#346]
Wir haben das Feld 787 umgestaltet. Können die Daten wie folgt angepasst werden?

Beispiel: https://opac.rism.info/search?id=243182&View=rism

Vorschlag: EN-ES
787$4: [Anzeige:] Related source: / Fuente relacionada 
[Feldinhalt: Eins von folgendem:] 
[P60198] = Additional material / Material adicional
[P60242] = Arrangement of  / Arreglo de
[P60311] = Copied from  / Copiado de
[P60191] = Correlated source  / Fuente relacionada
[P60194] = Insert in  / Inserción en
[P60195] = Published in   / Publicado en

787$w: RISM ID number:  / Número de ID de RISM [ID wird angezeigt und verlinkt]
787$n: Note on related source:  / Nota

**Comment by BernLutz** [comment]
![Verwandte Quellen](https://user-images.githubusercontent.com/44613113/142396076-3de383a1-2959-4380-ada8-7cc52b772f4f.jpg)
Wäre eine Anzeige von 787 in dieser Form in Ihrem Sinne @jenniferward ?
