### ISSUE TITLE
Anzeige innerhalb von "Merkliste"

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#349]
Wenn ich einen Titel von der Merkliste aus anschaue, bin ich anscheinend (??) nicht mehr komplett im RISM-OPAC. Das Logo der BSB wird im Tab angezeigt und die Anzeige der Drucken ist eine alte.

1. Irgend einen Titel anklicken: https://opac.rism.info/search?id=990039139&View=rism
2. Dann auf "Diesen Titel speichern" klicken und in Merkliste speichern
![image](https://user-images.githubusercontent.com/18663291/139841664-c2d1f191-73ae-4ee6-91eb-fe06db3b1d01.png)
3. Dann zu Merkliste gehen und zum Dokument
4. Der Tab hat nun das Logo der BSB: 
![image](https://user-images.githubusercontent.com/18663291/139841845-7dfcb214-3ead-4568-82ae-f4ced0db8e74.png)
5. Bei den Drucken erscheinen die Exemplarinfo an zwei Stellen, 1x wie normal und 1x wie in der alten Version.
![image](https://user-images.githubusercontent.com/18663291/139841945-c6b6570d-9683-48e0-a991-a9b8f7de1ff3.png)

**Comment by BernLutz** [comment]
Vielen Dank für den Hinweis @jenniferward , das Problem wurde behoben.
