### ISSUE TITLE
Suche nach Textsprache

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#355]
Siehe #7

Einige Sprachen fehlen im Autocomplete in der Erweiterten Suche. Hat es damit zu tun, dass sie für uns relativ neu sind (Ende 2020)? 
Beispiel: https://opac.rism.info/search?id=100500163&View=rism scheint nur über crp suchbar zu sein, nicht "Creoles and Pidgins (Other)". Aber die Anzeige ist korrekt.
Oder wie können wir das abgleichen/überprüfen?

Ergänzung: bei https://opac.rism.info/search?id=410002283&View=rism wird nur "bos" angezeigt, nicht Bosnian.

**Comment by BernLutz** [comment]
Die Sprachen werden nun korrekt angezeigt und auch für die AC berücksichtigt.
