### ISSUE TITLE
Anzeige der hochgestellten Zeichen nach einem Pipesymbol

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#357]
Im Feld 245 werden die Zeichen nach einem Pipesymbol nicht hoch gestellt. Ich meine, sie sollen hochgestellt werden. 
https://opac.rism.info/search?id=991025326&View=rism
![image](https://user-images.githubusercontent.com/18663291/157669046-09115edf-ae45-4229-b5f3-6df919b0718a.png)

**Comment by BernLutz** [comment]
Die Elemente nach einem Pipesymbol werden nun auch in 245, 246 und 500 hochgestellt.
