### ISSUE TITLE
Keine RISM-IDs oder Permalinks in der mobile Version

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#359]
In der Vollanzeige auf meinem Handy fehlt sowohl RISM-ID als auch Permalink. Ohne ID kann man sich den Titel kaum merken; Permalink wäre auch gut aber vielleicht keine Priorität (ich weiß, dass die Handyversion weniger Features anbietet). Hat die Anzeige der "Last update" die ID vielleicht ersetzt?

Hier einen Screenshot, gespeichert als PDF:
[versteinern - RISM.pdf](https://github.com/rism-international/opac-report/files/8563878/versteinern.-.RISM.pdf)

**Comment by jenniferward** [comment]
ausprobiert mit:
- iPhone 8, Safari, alles aktualisiert
- Android 12, Chrome 100

**Comment by jenniferward** [comment]
Permalinks und RISM-IDs sehe ich nun mit dem iPhone. Danke @BernLutz !

**Comment by alexandermarxen** [comment]
Auch bei Android wird es angezeigt. Herzlichen Dank!
