### ISSUE TITLE
Anzeige 787

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#362]
Erst jetzt aufgefallen: Bei mehrfacher Feldbelegung vom 787 werden alle 787$w hintereinander aufgelistet, dann $4 und dann alle $n. 
https://opac.rism.info/search?id=806918368&View=rism

![image](https://user-images.githubusercontent.com/18663291/182146409-62f2b355-f2e7-4cb0-a882-8bfd11c4d634.png)

Die Verlinkung mit $w führt ins Leere, weil alle $w kombiniert werden:
https://opac.rism.info/search?id=990053206%20806038230%20136722%20800228397%20993122146&View=rism&Language=en

Können die 787-Felder getrennt angezeigt werden? 

**Verwandte Quelle**:  990053206   Purcell, Henry. 'A collection of ayres compos'd for the theatre and upon other occasions'. London: Printed by J. Heptinstall, for Frances Purcell, 1697. p.42. 

**Verwandte Quelle**: 806038230  [Correlated source]   British Library Add MS 35043 (a 1) 

**Verwandte Quelle**: 136722 [Correlated source]    University of California, William Andrews Clark Memorial Library, Finney partbooks (a 4), p.76. 

usw.

Quelle in Muscat: https://muscat.rism.info/admin/sources/806918368

**Comment by BernLutz** [comment]
Die Anzeige von Feld 787 wurde korrigiert @jenniferward
