### ISSUE TITLE
RISM-App

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#43]
Eine eigenständige RISM-App wird erwünscht.

**Comment by bjoernkessler** [comment]
Ich denke nicht, dass das als _Verbesserung_ des vorhandenen OPAC umsetzbar ist.

**Comment by jenniferward** [comment]
Eine App könnten wir evtl. verkaufen. 

Manchmal sitzen unsere Mitarbeiter/Nutzer in Archiven, die kein Internet haben, und eine Recherche in RISM ist unmöglich. Eine offline-Lösung wäre schon nützlich. (Ich werde in Kürze etwas ähnliches für Muscat vorschlagen...)

**Comment by jenniferward** [comment]
Unter "enhancement" verstehe ich übrigens nicht unbedingt "Verbesserung" sondern eher "Funktionsvielfalt  erweitern", d.h. etwas ganz neues einführen.
