### ISSUE TITLE
Bereicherung von Personendaten um weitere externe Nachweise (via VIAF)

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#44]
Bereicherung von Personendaten um weitere externe Nachweise (via VIAF).

**Comment by jenniferward** [comment]
@alexandermarxen : Aus einer alten Tabelle. Ist das noch erwünscht?

**Comment by alexandermarxen** [comment]
VIAF ist inzwischen vorhanden. Für weitere externe Nachweise gibt es zur Zeit keine konkreten Anforderungen.
