### ISSUE TITLE
Personen mit bestimmten Funktionen fehlen in der Vollanzeige

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#5]
Personen mit bestimmten Funktionsbezeichnungen (z.B. trl für Übersetzer) werden nicht angezeigt.
Beispiel:
https://opac.rism.info/search?id=1001032605&View=rism

**Comment by alexandermarxen** [comment]
Da sie in der XML-Datei vorhanden sind liegt es vermutlich am Indikator "Funktionsbezeichnung". Daher wäre zu prüfen, ob weitere Indikatoren zu diesem Fehler führen.

**Comment by alexandermarxen** [comment]
Siehe auch #93

**Comment by jenniferward** [comment]
Wir haben dieses Problem nur zufällig entdeckt. Wir müssen hier die Kommunikation verbessern.  

Hier die aktuelle Liste von allen Funktionen für die Personen (700) auf Englisch. Alle Personen mit diesen Funktionen sollen angezeigt werden. 
- Arranger [arr]
- Author [aut]
- Censor [cns]
- Co-composer [ctb]
- Composer cross-reference [cmp]
- Conceptor [ccp] 
- Copyist [scr]
- Dedicatee [dte]
- Distributor [dst]
- Editor [edt]
- Engraver [egr]
- Former owner [fmo]
- Illustrator [ill]
- Librettist [lbt]
- Lithographer [ltg]
- Other [oth]
- Performer [prf]
- Printer [prt]
- Publisher [pbl]
- Text author [lyr]
- Translator [trl]

Falls dasselbe Problem auch bei den Körperschaften (710) auftaucht, hier alle Funktionen für 710. Alle Körperschaften mit diesen Funktionen sollen angezeigt werden. 
- Bookseller [bsl]
- Copyist [scr]
- Dedicatee [dte]
- Depositor [dpt]
- Distributor [dst]
- Editor [edt]
- Event place [evp]
- Former owner [fmo]
- Other [oth]
- Performer [prf]
- Printer [prt]
- Publisher [pbl]

**Comment by BernLutz** [comment]
Die Personen (700) und Institutionen (710) werden entsprechend ihrer $4-Ansetzung angezeigt.
