### ISSUE TITLE
Exemplarspezifische Anmerkungen für Drucke

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#53]
Bei den Drucken: Exemplarspezifische Daten sind im bibliographischen Teil sichtbar.
Beispiel: 
https://opac.rism.info/search?id=00000990022818&View=rism

506: Ansicht im Lesesaal (wird im OPAC nicht veröffentlicht)
700: Weilenmann gehört zum Exemplareintrag
500: "Handschriftlicher Besitzervermerk..."

**Comment by MFalletta** [comment]
Das ist vor allem verwirrend, wenn viele Eemplare überliefert sind.
Beispiel:
https://opac.rism.info/search?id=00000990026684&View=rism
80 Exemplare nachgewiesen, einige davon überarbeitet.
Die Angaben in den Blöcken "Weitere Angaben und Bemerkungen" und "Provenienz und Fundort" stammen aus den Exemplaren D-AAm, D-Dl, D-LEu und D-Sla

**Comment by jenniferward** [comment]
Rückmeldung von einer RISM-Mitarbeiterin: Die Anzeige im OPAC verwirrt, da sie ja alles in die richtigen Felder eingegeben hat.

**Comment by BernLutz** [comment]
Wurde durch das neue Drucke-Template gelöst.
