### ISSUE TITLE
Byzantinische Tonarten werden nicht entschlüsselt 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#57]
Der OPAC enthält griechischen Quellen mit griechischen Tonarten. Leider werden die Tonarten nur in verschlüsselter Form angezeigt. Sie sind auch nur in verschlüsselter Form suchbar. 

In der Trefferliste ist die verschlüsselte Form nicht verständlich.
Beispiel:
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22ks30006002%22
![image](https://user-images.githubusercontent.com/18663291/45682612-0ec72280-bb41-11e8-9799-699880156f28.png)

Auch in der Vollanzeige sind die Tonarten nicht verständlich:
https://opac.rism.info/search?id=1001034415&View=rism
![image](https://user-images.githubusercontent.com/18663291/45682646-2e5e4b00-bb41-11e8-8340-40b4e3dbbd42.png)

Die byzantinischen Tonarten bitte so entschlüsseln: 
Code | Entschlüsselte Form
1byz | Ēchos prōtos (First mode of Byzantine music)
2byz | Ēchos deuteros (Second mode of Byzantine music)
3byz | Ēchos tritos (Third mode of Byzantine music)
4byz | Ēchos tetartos (Fourth mode of Byzantine music)
5byz | Ēchos plagios prōtos (First plagal mode of Byzantine music)
6byz | Ēchos plagios deuteros (Second plagal mode of Byzantine music)
7byz | Ēchos barys (Third plagal mode of Byzantine music)
8byz | Ēchos plagios tetartos (Fourth plagal mode of Byzantine music

**Comment by BernLutz** [comment]
@jenniferward sollen die englischen Bezeichnungen für alle Sprachen als Standardeinstellung verwendet werden oder möchten Sie hier auch noch eine deutsche Version anbieten? Dies ist für alle anderen Tonarten aktuell der Fall.

**Comment by jenniferward** [comment]
Das überlasse ich meinen deutschen Kollegen @MFalletta ?

**Comment by MFalletta** [comment]
Folgende Begriffe bitte für die deutsche Version anbieten:

1byz | Ēchos prōtos (1. Echos - dorisch)
2byz | Ēchos deuteros (2. Echos - phrygisch)
3byz | Ēchos tritos (3. Echos - lydisch)
4byz | Ēchos tetartos (4. Echos - mixolydisch)
5byz | Ēchos plagios prōtos (1. Plagale Echos - hypodorisch)
6byz | Ēchos plagios deuteros (2. Plagale Echos - hypophrygisch)
7byz | Ēchos barys (3. Plagale Echos - hypolydisch)
8byz | Ēchos plagios tetartos (4. Plagale Echos - hypomixolydisch)
