### ISSUE TITLE
Popup-Fenster für Besetzung geht nicht

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#59]
Englische Suche, in der Erweiterten Suche, Feld Scoring: Im alten OPAC bekam man ein Popup-Fenster mit allen Abkürzungen angeboten. Das Fenster wird seit dem neuen Release nicht mehr angeboten. Meines Wissens war das Fenster in Typo3 vorhanden. Bitte wiederherstellen!

Die deutsche Seite funktioniert wie erwartet.

**Comment by BernLutz** [comment]
Das Popup-Fenster wird wieder angezeigt.
