### ISSUE TITLE
Anzeige der Lebensdaten bei Personen

### ISSUE THREAD

**Issue by alexandermarxen** [rism-international/opac-report#6]
Wenn nur eine Jahreszahl (Geburts- ODER Sterbe-datum) vorhanden ist, werden die Lebensdaten nicht überall korrekt angezeigt.
Beispiel:
https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe30005730%22
Richtig angezeigt werden die Lebensdaten in der Trefferliste (aber nur beim Personendatensatz): 1699+
In der Vollanzeige der Quellen und in der Trefferliste (Musikquellen): 1699-
In der Vollanzeige des Personen-Datensatzes: 1699-1699

**Comment by alexandermarxen** [comment]
Bitte in all diesen Fällen das Feld 100 $d als Grundlage verwenden. Es ist weder für uns und erst Recht nicht für die Nutzer ersichtlich aus welcher Quelle beispielsweise die Lebensdaten von Josquin des Prez importiert wurden:
https://opac.rism.info/search?id=pe20000367&View=rism
(1521-1521-08-27) [!]
In der MarcXML steht im Feld 100 $d 1450p-1521
Grundsätzlich: Falls die BSB Informationen aus anderen Quellen (beispielsweise DNB) importiert, müssen diese eindeutig als importierte Informationen gekennzeichnet werden.

**Comment by alexandermarxen** [comment]
Ist leider bei der neuen Version noch nicht behoben:
![Alles   A Kempis - RISM](https://user-images.githubusercontent.com/42838336/64174261-2fbf7b00-ce59-11e9-8566-4b9ce288fefe.png)

**Comment by MFalletta** [comment]
> Bitte in all diesen Fällen das Feld 100 $d als Grundlage verwenden. Es ist weder für uns und erst Recht nicht für die Nutzer ersichtlich aus welcher Quelle beispielsweise die Lebensdaten von Josquin des Prez importiert wurden:
> https://opac.rism.info/search?id=pe20000367&View=rism
> (1521-1521-08-27) [!]
> In der MarcXML steht im Feld 100 $d 1450p-1521
> Grundsätzlich: Falls die BSB Informationen aus anderen Quellen (beispielsweise DNB) importiert, müssen diese eindeutig als importierte Informationen gekennzeichnet werden.

![Lebensdaten vom 2019-09-05 15-01-13](https://user-images.githubusercontent.com/18736235/64344285-75617c80-cfee-11e9-8e86-bdba7c73f615.png)
Diese Lebensdaten sind schwer zu lesen!

**Comment by BernLutz** [comment]
100 $d wird nun als Standard angezeigt.

**Comment by alexandermarxen** [comment]
Nach der Überarbeitung der Normdatenanzeige wird leider wieder etwas Anderes als 100 $d für die Anzeige verwendet.

**Comment by BernLutz** [comment]
Für die Anzeige der Lebensdaten wird nun wieder 100 $d verwendet.

**Comment by alexandermarxen** [comment]
Vielen Dank, leider hatte es nur kurz Bestand, inzwischen stimmt die Angabe leider wieder nicht mehr, vgl. https://opac.rism.info/metaopac/perma.do?v=rism&q=-1%3d%22pe30005730%22

**Comment by BernLutz** [comment]
Vielen Dank für den Hinweis @alexandermarxen 

Das Problem bei der Anzeige trat durch folgende Elemente auf:
 .sc / + * 

Wir werten jetzt den Inhalt  aus 100$d aus, z. B.:

Agostini, Agostino (1569+): https://opac.rism.info/search?id=pe50051657&View=rism
Copyist of Salzburg 721 (19.sc): https://opac.rism.info/search?id=pe50052233&View=rism 
Courteille, Charles Pavet de (1788*): https://opac.rism.info/search?id=pe50051695&View=rism 
Zierenberg, Christian (20/21): https://opac.rism.info/search?id=pe30091101&View=rism
