### ISSUE TITLE
Grammatikfehler im Suchkästchen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#61]
Auf der Startseite auf Englisch:
https://opac.rism.info/index.php?id=15&L=1
![image](https://user-images.githubusercontent.com/18663291/45683734-a417e600-bb44-11e8-804f-ab3dcc4ca9a3.png)

ist der Text im Suchkästchen "Search for music, composer and more" nicht richtig. "Composer" soll auf jeden Fall im Plural stehen. "Music" ist etwas irreführend, besser wäre Musikquellen. 

Bitte ändern in:
Search for musical sources, composers, and more

**Comment by BernLutz** [comment]
Erledigt!
