### ISSUE TITLE
Autocomplete soll man ein- und einschalten können

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#67]
Es stört manche Nutzer, dass das Autocomplete ständig eingeschaltet ist. Kann es möglich sein, das Autocomplete auszuschalten?

**Comment by jenniferward** [comment]
Das kam aus der Nutzerstudie. Ehrlich gesagt stört das mich nicht. @alexandermarxen @MFalletta , Meinungen?

**Comment by BernLutz** [comment]
Ist dieser Punkt noch aktuell @jenniferward ?

**Comment by jenniferward** [comment]
Nein, seit der Nutzerstudie habe ich nichts  gehört. Ich schließe das Ticket.
