### ISSUE TITLE
Zusätzliche Autocompletes anbieten

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#68]
Erweiterte Suche: Wenn ein Feld ein Freitextfeld ist, ist es den Nutzern nicht immer klar, was man eingeben kann.

Bitte Autocomplete ermöglichen für die Felder:
-Werkverzeichnis (Kurztitel, Title und Autor anbieten)
-Liturgisches Fest
-Schlagwort
-Textsprache #7

**Comment by BernLutz** [comment]
Folgende Felder werden als AC angeboten:
-Liturgisches Feste
-Schlagwort
-Textsprache

Beim Werkverzeichnis ist dies in dieser Form leider nicht möglich, daher schließe ich das Ticket.
