### ISSUE TITLE
2.1. Verbesserte Suche nach Textsprache (Fehlerbereinigung Wartung von SH)

### ISSUE THREAD

**Issue by rism-international** [rism-international/opac-report#7]
Das Beispiel Low German ist in der Suche nach wie vor nicht zu finden. Man findet aber Niederdeutsch (27 Treffer). Autolookup wurde nicht eingerichtet
Beipiel: https://opac.rism.info/search?id=450032828&View=rism

**Comment by jenniferward** [comment]
In der erweiterten Suche auf English sind viele Sprachen über ihren Namen nicht suchbar und müssen über die [ISO-Codes](https://www.loc.gov/standards/iso639-2/php/code_list.php) gesucht werden. 

Deutsch hat m.W. das gleiche Problem aber mit anderen Sprachen.

Ein Autocomplete würde helfen, oder vielleicht wäre ein Popup-Fenster besser.

Diese Sprachen sind auf Englisch nicht suchbar und müssen mit den Codes gesucht werden:
Aragonese (arg)
Croatian (hrv)
Luxembourgish (ltz)
Low German (nds)
Neapolitan (nap)
Northern Frisian (frr)
Occitan (oci)
Romansh (roh)
Sicilian (scn)
Lower Sorbian (dsb)
Upper Sorbian (hsb)
Swiss German (gsw)

**Comment by BernLutz** [comment]
Die fehlenden Sprachen werden nun über die Autocomplete angeboten.
