### ISSUE TITLE
Verwirrende Manuskriptdatierung wie 1840 (1840c) 

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#87]
In den Daten wurden bisher viele Abkürzungen bei der Manuskriptdatierung  benutzt, die für die Nutzer nicht selbsterklärend sind.

Im Feld 260 $c bitte alle Abkürzungen ersetzen wie folgt:

Text | Deutsch | Englisch
1782a | vor 1782 | before 1782
1782c | circa 1782 | circa 1782
1782p | nach 1782 | after 1782
18.in | Anfang des 18. Jahrhunderts | beginning of the 18th century
18.me | Mitte des 18. Jahrhunderts | middle of the 18th century
18.ex | Ende des 18. Jahrhunderts | end of the 18th century
18.1t | 1. Drittel des 18. Jahrhunderts | 1st third of the 18th century
18.2t | 2. Drittel des 18. Jahrhunderts | 2nd third of the 18th century
18.3t | 3. Drittel des 18. Jahrhunderts | 3rd third of the 18th century
18.1q | 1. Viertel des 18. Jahrhunderts | 1st quarter of the 18th century
18.2q | 2. Viertel des 18. Jahrhunderts | 2nd quarter of the 18th century
18.3q | 3. 	Viertel des 18. Jahrhunderts | 3rd quarter of the 18th century
18.4q | 4. 	Viertel des 18. Jahrhunderts | 4th quarter of the 18th century
18.1d | 1. 	Hälfte des 18. Jahrhunderts | 1st half of the 18th century
18.2d | 2. 	Hälfte des 18. Jahrhunderts | 2nd half of the 18th century
18.sc | 18. Jahrhundert | 18th century
18/19 | 18./19. Jahrhundert | 18th/19th century

**Comment by jenniferward** [comment]
@Docudoctor @MFalletta Ist dieses Ticket noch relevant? Es scheint eine Datenfrage zu sein und keine OPAC-Frage.

**Comment by MFalletta** [comment]
Wenn zwei Angaben - wie im Betreff "1840 (1840c)" - vorhanden sind, wurde der Klammerausdruck nicht umgesetzt. Diese Fälle sehe ich immer wieder. Das stammt noch aus Kallisto, wo es ein Zahlen- und ein Textfeld - für die Datierung gab. ca-Angaben o.ä. konnten nur im Textfeld gemacht werden, aber es musste auch das Zahlenfeld ausgefüllt sein.

Das ist inzwischen eigentlich ein Ticket für Muscat, nicht für den OPAC.
