### ISSUE TITLE
Weitere Namen werden im OPAC nicht angezeigt

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#93]
In diesem Titel https://opac.rism.info/search?id=00000990059797&View=rism kommt das Feld 700 zwei Mal vor. Die zwei Personen sind auch in der MARC-Datei zu sehen:
https://opac.rism.info/id/rismid/00000990059797?format=marc
Reuchlin, Johannes und Böschenstein, Johann

Nur Böschenstein wird im OPAC angezeigt aber der Name Reuchlin, Johannes wird anscheinend indexiert.

Bitte alle Namen/700s anzeigen.

**Comment by alexandermarxen** [comment]
Siehe #5 
Vermutlich gibt es auch keine Umsetzung für den Indikator "aut"

**Comment by BernLutz** [comment]
Die Felder werden nun angezeigt. Wir arbeiten noch an der Verlinkung zum Normdatensatz.

**Comment by BernLutz** [comment]
Die Verlinkungen sind gesetzt.
