### ISSUE TITLE
Letzte Aktualisierung anzeigen

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#95]
Es würde dem Leser helfen, zu wissen, wann ein Titel zuletzt aktualisiert (bzw. erstellt) wurde. 

Solche Daten werden mitgeliefert: Die Angabe des Erstellungs- bzw. Änderungsdatums befindet sich in MARC21 controlfield 005.

Am Ende des Datensatzes soll stehen:
Letzte Aktualisierung: [Datum]
Last update: [date in Form 19 September 2018]

#94

**Comment by jenniferward** [comment]
Aus gegebenem Anlass - vielleicht ist es nur eine Frage der Anzeige?

N.B.: Nur das Datum der letzten Aktualisierung kann angezeigt werden. Das Erstellungsdatum ist, so weit ich es sehen kann, nicht in den MARC-Daten drin.

**Comment by BernLutz** [comment]
Haben Sie vielen Dank für den Hinweis auf das Ticket @jenniferward

**Comment by BernLutz** [comment]
Mit der Auswertung von controlfield 005 würden die neuen und die aktualisierten Titel erfasst. Wäre folgende Filterbezeichnung in Ihrem Sinne @jenniferward @MFalletta  ?
DE: Neue oder aktualisierte Titel
EN: New or updated titles
FR: Titres nouveaux ou mis à jour
ES: Títulos nuevos o actualizados
IT: Titoli nuovi o aggiornati

**Comment by MFalletta** [comment]
Anstelle von "Titel" würde ich Datensätze oder evtl. Einträge bevorzugen. Auch um etwaige Verwechslungen zu vermeiden.
DE: Neue oder aktualisierte Datensätze
FR: Enregistrements nouveaux ou mis à jour
IT: Record nuovi e aggiornati

**Comment by jenniferward** [comment]
EN: New or updated records
ES: Registros nuevos o actualizados

**Comment by BernLutz** [comment]
![grafik](https://user-images.githubusercontent.com/44613113/142403701-403f43aa-d893-4544-be77-7d65f240b208.png)
Das Datum der letzten Aktualisierung eines Datensatzes würden wir wie im Screenshot anzeigen.
Die Label wären:

DE: Letzte Aktualisierung
EN: Last update
FR: Dernière mise à jour
IT: Ultimo aggiornamento
ES: Última actualización

Einverstanden @jenniferward @MFalletta ?

**Comment by MFalletta** [comment]
Einverstanden !!!

**Comment by jenniferward** [comment]
Ja, einverstanden, vielen Dank!
