### ISSUE TITLE
Vorgaben für Standardbesetzungen sollen vorhanden sein

### ISSUE THREAD

**Issue by jenniferward** [rism-international/opac-report#99]
Vorgaben für Standardbesetzungen sollen vorhanden sein

Besetzung | Deutsch | Englisch

vl (2), vla, vlc | Streichquartett | String quartet
vl (2), vla (2), vlc | Streichquintett (2 Bratschen) | String quintet (2 violas)
vl (2), vla, vlc (2) | Streichquintett (zwei Celli) | String quintet (2 cellos)
vl (2), vla, vlc, cb | Streichquintett | String quintet (with double bass)
vl, vlc, pf | Klaviertrio | Piano trio
fl, ob, cl, cor, fag | Bläserquintett | Wind quintet
fl (4) | Flötenquartett | Flute quartet (all flutes)
fl, vl, vla, vlc | Flötenquartett | Flute quartet (flute with strings)

**Comment by jenniferward** [comment]
@MFalletta @alexandermarxen : Aus der Nutzerstudie. Was haben wir damit gemeint? :-)  Kommt das in den Hilfetext oder ist "Streichquartett" eine Besetzung...?

**Comment by bjoernkessler** [comment]
Das sieht mir ehrlich gesagt nach dem Ruf nach Normdaten für die Besetzung aus und würde damit eher in unsere interne Diskussion gehören. Was meinen Sie @jenniferward?

Wenn dem so wäre würde ich vorschlagen den issue vorerst zu schließen.

**Comment by jenniferward** [comment]
Ich warte auf eine Reaktion von @MFalletta und @alexandermarxen.

**Comment by alexandermarxen** [comment]
Wenn ich mich richtig erinnere, war die Idee, dass man möglichst einfach nach Besetzungen wie Streichquartett suchen können soll. Viele unerfahrene Nutzer geben diese Begriffe ein und finden natürlich nur ein Bruchteil der vorhandenen Quellen.
Ich glaube, wir hatten angedacht, dass eine derartige Anfrage entweder (automatisch) umgesetzt wird oder ein entsprechender Suchvorschlag im Dropdownmenü erscheint. Beides würde wohl zunächst eine Umsetzung der Besetzung bzw. des Besetzungshinweises in eine Normdatei oder in einen Thesaurus erfordern.

**Comment by MFalletta** [comment]
Ich denke auch, dass die BSB hier wenig machen kann. Wir sind in der Pflicht und benötigen den Thesaurus. Von mir aus kann der issue erstmal geschlossen werden.
